/* ==========================================================================
   equips.js - 装備品マスタデータベース (ハクスラ厳選重視・デフレ調整版)
   全252アイテム：12カテゴリ × 21段階 (1, 10, 20...200)
   ========================================================================== */

const EQUIP_MASTER = [
    // --- Rank 1 ---
    { eid:1, noRandom: false, rank: 1, name: "ひのきのぼう", type: "武器", baseName: "剣", data: { atk: 10, hit: 10}, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:2, noRandom: false, rank: 1, name: "石のオノ", type: "武器", baseName: "斧", data: { atk: 20, hit: -10}, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:3, noRandom: false, rank: 1, name: "銅のナイフ", type: "武器", baseName: "短剣", data: { atk: 5, spd: 5, mag: 5 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:4, noRandom: false, rank: 1, name: "樫の杖", type: "武器", baseName: "杖", data: { mag: 12 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:5, noRandom: false, rank: 1, name: "たけのやり", type: "武器", baseName: "槍", data: { atk: 15 } },
    { eid:6, noRandom: false, rank: 1, name: "おもちゃの弓", type: "武器", baseName: "弓", data: { atk: 15, hit: -5, cri: 1 } },
    { eid:7, noRandom: false, rank: 1, name: "おなべのふた", type: "盾", baseName: "盾", data: { def: 5 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:8, noRandom: false, rank: 1, name: "銅のバングル", type: "盾", baseName: "腕輪", data: { def: 2, atk: 3 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:9, noRandom: false, rank: 1, name: "皮のぼうし", type: "頭", baseName: "兜", data: { def: 3, hp: 5 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { eid:10, noRandom: false, rank: 1, name: "ターバン", type: "頭", baseName: "帽子", data: { def: 2, mag: 3 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:11, noRandom: false, rank: 1, name: "布の服", type: "体", baseName: "鎧", data: { def: 8 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:12, noRandom: false, rank: 1, name: "旅人の服", type: "体", baseName: "ローブ", data: { def: 5, mag: 5 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { eid:13, noRandom: false, rank: 1, name: "皮のくつ", type: "足", baseName: "ブーツ", data: { spd: 5, def: 2 }, possibleOpts: ['def', 'spd', 'finRed', 'elmRes'] },
    { eid:14, noRandom: false, rank: 1, name: "わらじ", type: "足", baseName: "くつ", data: { spd: 8 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 10 ---
    { eid:21, noRandom: false, rank: 10, name: "銅のつるぎ", type: "武器", baseName: "剣", data: { atk: 45 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:22, noRandom: false, rank: 10, name: "鉄のオノ", type: "武器", baseName: "斧", data: { atk: 65, spd: -10 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:23, noRandom: false, rank: 10, name: "鉄のナイフ", type: "武器", baseName: "短剣", data: { atk: 25, spd: 15, mag: 15 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:24, noRandom: false, rank: 10, name: "魔導士の杖", type: "武器", baseName: "杖", data: { mag: 40 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:25, noRandom: false, rank: 10, name: "鉄のやり", type: "武器", baseName: "槍", data: { atk: 55 } },
    { eid:26, noRandom: false, rank: 10, name: "ショートボウ", type: "武器", baseName: "弓", data: { atk: 50, hit: -5, cri: 3 } },
    { eid:27, noRandom: false, rank: 10, name: "皮のたて", type: "盾", baseName: "盾", data: { def: 25 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:28, noRandom: false, rank: 10, name: "鉄の腕輪", type: "盾", baseName: "腕輪", data: { def: 10, atk: 15 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:29, noRandom: false, rank: 10, name: "木のヘルメット", type: "頭", baseName: "兜", data: { def: 18, hp: 15 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:30, noRandom: false, rank: 10, name: "羽根ぼうし", type: "頭", baseName: "帽子", data: { def: 12, mag: 15 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:31, noRandom: false, rank: 10, name: "皮のよろい", type: "体", baseName: "鎧", data: { def: 40 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:32, noRandom: false, rank: 10, name: "稽古着", type: "体", baseName: "ローブ", data: { def: 30, mag: 25 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:33, noRandom: false, rank: 10, name: "鉄のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 25, def: 10 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:34, noRandom: false, rank: 10, name: "旅人のくつ", type: "足", baseName: "くつ", data: { spd: 40 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 20 ---
    { eid:41, noRandom: false, rank: 20, name: "鉄のつるぎ", type: "武器", baseName: "剣", data: { atk: 85 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:42, noRandom: false, rank: 20, name: "バトルアックス", type: "武器", baseName: "斧", data: { atk: 120, spd: -15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:43, noRandom: false, rank: 20, name: "どくがのナイフ", type: "武器", baseName: "短剣", data: { atk: 50, spd: 30, attack_Poison: 10 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:44, noRandom: false, rank: 20, name: "ルーンスタッフ", type: "武器", baseName: "杖", data: { mag: 90, mp: 30 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:45, noRandom: false, rank: 20, name: "パルチザン", type: "武器", baseName: "槍", data: { atk: 100, spd: 5 } },
    { eid:46, noRandom: false, rank: 20, name: "クロスボウ", type: "武器", baseName: "弓", data: { atk: 95, hit: -6, cri: 5 } },
    { eid:47, noRandom: false, rank: 20, name: "鉄のたて", type: "盾", baseName: "盾", data: { def: 55 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:48, noRandom: false, rank: 20, name: "銀のバングル", type: "盾", baseName: "腕輪", data: { def: 25, atk: 35 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:49, noRandom: false, rank: 20, name: "鉄かぶと", type: "頭", baseName: "兜", data: { def: 45, hp: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:50, noRandom: false, rank: 20, name: "魔道士の帽子", type: "頭", baseName: "帽子", data: { def: 30, mag: 40 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:51, noRandom: false, rank: 20, name: "鎖かたびら", type: "体", baseName: "鎧", data: { def: 90, finRed: 3 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:52, noRandom: false, rank: 20, name: "絹のローブ", type: "体", baseName: "ローブ", data: { def: 60, mag: 55 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:53, noRandom: false, rank: 20, name: "鋼のブーツ", type: "足", baseName: "ブーツ", data: { spd: 70, def: 30 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:54, noRandom: false, rank: 20, name: "ラバーソール", type: "足", baseName: "くつ", data: { spd: 110 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 30 ---
    { eid:61, noRandom: false, rank: 30, name: "はがねのつるぎ", type: "武器", baseName: "剣", data: { atk: 150 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:62, noRandom: false, rank: 30, name: "鋼鉄のギロチン", type: "武器", baseName: "斧", data: { atk: 210, spd: -25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:63, noRandom: false, rank: 30, name: "アサシンダガー", type: "武器", baseName: "短剣", data: { atk: 90, spd: 50, attack_InstantDeath: 2 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:64, noRandom: false, rank: 30, name: "まどろみの杖", type: "武器", baseName: "杖", data: { mag: 150 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:65, noRandom: false, rank: 30, name: "はがねのやり", type: "武器", baseName: "槍", data: { atk: 180 } },
    { eid:66, noRandom: false, rank: 30, name: "ロングボウ", type: "武器", baseName: "弓", data: { atk: 175, hit: -8, cri: 7 } },
    { eid:67, noRandom: false, rank: 30, name: "はがねのたて", type: "盾", baseName: "盾", data: { def: 110 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:68, noRandom: false, rank: 30, name: "鋼鉄の腕輪", type: "盾", baseName: "腕輪", data: { def: 45, atk: 70 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:69, noRandom: false, rank: 30, name: "はがねのかぶと", type: "頭", baseName: "兜", data: { def: 85, hp: 80 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:70, noRandom: false, rank: 30, name: "銀の髪飾り", type: "頭", baseName: "帽子", data: { def: 55, mag: 75 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:71, noRandom: false, rank: 30, name: "鉄のよろい", type: "体", baseName: "鎧", data: { def: 180, finRed: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:72, noRandom: false, rank: 30, name: "魔道士の服", type: "体", baseName: "ローブ", data: { def: 110, mag: 110 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:73, noRandom: false, rank: 30, name: "銀のブーツ", type: "足", baseName: "ブーツ", data: { spd: 140, def: 50 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:74, noRandom: false, rank: 30, name: "俊足のサンダル", type: "足", baseName: "くつ", data: { spd: 220 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 40 ---
    { eid:81, noRandom: false, rank: 40, name: "破邪の剣", type: "武器", baseName: "剣", data: { atk: 240, elmAtk: {'光':5} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:82, noRandom: false, rank: 40, name: "大地のオノ", type: "武器", baseName: "斧", data: { atk: 330, spd: -35, elmAtk: {'火':5} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:83, noRandom: false, rank: 40, name: "ミスリルナイフ", type: "武器", baseName: "短剣", data: { atk: 150, spd: 80, mag: 60 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:84, noRandom: false, rank: 40, name: "ホーリーランス", type: "武器", baseName: "槍", data: { atk: 280, elmAtk: { '光': 5 } } },
    { eid:85, noRandom: false, rank: 40, name: "狩人の弓", type: "武器", baseName: "弓", data: { atk: 270, hit: -10, cri: 10 } },
    { eid:86, noRandom: false, rank: 40, name: "マジカルスタッフ", type: "武器", baseName: "杖", data: { mag: 250, mp: 50 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:87, noRandom: false, rank: 40, name: "魔法の盾", type: "盾", baseName: "盾", data: { def: 180, elmRes: {'火':5, '水':5} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:88, noRandom: false, rank: 40, name: "黄金のブレスレット", type: "盾", baseName: "腕輪", data: { def: 75, atk: 120 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:89, noRandom: false, rank: 40, name: "知力の兜", type: "頭", baseName: "兜", data: { def: 130, mag: 25 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { eid:90, noRandom: false, rank: 40, name: "黄金のティアラ", type: "頭", baseName: "帽子", data: { def: 90, mag: 140 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:91, noRandom: false, rank: 40, name: "はがねのよろい", type: "体", baseName: "鎧", data: { def: 300, finRed: 8 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:92, noRandom: false, rank: 40, name: "魔法の法衣", type: "体", baseName: "ローブ", data: { def: 180, mag: 180, elmRes: {'光':5} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { eid:93, noRandom: false, rank: 40, name: "黄金のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 200, def: 90 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { eid:94, noRandom: false, rank: 40, name: "魔法のサンダル", type: "足", baseName: "くつ", data: { spd: 320, mag: 25 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 50 ---
    { eid:101, noRandom: false, rank: 50, name: "ドラゴンキラー", type: "武器", baseName: "剣", data: { atk: 400 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'],traits: [{ id: 36, level: 5 } ] },
    { eid:102, noRandom: false, rank: 50, name: "魔神のオノ", type: "武器", baseName: "斧", data: { atk: 550, spd: -50 ,hit: -30 ,cri : 30 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:103, noRandom: false, rank: 50, name: "グラディウス", type: "武器", baseName: "短剣", data: { atk: 220, spd: 120, mag: 100 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:104, noRandom: false, rank: 50, name: "賢者の杖", type: "武器", baseName: "杖", data: { mag: 420, mp: 100 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:105, noRandom: false, rank: 50, name: "トライデント", type: "武器", baseName: "槍", data: { atk: 480, elmAtk: { '水': 10 } } },
    { eid:106, noRandom: false, rank: 50, name: "コンポジットボウ", type: "武器", baseName: "弓", data: { atk: 460, hit: -10, cri: 12 } },
    { eid:107, noRandom: false, rank: 50, name: "ドラゴンシールド", type: "盾", baseName: "盾", data: { def: 320, elmRes: {'火':10} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:108, noRandom: false, rank: 50, name: "竜のうろこ", type: "盾", baseName: "腕輪", data: { def: 140, atk: 180 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:109, noRandom: false, rank: 50, name: "ミスリルヘルム", type: "頭", baseName: "兜", data: { def: 240, hp: 150 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { eid:110, noRandom: false, rank: 50, name: "司祭の帽子", type: "頭", baseName: "帽子", data: { def: 160, mag: 220 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:111, noRandom: false, rank: 50, name: "魔法の鎧", type: "体", baseName: "鎧", data: { def: 500, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:112, noRandom: false, rank: 50, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 320, mag: 300, elmRes: {'全':5} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { eid:113, noRandom: false, rank: 50, name: "ミスリルブーツ", type: "足", baseName: "ブーツ", data: { spd: 400, def: 180 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { eid:114, noRandom: false, rank: 50, name: "フェザーシューズ", type: "足", baseName: "くつ", data: { spd: 650, spdMod: 5 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 60 ---
    { eid:121, noRandom: false, rank: 60, name: "プラチナソード", type: "武器", baseName: "剣", data: { atk: 600 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:122, noRandom: false, rank: 60, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 850, spd: -80 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:123, noRandom: false, rank: 60, name: "ソウルブレイカー", type: "武器", baseName: "短剣", data: { atk: 350, spd: 200, mag: 150 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:124, noRandom: false, rank: 60, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 650, mp: 150 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:125, noRandom: false, rank: 60, name: "プラチナランス", type: "武器", baseName: "槍", data: { atk: 720, def: 50 } },
    { eid:126, noRandom: false, rank: 60, name: "プラチナボウ", type: "武器", baseName: "弓", data: { atk: 700, hit: -12, cri: 15 } },
    { eid:127, noRandom: false, rank: 60, name: "プラチナシールド", type: "盾", baseName: "盾", data: { def: 520, resists_Debuff: 5 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:128, noRandom: false, rank: 60, name: "ミスリルバングル", type: "盾", baseName: "腕輪", data: { def: 220, atk: 280 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:129, noRandom: false, rank: 60, name: "プラチナヘッド", type: "頭", baseName: "兜", data: { def: 400, hp: 250 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:130, noRandom: false, rank: 60, name: "賢者のターバン", type: "頭", baseName: "帽子", data: { def: 280, mag: 380 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:131, noRandom: false, rank: 60, name: "ドラゴンメイル", type: "体", baseName: "鎧", data: { def: 750, elmRes: {'火':10} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:132, noRandom: false, rank: 60, name: "ミスリルケープ", type: "体", baseName: "ローブ", data: { def: 480, mag: 450 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:133, noRandom: false, rank: 60, name: "竜のブーツ", type: "足", baseName: "ブーツ", data: { spd: 750, def: 300 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:134, noRandom: false, rank: 60, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 1200, mp: 80 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 70 ---
    { eid:141, noRandom: false, rank: 70, name: "隼の剣", type: "武器", baseName: "剣", data: { atk: 850, doubleAction: 10 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:142, noRandom: false, rank: 70, name: "破壊の鉄球", type: "武器", baseName: "斧", data: { atk: 1250, spd: -120 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:143, noRandom: false, rank: 70, name: "フェニックスダガー", type: "武器", baseName: "短剣", data: { atk: 500, spd: 350, mag: 250, elmAtk: {'火':10} }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:144, noRandom: false, rank: 70, name: "精霊の杖", type: "武器", baseName: "杖", data: { mag: 900, elmAtk: {'全':5} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:145, noRandom: false, rank: 70, name: "竜の髭", type: "武器", baseName: "槍", data: { atk: 1050, spd: 20 } },
    { eid:146, noRandom: false, rank: 70, name: "風の弓", type: "武器", baseName: "弓", data: { atk: 1000, hit: -12, cri: 18, elmAtk: { '風': 10 } } },
    { eid:147, noRandom: false, rank: 70, name: "鏡の盾", type: "盾", baseName: "盾", data: { def: 750, elmRes: {'光':10} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:148, noRandom: false, rank: 70, name: "守りのルーン", type: "盾", baseName: "腕輪", data: { def: 350, resists_Debuff: 10 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:149, noRandom: false, rank: 70, name: "隼の兜", type: "頭", baseName: "兜", data: { def: 550, spd: 30 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { eid:150, noRandom: false, rank: 70, name: "精霊の帽子", type: "頭", baseName: "帽子", data: { def: 420, mag: 550 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:151, noRandom: false, rank: 70, name: "刃のよろい", type: "体", baseName: "鎧", data: { def: 1000, pierce: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:152, noRandom: false, rank: 70, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 680, mag: 700, elmRes: {'光':10} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { eid:153, noRandom: false, rank: 70, name: "天使のブーツ", type: "足", baseName: "ブーツ", data: { spd: 1100, def: 500 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { eid:154, noRandom: false, rank: 70, name: "韋駄天のくつ", type: "足", baseName: "くつ", data: { spd: 1800, fastestAction: 5 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 80 (はぐれメタルシリーズ) ---
    { eid:161, noRandom: false, rank: 80, name: "はぐれメタルの剣", type: "武器", baseName: "剣", data: { atk: 1200, spd: 50 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:162, noRandom: false, rank: 80, name: "はぐれメタルのオノ", type: "武器", baseName: "斧", data: { atk: 1800, spd: -180, attack_Fear: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:163, noRandom: false, rank: 80, name: "はぐれメタルの短剣", type: "武器", baseName: "短剣", data: { atk: 800, spd: 600, attack_Poison: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:164, noRandom: false, rank: 80, name: "はぐれメタルの杖", type: "武器", baseName: "杖", data: { mag: 1200, mp: 300 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:165, noRandom: false, rank: 80, name: "はぐれメタルのやり", type: "武器", baseName: "槍", data: { atk: 1500, spd: 30 } },
    { eid:166, noRandom: false, rank: 80, name: "はぐれメタルの弓", type: "武器", baseName: "弓", data: { atk: 1450, hit: -10, cri: 20 } },
    { eid:167, noRandom: false, rank: 80, name: "はぐれメタルの盾", type: "盾", baseName: "盾", data: { def: 1000, elmRes: {'火':10,'水':10,'風':10,'雷':10} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:168, noRandom: false, rank: 80, name: "はぐれメタルの腕輪", type: "盾", baseName: "腕輪", data: { def: 500, atk: 500 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:169, noRandom: false, rank: 80, name: "はぐれメタルヘルム", type: "頭", baseName: "兜", data: { def: 750, mp: 300, resists_Fear: 10 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:170, noRandom: false, rank: 80, name: "はぐれメタルの帽子", type: "頭", baseName: "帽子", data: { def: 580, mag: 850 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:171, noRandom: false, rank: 80, name: "はぐれメタルの鎧", type: "体", baseName: "鎧", data: { def: 1500, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:172, noRandom: false, rank: 80, name: "はぐれメタルのローブ", type: "体", baseName: "ローブ", data: { def: 1100, mag: 1000 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:173, noRandom: false, rank: 80, name: "はぐれメタルのブーツ", type: "足", baseName: "ブーツ", data: { spd: 2200, def: 800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:174, noRandom: false, rank: 80, name: "はぐれメタルのくつ", type: "足", baseName: "くつ", data: { spd: 3500 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 90 ---
    { eid:181, noRandom: false, rank: 90, name: "真魔剛竜剣", type: "武器", baseName: "剣", data: { atk: 1400, elmAtk: {'火':10} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:182, noRandom: false, rank: 90, name: "ギガントアックス", type: "武器", baseName: "斧", data: { atk: 2100, spd: -220, attack_Fear: 20 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:183, noRandom: false, rank: 90, name: "神速の暗器", type: "武器", baseName: "短剣", data: { atk: 950, spd: 800, mag: 300, attack_Poison: 25 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:184, noRandom: false, rank: 90, name: "ドラゴンの杖", type: "武器", baseName: "杖", data: { mag: 1500, elmAtk: {'火':15} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:185, noRandom: false, rank: 90, name: "ゲイボルグ", type: "武器", baseName: "槍", data: { atk: 1750, finDmg: 5 } },
    { eid:186, noRandom: false, rank: 90, name: "アルテミスの弓", type: "武器", baseName: "弓", data: { atk: 1700, hit: -15, cri: 25, mag: 100 } },
    { eid:187, noRandom: false, rank: 90, name: "覇者の盾", type: "盾", baseName: "盾", data: { def: 1300, resists_Debuff: 15 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:188, noRandom: false, rank: 90, name: "覇者の紋章", type: "盾", baseName: "腕輪", data: { def: 650, atk: 750 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:189, noRandom: false, rank: 90, name: "天獄の兜", type: "頭", baseName: "兜", data: { def: 1000, hp: 400 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { eid:190, noRandom: false, rank: 90, name: "星天のティアラ", type: "頭", baseName: "帽子", data: { def: 720, mag: 1100, resists_SpellSeal: 10 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:191, noRandom: false, rank: 90, name: "覇王の鎧", type: "体", baseName: "鎧", data: { def: 1800, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:192, noRandom: false, rank: 90, name: "プリンセスローブ", type: "体", baseName: "ローブ", data: { def: 1200, mag: 1200, elmRes: {'光':15,'闇':15} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { eid:193, noRandom: false, rank: 90, name: "冥府のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 2800, def: 1000, elmRes: {'闇':15} }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { eid:194, noRandom: false, rank: 90, name: "ペガサスの靴", type: "足", baseName: "くつ", data: { spd: 4500, fastestAction: 8 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },


    { eid:201, noRandom: false, rank: 100, name: "王者の剣", type: "武器", baseName: "剣", data: { atk: 1500, elmAtk: {'光':10}, attack_Fear: 5 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:202, noRandom: false, rank: 100, name: "天罰の巨斧", type: "武器", baseName: "斧", data: { atk: 2100, spd: -100, elmAtk: {'雷':10}, attack_Fear: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:203, noRandom: false, rank: 100, name: "トリトンダガー", type: "武器", baseName: "短剣", data: { atk: 900, spd: 400, attack_Poison: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:204, noRandom: false, rank: 100, name: "神鳥の杖", type: "武器", baseName: "杖", data: { mag: 1400, mp: 300, magCrit: 5 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:205, noRandom: false, rank: 100, name: "聖槍ロンギヌス", type: "武器", baseName: "槍", data: { atk: 1800, elmAtk: { '光': 15 } } },
    { eid:206, noRandom: false, rank: 100, name: "天之麻迦古弓", type: "武器", baseName: "弓", data: { atk: 1750, hit: -15, cri: 25 } },
    { eid:207, noRandom: false, rank: 100, name: "真・地獄の盾", type: "盾", baseName: "盾", data: { def: 1200, elmRes: {'闇':20}, resists_InstantDeath: 10 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:208, noRandom: false, rank: 100, name: "神の腕輪", type: "盾", baseName: "腕輪", data: { def: 550, atk: 600, finDmg: 5 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:209, noRandom: false, rank: 100, name: "天帝の冠", type: "頭", baseName: "兜", data: { def: 900, hp: 400, resists_Fear: 20 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:210, noRandom: false, rank: 100, name: "神の知恵袋", type: "頭", baseName: "帽子", data: { def: 650, mag: 1200, resists_SpellSeal: 20 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:211, noRandom: false, rank: 100, name: "天のゼウスメイル", type: "体", baseName: "鎧", data: { def: 2200, finRed: 10, elmRes: {'雷':20} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:212, noRandom: false, rank: 100, name: "常世の法衣", type: "体", baseName: "ローブ", data: { def: 1500, mag: 1500, elmRes: {'闇':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:213, noRandom: false, rank: 100, name: "オーディンレッグ", type: "足", baseName: "ブーツ", data: { spd: 3000, def: 1000 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:214, noRandom: false, rank: 100, name: "神速の具足", type: "足", baseName: "くつ", data: { spd: 5500, fastestAction: 10 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 110 ---
    { eid:221, noRandom: false, rank: 110, name: "英雄の剣", type: "武器", baseName: "剣", data: { atk: 1800 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:222, noRandom: false, rank: 110, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 2500, spd: -130, attack_Fear: 20 }, possibleOpts: ['atk', 'finDmg'] },
    { eid:223, noRandom: false, rank: 110, name: "飛燕のダガー", type: "武器", baseName: "短剣", data: { atk: 1100, spd: 600, attack_Poison: 25 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:224, noRandom: false, rank: 110, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 1700, mp: 400 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:225, noRandom: false, rank: 110, name: "英雄の槍", type: "武器", baseName: "槍", data: { atk: 2150, def: 100 } },
    { eid:226, noRandom: false, rank: 110, name: "英雄の弓", type: "武器", baseName: "弓", data: { atk: 2100, hit: -15, cri: 28 } },
    { eid:227, noRandom: false, rank: 110, name: "英雄の盾", type: "盾", baseName: "盾", data: { def: 1500, resists_Debuff: 20 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:228, noRandom: false, rank: 110, name: "英雄の腕輪", type: "盾", baseName: "腕輪", data: { def: 700, atk: 800 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:229, noRandom: false, rank: 110, name: "英雄の兜", type: "頭", baseName: "兜", data: { def: 1100, hp: 500 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:230, noRandom: false, rank: 110, name: "賢者の帽子", type: "頭", baseName: "帽子", data: { def: 800, mag: 1500 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:231, noRandom: false, rank: 110, name: "英雄の鎧", type: "体", baseName: "鎧", data: { def: 2700, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:232, noRandom: false, rank: 110, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 1800, mag: 1800 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:233, noRandom: false, rank: 110, name: "英雄のブーツ", type: "足", baseName: "ブーツ", data: { spd: 3800, def: 1200 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:234, noRandom: false, rank: 110, name: "俊足の靴", type: "足", baseName: "くつ", data: { spd: 7000 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 120 (勇者シリーズ) ---
    { eid:241, noRandom: false, rank: 120, name: "勇者のつるぎ", type: "武器", baseName: "剣", data: { atk: 2200, elmAtk: {'光':15} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:242, noRandom: false, rank: 120, name: "覇王の戦斧", type: "武器", baseName: "斧", data: { atk: 3100, spd: -160, attack_Fear: 25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:243, noRandom: false, rank: 120, name: "オリハルコンナイフ", type: "武器", baseName: "短剣", data: { atk: 1300, spd: 900, attack_InstantDeath: 3 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:244, noRandom: false, rank: 120, name: "アルテマスタッフ", type: "武器", baseName: "杖", data: { mag: 2100, mp: 600 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:245, noRandom: false, rank: 120, name: "勇者の槍", type: "武器", baseName: "槍", data: { atk: 2650, hit: 10 } },
    { eid:246, noRandom: false, rank: 120, name: "勇者の弓", type: "武器", baseName: "弓", data: { atk: 2600, hit: -10, cri: 30 } },
    { eid:247, noRandom: false, rank: 120, name: "女神の盾", type: "盾", baseName: "盾", data: { def: 1900, elmRes: {'全':15}, resists_Debuff: 25 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:248, noRandom: false, rank: 120, name: "勇気の紋章", type: "盾", baseName: "腕輪", data: { def: 900, atk: 1100, hp: 300 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:249, noRandom: false, rank: 120, name: "王者の冠", type: "頭", baseName: "兜", data: { def: 1400, resists_Fear: 25 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:250, noRandom: false, rank: 120, name: "司教のミトラ", type: "頭", baseName: "帽子", data: { def: 1000, mag: 1900, resists_SpellSeal: 25 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:251, noRandom: false, rank: 120, name: "王者のマント", type: "体", baseName: "鎧", data: { def: 3300, finRed: 15 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:252, noRandom: false, rank: 120, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 2200, mag: 2300, elmRes: {'光':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:253, noRandom: false, rank: 120, name: "勇者の具足", type: "足", baseName: "ブーツ", data: { spd: 4800, def: 1500, resists_Shock: 40 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:254, noRandom: false, rank: 120, name: "星降る靴", type: "足", baseName: "くつ", data: { spd: 9000, fastestAction: 15 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 130 (竜神シリーズ) ---
    { eid:261, noRandom: false, rank: 130, name: "竜神王の剣", type: "武器", baseName: "剣", data: { atk: 2600, elmAtk: {'火':20} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:262, noRandom: false, rank: 130, name: "ミョルニル", type: "武器", baseName: "斧", data: { atk: 3700, spd: -200, elmAtk: {'雷':20} }, possibleOpts: ['atk', 'finDmg', 'elmAtk'] },
    { eid:263, noRandom: false, rank: 130, name: "月下の小太刀", type: "武器", baseName: "短剣", data: { atk: 1600, spd: 1300, attack_Poison: 30 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:264, noRandom: false, rank: 130, name: "世界樹の杖", type: "武器", baseName: "杖", data: { mag: 2500, hpRegen: 3 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:265, noRandom: false, rank: 130, name: "竜神の槍", type: "武器", baseName: "槍", data: { atk: 3150, elmAtk: { '火': 20 } } },
    { eid:266, noRandom: false, rank: 130, name: "竜神の弓", type: "武器", baseName: "弓", data: { atk: 3100, hit: -18, cri: 32 } },
    { eid:267, noRandom: false, rank: 130, name: "竜神の盾", type: "盾", baseName: "盾", data: { def: 2400, elmRes: {'火':30} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:268, noRandom: false, rank: 130, name: "輝石のバングル", type: "盾", baseName: "腕輪", data: { def: 1100, mag: 600, resists_Debuff: 30 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:269, noRandom: false, rank: 130, name: "龍神の兜", type: "頭", baseName: "兜", data: { def: 1800, hp: 800, resists_Fear: 30 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:270, noRandom: false, rank: 130, name: "マジカルリボン", type: "頭", baseName: "帽子", data: { def: 1200, mag: 2400 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:271, noRandom: false, rank: 130, name: "竜神のよろい", type: "体", baseName: "鎧", data: { def: 4000, finRed: 15, elmRes: {'火':20} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:272, noRandom: false, rank: 130, name: "虹色のローブ", type: "体", baseName: "ローブ", data: { def: 2700, mag: 2800, elmRes: {'全':15} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:273, noRandom: false, rank: 130, name: "竜神の靴", type: "足", baseName: "ブーツ", data: { spd: 6500, def: 1800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:274, noRandom: false, rank: 130, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 12000, mpRegen: 3 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 140 ---
    { eid:281, noRandom: false, rank: 140, name: "ラグナロク", type: "武器", baseName: "剣", data: { atk: 3200, elmAtk: {'闇':25}, attack_Fear: 10 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:282, noRandom: false, rank: 140, name: "バハムートアクス", type: "武器", baseName: "斧", data: { atk: 4800, spd: -300, pierce: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:283, noRandom: false, rank: 140, name: "ソウルイーター", type: "武器", baseName: "短剣", data: { atk: 1900, spd: 1800, attack_InstantDeath: 5 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:284, noRandom: false, rank: 140, name: "虚空の杖", type: "武器", baseName: "杖", data: { mag: 3200, mp: 1000 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:285, noRandom: false, rank: 140, name: "ブリューナク", type: "武器", baseName: "槍", data: { atk: 4000, mag: 300 } },
    { eid:286, noRandom: false, rank: 140, name: "バハムートボウ", type: "武器", baseName: "弓", data: { atk: 3900, hit: -20, cri: 35, elmAtk: { '闇': 20 } } },
    { eid:287, noRandom: false, rank: 140, name: "イージスの盾", type: "盾", baseName: "盾", data: { def: 3200, finRed: 15, resists_Debuff: 40 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:288, noRandom: false, rank: 140, name: "星座の腕輪", type: "盾", baseName: "腕輪", data: { def: 1500, spd: 500 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:289, noRandom: false, rank: 140, name: "黄金のマスク", type: "頭", baseName: "兜", data: { def: 2200, hp: 1000, resists_InstantDeath: 20 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:290, noRandom: false, rank: 140, name: "星座のベレー", type: "頭", baseName: "帽子", data: { def: 1600, mag: 3200 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:291, noRandom: false, rank: 140, name: "天界の鎧", type: "体", baseName: "鎧", data: { def: 5000, finRed: 20 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:292, noRandom: false, rank: 140, name: "星辰の法衣", type: "体", baseName: "ローブ", data: { def: 3300, mag: 3500, elmRes: {'闇':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:293, noRandom: false, rank: 140, name: "戦神のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 8500, def: 2200 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:294, noRandom: false, rank: 140, name: "飛翔の靴", type: "足", baseName: "くつ", data: { spd: 16000, spdMod: 20 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 150 (メタルキングシリーズ) ---
    { eid:301, noRandom: false, rank: 150, name: "メタルキングの剣", type: "武器", baseName: "剣", data: { atk: 3800, spd: 50, attack_Fear: 15 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:302, noRandom: false, rank: 150, name: "メタルキングの大斧", type: "武器", baseName: "斧", data: { atk: 5500, spd: -400, attack_Fear: 30 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:303, noRandom: false, rank: 150, name: "メタルキングダガー", type: "武器", baseName: "短剣", data: { atk: 2200, spd: 2500, attack_Poison: 40, attack_InstantDeath: 8 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:304, noRandom: false, rank: 150, name: "メタルキングの杖", type: "武器", baseName: "杖", data: { mag: 4500, mp: 1200, magCrit: 15 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:305, noRandom: false, rank: 150, name: "メタルキングの槍", type: "武器", baseName: "槍", data: { atk: 4650, cri: 10 } },
    { eid:306, noRandom: false, rank: 150, name: "メタルキングの弓", type: "武器", baseName: "弓", data: { atk: 4500, hit: -10, cri: 40 } },
    { eid:307, noRandom: false, rank: 150, name: "メタルキングの盾", type: "盾", baseName: "盾", data: { def: 4200, elmRes: {'全':25}, resists_Debuff: 40 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:308, noRandom: false, rank: 150, name: "メタルキングの紋章", type: "盾", baseName: "腕輪", data: { def: 2000, atk: 1500, finDmg: 10 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:309, noRandom: false, rank: 150, name: "メタルキングヘルム", type: "頭", baseName: "兜", data: { def: 2800, resists_InstantDeath: 50, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear', 'resists_InstantDeath'] },
    { eid:310, noRandom: false, rank: 150, name: "メタルキングの大冠", type: "頭", baseName: "帽子", data: { def: 2100, mag: 4200, resists_SpellSeal: 50 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:311, noRandom: false, rank: 150, name: "メタルキングの鎧", type: "体", baseName: "鎧", data: { def: 6000, finRed: 20, resists_SkillSeal: 50, resists_SpellSeal: 50 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:312, noRandom: false, rank: 150, name: "メタルキングローブ", type: "体", baseName: "ローブ", data: { def: 4000, mag: 4800, resists_HealSeal: 50 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:313, noRandom: false, rank: 150, name: "メタルキングブーツ", type: "足", baseName: "ブーツ", data: { spd: 11000, def: 2800, resists_Shock: 70 }, possibleOpts: ['def', 'spd', 'finRed', 'elmRes'] },
    { eid:314, noRandom: false, rank: 150, name: "メタルキングのくつ", type: "足", baseName: "くつ", data: { spd: 20000, fastestAction: 25 }, possibleOpts: ['spd', 'finDmg', 'elmAtk'] },

    // --- Rank 160 ---
    { eid:321, noRandom: false, rank: 160, name: "終焉の剣", type: "武器", baseName: "剣", data: { atk: 4200, elmAtk: {'闇':30} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:322, noRandom: false, rank: 160, name: "ヴォルカノン", type: "武器", baseName: "斧", data: { atk: 6200, spd: -500, elmAtk: {'火':30} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:323, noRandom: false, rank: 160, name: "宵闇の牙", type: "武器", baseName: "短剣", data: { atk: 2500, spd: 3500, attack_InstantDeath: 12 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:324, noRandom: false, rank: 160, name: "コスモロッド", type: "武器", baseName: "杖", data: { mag: 5200, elmAtk: {'光':10,'闇':10} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:325, noRandom: false, rank: 160, name: "アビスランス", type: "武器", baseName: "槍", data: { atk: 5200, elmAtk: { '闇': 30 } } },
    { eid:326, noRandom: false, rank: 160, name: "フェイルノート", type: "武器", baseName: "弓", data: { atk: 5100, hit: -20, cri: 42, spd: 50 } },
    { eid:327, noRandom: false, rank: 160, name: "天界の盾", type: "盾", baseName: "盾", data: { def: 4800, elmRes: {'光':30}, finRed: 15 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:328, noRandom: false, rank: 160, name: "太陽のバングル", type: "盾", baseName: "腕輪", data: { def: 2400, atk: 1800, elmAtk: {'火':20} }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:329, noRandom: false, rank: 160, name: "星詠みの兜", type: "頭", baseName: "兜", data: { def: 3200, mp: 1000, resists_Fear: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:330, noRandom: false, rank: 160, name: "精霊の冠", type: "頭", baseName: "帽子", data: { def: 2500, mag: 5500, elmRes: {'全':10} }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:331, noRandom: false, rank: 160, name: "鳳凰の鎧", type: "体", baseName: "鎧", data: { def: 7000, hpRegen: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:332, noRandom: false, rank: 160, name: "聖者のガウン", type: "体", baseName: "ローブ", data: { def: 4800, mag: 5800, resists_Debuff: 30 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:333, noRandom: false, rank: 160, name: "幻影のブーツ", type: "足", baseName: "ブーツ", data: { spd: 15000, doubleAction: 10 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:334, noRandom: false, rank: 160, name: "水面の靴", type: "足", baseName: "くつ", data: { spd: 30000, spdMod: 30 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 170 ---
    { eid:341, noRandom: false, rank: 170, name: "創世の剣", type: "武器", baseName: "剣", data: { atk: 4800, hp: 1500 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { eid:342, noRandom: false, rank: 170, name: "ガルガリン", type: "武器", baseName: "斧", data: { atk: 7500, spd: -650, pierce: 25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:343, noRandom: false, rank: 170, name: "時空の針", type: "武器", baseName: "短剣", data: { atk: 2800, spd: 5000, fastestAction: 15 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:344, noRandom: false, rank: 170, name: "神託の杖", type: "武器", baseName: "杖", data: { mag: 6500, mp: 2000, magCrit: 20 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:345, noRandom: false, rank: 170, name: "創世の槍", type: "武器", baseName: "槍", data: { atk: 6150, def: 300 } },
    { eid:346, noRandom: false, rank: 170, name: "明星の弓", type: "武器", baseName: "弓", data: { atk: 6000, hit: -22, cri: 45, mag: 500 } },
    { eid:347, noRandom: false, rank: 170, name: "輪廻の盾", type: "盾", baseName: "盾", data: { def: 5500, finRed: 20, resists_Debuff: 45 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:348, noRandom: false, rank: 170, name: "月光のバングル", type: "盾", baseName: "腕輪", data: { def: 2800, mag: 1200, resists_Fear: 40 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:349, noRandom: false, rank: 170, name: "真実の仮面", type: "頭", baseName: "兜", data: { def: 3800, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:350, noRandom: false, rank: 170, name: "夢幻の帽子", type: "頭", baseName: "帽子", data: { def: 2900, mag: 6800, mp: 2500 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:351, noRandom: false, rank: 170, name: "星座のよろい", type: "体", baseName: "鎧", data: { def: 8500, finRed: 20, resists_SkillSeal: 45 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:352, noRandom: false, rank: 170, name: "女神のドレス", type: "体", baseName: "ローブ", data: { def: 5500, mag: 7500, resists_HealSeal: 45 }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:353, noRandom: false, rank: 170, name: "明星のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 18000, def: 3500 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:354, noRandom: false, rank: 170, name: "無音の靴", type: "足", baseName: "くつ", data: { spd: 45000, resists_Shock: 45 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 180 ---
    { eid:361, noRandom: false, rank: 180, name: "オメガブレイド", type: "武器", baseName: "剣", data: { atk: 5500, finDmg: 20, elmAtk: {'混沌':10} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:362, noRandom: false, rank: 180, name: "天変地異", type: "武器", baseName: "斧", data: { atk: 8500, spd: -800, attack_Fear: 40 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { eid:363, noRandom: false, rank: 180, name: "無音の暗殺刃", type: "武器", baseName: "短剣", data: { atk: 3200, spd: 7000, attack_InstantDeath: 15 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:364, noRandom: false, rank: 180, name: "始祖の魔杖", type: "武器", baseName: "杖", data: { mag: 8000, magCrit: 25, resists_SpellSeal: 45 }, possibleOpts: ['mag', 'finDmg'] },
    { eid:365, noRandom: false, rank: 180, name: "ロンゴミニアド", type: "武器", baseName: "槍", data: { atk: 7000, finDmg: 15 } },
    { eid:366, noRandom: false, rank: 180, name: "オメガボウ", type: "武器", baseName: "弓", data: { atk: 6900, hit: -25, cri: 48, elmAtk: { '混沌': 15 } } },
    { eid:367, noRandom: false, rank: 180, name: "ゼウスの盾", type: "盾", baseName: "盾", data: { def: 6500, elmRes: {'雷':50}, finRed: 20 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:368, noRandom: false, rank: 180, name: "混沌の腕輪", type: "盾", baseName: "腕輪", data: { def: 3200, atk: 2200, elmAtk: {'混沌':15} }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:369, noRandom: false, rank: 180, name: "神々の王冠", type: "頭", baseName: "兜", data: { def: 4500, hp: 3000, resists_Fear: 60 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:370, noRandom: false, rank: 180, name: "審判のカチュール", type: "頭", baseName: "帽子", data: { def: 3400, mag: 9000, resists_HealSeal: 60 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:371, noRandom: false, rank: 180, name: "神威の装束", type: "体", baseName: "鎧", data: { def: 11000, resists_Debuff: 40 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:372, noRandom: false, rank: 180, name: "虚無の法衣", type: "体", baseName: "ローブ", data: { def: 6500, mag: 10000, elmRes: {'混沌':20} }, possibleOpts: ['mp', 'mag', 'def'] },
    { eid:373, noRandom: false, rank: 180, name: "獅子のレガース", type: "足", baseName: "ブーツ", data: { spd: 25000, atk: 800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:374, noRandom: false, rank: 180, name: "光速のサンダル", type: "足", baseName: "くつ", data: { spd: 70000, fastestAction: 30 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 190 ---
    { eid:381, noRandom: false, rank: 190, name: "究極の聖剣", type: "武器", baseName: "剣", data: { atk: 6200, elmAtk: {'光':40}, finDmg: 20 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'], grantSkills: [421] },
    { eid:382, noRandom: false, rank: 190, name: "ゼウスのアクス", type: "武器", baseName: "斧", data: { atk: 10500, spd: -1000, elmAtk: {'雷':40} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:383, noRandom: false, rank: 190, name: "神殺しの匕首", type: "武器", baseName: "短剣", data: { atk: 3800, spd: 12000, pierce: 30, attack_InstantDeath: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { eid:384, noRandom: false, rank: 190, name: "アポカリプス", type: "武器", baseName: "杖", data: { mag: 12000, elmAtk: {'混沌':25} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:385, noRandom: false, rank: 190, name: "究極の魔槍", type: "武器", baseName: "槍", data: { atk: 8350, spd: 100 } },
    { eid:386, noRandom: false, rank: 190, name: "究極の神弓", type: "武器", baseName: "弓", data: { atk: 8200, hit: -25, cri: 50, doubleAction: 10 } },
    { eid:387, noRandom: false, rank: 190, name: "アカシックシールド", type: "盾", baseName: "盾", data: { def: 8500, finRed: 20, elmRes: {'混沌':30} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { eid:388, noRandom: false, rank: 190, name: "神話の紋章", type: "盾", baseName: "腕輪", data: { def: 4500, atk: 3500, spd: 1000 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { eid:389, noRandom: false, rank: 190, name: "虚空の兜", type: "頭", baseName: "兜", data: { def: 6000, hp: 5000, resists_InstantDeath: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { eid:390, noRandom: false, rank: 190, name: "明星の帽子", type: "頭", baseName: "帽子", data: { def: 4500, mag: 13000, hp: 2000 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { eid:391, noRandom: false, rank: 190, name: "至高の神鎧", type: "体", baseName: "鎧", data: { def: 16000, finRed: 30 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { eid:392, noRandom: false, rank: 190, name: "宇宙のケープ", type: "体", baseName: "ローブ", data: { def: 9500, mag: 15000, elmRes: {'全':25} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:393, noRandom: false, rank: 190, name: "神話のブーツ", type: "足", baseName: "ブーツ", data: { spd: 40000, def: 5000 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { eid:394, noRandom: false, rank: 190, name: "時空の靴", type: "足", baseName: "くつ", data: { spd: 110000, doubleAction: 15 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 200 (悠久・創世：マスタデータの頂点。ここから真・無限厳選の世界へ) ---
    { eid:401, noRandom: false, rank: 200, name: "悠久の真剣", type: "武器", baseName: "剣", data: { atk: 7500, spd: 200, attack_Fear: 20, elmAtk: {'混沌':30} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { eid:402, noRandom: false, rank: 200, name: "破滅の断罪斧", type: "武器", baseName: "斧", data: { atk: 12000, spd: -1500, pierce: 50, attack_Fear: 50 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { eid:403, noRandom: false, rank: 200, name: "幻想の終止符", type: "武器", baseName: "短剣", data: { atk: 4500, spd: 25000, attack_Poison: 50, attack_InstantDeath: 30 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { eid:404, noRandom: false, rank: 200, name: "全知の神杖", type: "武器", baseName: "杖", data: { mag: 8500, mp: 3000, magCrit: 30, resists_SpellSeal: 50 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { eid:405, noRandom: false, rank: 200, name: "悠久の聖槍", type: "武器", baseName: "槍", data: { atk: 10000, spd: 300, elmAtk: { '混沌': 30 } } },
    { eid:406, noRandom: false, rank: 200, name: "幻想の真弓", type: "武器", baseName: "弓", data: { atk: 9800, hit: -30, cri: 60, finDmg: 20 } },
    { eid:407, noRandom: false, rank: 200, name: "エタニティガード", type: "盾", baseName: "盾", data: { def: 12000, finRed: 30, elmRes: {'混沌':50}, resists_Debuff: 50 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { eid:408, noRandom: false, rank: 200, name: "創世の腕輪", type: "盾", baseName: "腕輪", data: { def: 6000, atk: 5000, finDmg: 20, resists_Debuff: 50 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { eid:409, noRandom: false, rank: 200, name: "無窮の冠", type: "頭", baseName: "兜", data: { def: 8500, hp: 10000, resists_InstantDeath: 50, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear', 'resists_InstantDeath'] },
    { eid:410, noRandom: false, rank: 200, name: "叡智の宝冠", type: "頭", baseName: "帽子", data: { def: 6500, mag: 11000, mp: 5000, resists_SpellSeal: 50, resists_HealSeal: 50 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { eid:411, noRandom: false, rank: 200, name: "創世の神鎧", type: "体", baseName: "鎧", data: { def: 22000, hp: 15000, mdef: 200, cri: 5, hit: 5, eva: 5, finRed: 35, resists_SkillSeal: 50 ,traits: [{ id: 15, level: 3 },{ id: 18, level: 2 }]}, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { eid:412, noRandom: false, rank: 200, name: "終焉の神衣", type: "体", baseName: "ローブ", data: { def: 14000, mag: 15000, mp: 8000, elmRes: {'混沌':50}, resists_Debuff: 50 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { eid:413, noRandom: false, rank: 200, name: "終焉の足跡", type: "足", baseName: "ブーツ", data: { spd: 45000, def: 8000, doubleAction: 20, resists_Shock: 50 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { eid:414, noRandom: false, rank: 200, name: "悠久の歩み", type: "足", baseName: "くつ", data: { spd: 180000, fastestAction: 40, resists_Shock: 50 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] }
];

window.EQUIP_MASTER = EQUIP_MASTER;