/* ==========================================================================
   equips.js - 装備品マスタデータベース (ハクスラ厳選重視・デフレ調整版)
   全252アイテム：12カテゴリ × 21段階 (1, 10, 20...200)
   ========================================================================== */

const EQUIP_MASTER = [
    // --- Rank 1 ---
    { rank: 1, name: "ひのきのぼう", type: "武器", baseName: "剣", data: { atk: 10 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 1, name: "石のオノ", type: "武器", baseName: "斧", data: { atk: 15, spd: -5 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 1, name: "銅のナイフ", type: "武器", baseName: "短剣", data: { atk: 5, spd: 5, mag: 5 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 1, name: "樫の杖", type: "武器", baseName: "杖", data: { mag: 12 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 1, name: "おなべのふた", type: "盾", baseName: "盾", data: { def: 5 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 1, name: "銅のバングル", type: "盾", baseName: "腕輪", data: { def: 2, atk: 3 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 1, name: "皮のぼうし", type: "頭", baseName: "兜", data: { def: 3, hp: 5 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { rank: 1, name: "ターバン", type: "頭", baseName: "帽子", data: { def: 2, mag: 3 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 1, name: "布の服", type: "体", baseName: "鎧", data: { def: 8 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 1, name: "旅人の服", type: "体", baseName: "ローブ", data: { def: 5, mag: 5 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { rank: 1, name: "皮のくつ", type: "足", baseName: "ブーツ", data: { spd: 5, def: 2 }, possibleOpts: ['def', 'spd', 'finRed', 'elmRes'] },
    { rank: 1, name: "わらじ", type: "足", baseName: "くつ", data: { spd: 8 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 10 ---
    { rank: 10, name: "銅のつるぎ", type: "武器", baseName: "剣", data: { atk: 45 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 10, name: "鉄のオノ", type: "武器", baseName: "斧", data: { atk: 65, spd: -10 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 10, name: "鉄のナイフ", type: "武器", baseName: "短剣", data: { atk: 25, spd: 15, mag: 15 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 10, name: "魔導士の杖", type: "武器", baseName: "杖", data: { mag: 40 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 10, name: "皮のたて", type: "盾", baseName: "盾", data: { def: 25 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 10, name: "鉄の腕輪", type: "盾", baseName: "腕輪", data: { def: 10, atk: 15 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 10, name: "木のヘルメット", type: "頭", baseName: "兜", data: { def: 18, hp: 15 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 10, name: "羽根ぼうし", type: "頭", baseName: "帽子", data: { def: 12, mag: 15 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 10, name: "皮のよろい", type: "体", baseName: "鎧", data: { def: 40 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 10, name: "稽古着", type: "体", baseName: "ローブ", data: { def: 30, mag: 25 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 10, name: "鉄のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 25, def: 10 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 10, name: "旅人のくつ", type: "足", baseName: "くつ", data: { spd: 40 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 20 ---
    { rank: 20, name: "鉄のつるぎ", type: "武器", baseName: "剣", data: { atk: 85 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 20, name: "バトルアックス", type: "武器", baseName: "斧", data: { atk: 120, spd: -15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 20, name: "どくがのナイフ", type: "武器", baseName: "短剣", data: { atk: 50, spd: 30, attack_Poison: 10 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 20, name: "ルーンスタッフ", type: "武器", baseName: "杖", data: { mag: 90, mp: 30 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 20, name: "鉄のたて", type: "盾", baseName: "盾", data: { def: 55 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 20, name: "銀のバングル", type: "盾", baseName: "腕輪", data: { def: 25, atk: 35 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 20, name: "鉄かぶと", type: "頭", baseName: "兜", data: { def: 45, hp: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 20, name: "魔道士の帽子", type: "頭", baseName: "帽子", data: { def: 30, mag: 40 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 20, name: "鎖かたびら", type: "体", baseName: "鎧", data: { def: 90, finRed: 3 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 20, name: "絹のローブ", type: "体", baseName: "ローブ", data: { def: 60, mag: 55 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 20, name: "鋼のブーツ", type: "足", baseName: "ブーツ", data: { spd: 70, def: 30 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 20, name: "ラバーソール", type: "足", baseName: "くつ", data: { spd: 110 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 30 ---
    { rank: 30, name: "はがねのつるぎ", type: "武器", baseName: "剣", data: { atk: 150 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 30, name: "鋼鉄のギロチン", type: "武器", baseName: "斧", data: { atk: 210, spd: -25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 30, name: "アサシンダガー", type: "武器", baseName: "短剣", data: { atk: 90, spd: 50, attack_InstantDeath: 2 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 30, name: "まどろみの杖", type: "武器", baseName: "杖", data: { mag: 150 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 30, name: "はがねのたて", type: "盾", baseName: "盾", data: { def: 110 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 30, name: "鋼鉄の腕輪", type: "盾", baseName: "腕輪", data: { def: 45, atk: 70 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 30, name: "はがねのかぶと", type: "頭", baseName: "兜", data: { def: 85, hp: 80 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 30, name: "銀の髪飾り", type: "頭", baseName: "帽子", data: { def: 55, mag: 75 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 30, name: "鉄のよろい", type: "体", baseName: "鎧", data: { def: 180, finRed: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 30, name: "魔道士の服", type: "体", baseName: "ローブ", data: { def: 110, mag: 110 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 30, name: "銀のブーツ", type: "足", baseName: "ブーツ", data: { spd: 140, def: 50 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 30, name: "俊足のサンダル", type: "足", baseName: "くつ", data: { spd: 220 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 40 ---
    { rank: 40, name: "破邪の剣", type: "武器", baseName: "剣", data: { atk: 240, elmAtk: {'光':5} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 40, name: "大地のオノ", type: "武器", baseName: "斧", data: { atk: 330, spd: -35, elmAtk: {'火':5} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 40, name: "ミスリルナイフ", type: "武器", baseName: "短剣", data: { atk: 150, spd: 80, mag: 60 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 40, name: "マジカルスタッフ", type: "武器", baseName: "杖", data: { mag: 250, mp: 50 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 40, name: "魔法の盾", type: "盾", baseName: "盾", data: { def: 180, elmRes: {'火':5, '水':5} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 40, name: "黄金のブレスレット", type: "盾", baseName: "腕輪", data: { def: 75, atk: 120 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 40, name: "知力の兜", type: "頭", baseName: "兜", data: { def: 130, mag: 25 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { rank: 40, name: "黄金のティアラ", type: "頭", baseName: "帽子", data: { def: 90, mag: 140 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 40, name: "はがねのよろい", type: "体", baseName: "鎧", data: { def: 300, finRed: 8 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 40, name: "魔法の法衣", type: "体", baseName: "ローブ", data: { def: 180, mag: 180, elmRes: {'光':5} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { rank: 40, name: "黄金のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 200, def: 90 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { rank: 40, name: "魔法のサンダル", type: "足", baseName: "くつ", data: { spd: 320, mag: 25 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 50 ---
    { rank: 50, name: "ドラゴンキラー", type: "武器", baseName: "剣", data: { atk: 400 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 50, name: "ま神のオノ", type: "武器", baseName: "斧", data: { atk: 550, spd: -50 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 50, name: "グラディウス", type: "武器", baseName: "短剣", data: { atk: 220, spd: 120, mag: 100 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 50, name: "賢者の杖", type: "武器", baseName: "杖", data: { mag: 420, mp: 100 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 50, name: "ドラゴンシールド", type: "盾", baseName: "盾", data: { def: 320, elmRes: {'火':10} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 50, name: "竜のうろこ", type: "盾", baseName: "腕輪", data: { def: 140, atk: 180 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 50, name: "ミスリルヘルム", type: "頭", baseName: "兜", data: { def: 240, hp: 150 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { rank: 50, name: "司祭の帽子", type: "頭", baseName: "帽子", data: { def: 160, mag: 220 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 50, name: "魔法の鎧", type: "体", baseName: "鎧", data: { def: 500, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 50, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 320, mag: 300, elmRes: {'全':5} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { rank: 50, name: "ミスリルブーツ", type: "足", baseName: "ブーツ", data: { spd: 400, def: 180 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { rank: 50, name: "フェザーシューズ", type: "足", baseName: "くつ", data: { spd: 650, spdMod: 5 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 60 ---
    { rank: 60, name: "プラチナソード", type: "武器", baseName: "剣", data: { atk: 600 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 60, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 850, spd: -80 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 60, name: "ソウルブレイカー", type: "武器", baseName: "短剣", data: { atk: 350, spd: 200, mag: 150 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 60, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 650, mp: 150 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 60, name: "プラチナシールド", type: "盾", baseName: "盾", data: { def: 520, resists_Debuff: 5 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 60, name: "ミスリルバングル", type: "盾", baseName: "腕輪", data: { def: 220, atk: 280 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 60, name: "プラチナヘッド", type: "頭", baseName: "兜", data: { def: 400, hp: 250 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 60, name: "賢者のターバン", type: "頭", baseName: "帽子", data: { def: 280, mag: 380 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 60, name: "ドラゴンメイル", type: "体", baseName: "鎧", data: { def: 750, elmRes: {'火':10} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 60, name: "ミスリルケープ", type: "体", baseName: "ローブ", data: { def: 480, mag: 450 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 60, name: "竜のブーツ", type: "足", baseName: "ブーツ", data: { spd: 750, def: 300 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 60, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 1200, mp: 80 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 70 ---
    { rank: 70, name: "隼の剣", type: "武器", baseName: "剣", data: { atk: 850, doubleAction: 10 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 70, name: "破壊の鉄球", type: "武器", baseName: "斧", data: { atk: 1250, spd: -120 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 70, name: "フェニックスダガー", type: "武器", baseName: "短剣", data: { atk: 500, spd: 350, mag: 250, elmAtk: {'火':10} }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 70, name: "精霊の杖", type: "武器", baseName: "杖", data: { mag: 900, elmAtk: {'全':5} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 70, name: "鏡の盾", type: "盾", baseName: "盾", data: { def: 750, elmRes: {'光':10} }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 70, name: "守りのルーン", type: "盾", baseName: "腕輪", data: { def: 350, resists_Debuff: 10 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 70, name: "隼の兜", type: "頭", baseName: "兜", data: { def: 550, spd: 30 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { rank: 70, name: "精霊の帽子", type: "頭", baseName: "帽子", data: { def: 420, mag: 550 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 70, name: "刃のよろい", type: "体", baseName: "鎧", data: { def: 1000, pierce: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 70, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 680, mag: 700, elmRes: {'光':10} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { rank: 70, name: "天使のブーツ", type: "足", baseName: "ブーツ", data: { spd: 1100, def: 500 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { rank: 70, name: "韋駄天のくつ", type: "足", baseName: "くつ", data: { spd: 1800, fastestAction: 5 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },

    // --- Rank 80 (はぐれメタルシリーズ) ---
    { rank: 80, name: "はぐれメタルの剣", type: "武器", baseName: "剣", data: { atk: 1200, spd: 50 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 80, name: "はぐれメタルのオノ", type: "武器", baseName: "斧", data: { atk: 1800, spd: -180, attack_Fear: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 80, name: "はぐれメタルの短剣", type: "武器", baseName: "短剣", data: { atk: 800, spd: 600, attack_Poison: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 80, name: "はぐれメタルの杖", type: "武器", baseName: "杖", data: { mag: 1200, mp: 300 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 80, name: "はぐれメタルの盾", type: "盾", baseName: "盾", data: { def: 1000, elmRes: {'火':10,'水':10,'風':10,'雷':10} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 80, name: "はぐれメタルの腕輪", type: "盾", baseName: "腕輪", data: { def: 500, atk: 500 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 80, name: "はぐれメタルヘルム", type: "頭", baseName: "兜", data: { def: 750, mp: 300, resists_Fear: 10 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 80, name: "はぐれメタルの帽子", type: "頭", baseName: "帽子", data: { def: 580, mag: 850 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 80, name: "はぐれメタルの鎧", type: "体", baseName: "鎧", data: { def: 1500, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 80, name: "はぐれメタルのローブ", type: "体", baseName: "ローブ", data: { def: 1100, mag: 1000 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 80, name: "はぐれメタルのブーツ", type: "足", baseName: "ブーツ", data: { spd: 2200, def: 800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 80, name: "はぐれメタルのくつ", type: "足", baseName: "くつ", data: { spd: 3500 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 90 ---
    { rank: 90, name: "真魔剛竜剣", type: "武器", baseName: "剣", data: { atk: 1400, elmAtk: {'火':10} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 90, name: "ギガントアックス", type: "武器", baseName: "斧", data: { atk: 2100, spd: -220, attack_Fear: 20 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 90, name: "神速の暗器", type: "武器", baseName: "短剣", data: { atk: 950, spd: 800, mag: 300, attack_Poison: 25 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 90, name: "ドラゴンの杖", type: "武器", baseName: "杖", data: { mag: 1500, elmAtk: {'火':15} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 90, name: "覇者の盾", type: "盾", baseName: "盾", data: { def: 1300, resists_Debuff: 15 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 90, name: "覇者の紋章", type: "盾", baseName: "腕輪", data: { def: 650, atk: 750 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 90, name: "天獄の兜", type: "頭", baseName: "兜", data: { def: 1000, hp: 400 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear'] },
    { rank: 90, name: "星天のティアラ", type: "頭", baseName: "帽子", data: { def: 720, mag: 1100, resists_SpellSeal: 10 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 90, name: "覇王の鎧", type: "体", baseName: "鎧", data: { def: 1800, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 90, name: "プリンセスローブ", type: "体", baseName: "ローブ", data: { def: 1200, mag: 1200, elmRes: {'光':15,'闇':15} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk', 'elmRes'] },
    { rank: 90, name: "冥府のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 2800, def: 1000, elmRes: {'闇':15} }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { rank: 90, name: "ペガサスの靴", type: "足", baseName: "くつ", data: { spd: 4500, fastestAction: 8 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] },
	
	// --- Rank 100 (伝説級の入り口) ---
    { rank: 100, name: "王者の剣", type: "武器", baseName: "剣", data: { atk: 1500, elmAtk: {'光':10}, attack_Fear: 5 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 100, name: "天罰の巨斧", type: "武器", baseName: "斧", data: { atk: 2100, spd: -100, elmAtk: {'雷':10}, attack_Fear: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 100, name: "トリトンダガー", type: "武器", baseName: "短剣", data: { atk: 900, spd: 400, attack_Poison: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 100, name: "神鳥の杖", type: "武器", baseName: "杖", data: { mag: 1400, mp: 300, magCrit: 5 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 100, name: "真・地獄の盾", type: "盾", baseName: "盾", data: { def: 1200, elmRes: {'闇':20}, resists_InstantDeath: 10 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 100, name: "神の腕輪", type: "盾", baseName: "腕輪", data: { def: 550, atk: 600, finDmg: 5 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 100, name: "天帝の冠", type: "頭", baseName: "兜", data: { def: 900, hp: 400, resists_Fear: 20 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 100, name: "神の知恵袋", type: "頭", baseName: "帽子", data: { def: 650, mag: 1200, resists_SpellSeal: 20 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 100, name: "天のゼウスメイル", type: "体", baseName: "鎧", data: { def: 2200, finRed: 10, elmRes: {'雷':20} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 100, name: "常世の法衣", type: "体", baseName: "ローブ", data: { def: 1500, mag: 1500, elmRes: {'闇':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 100, name: "オーディンレッグ", type: "足", baseName: "ブーツ", data: { spd: 3000, def: 1000 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 100, name: "神速の具足", type: "足", baseName: "くつ", data: { spd: 5500, fastestAction: 10 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 110 ---
    { rank: 110, name: "英雄の剣", type: "武器", baseName: "剣", data: { atk: 1800 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 110, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 2500, spd: -130, attack_Fear: 20 }, possibleOpts: ['atk', 'finDmg'] },
    { rank: 110, name: "飛燕のダガー", type: "武器", baseName: "短剣", data: { atk: 1100, spd: 600, attack_Poison: 25 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 110, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 1700, mp: 400 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 110, name: "英雄の盾", type: "盾", baseName: "盾", data: { def: 1500, resists_Debuff: 20 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 110, name: "英雄の腕輪", type: "盾", baseName: "腕輪", data: { def: 700, atk: 800 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 110, name: "英雄の兜", type: "頭", baseName: "兜", data: { def: 1100, hp: 500 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 110, name: "賢者の帽子", type: "頭", baseName: "帽子", data: { def: 800, mag: 1500 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 110, name: "英雄の鎧", type: "体", baseName: "鎧", data: { def: 2700, finRed: 10 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 110, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 1800, mag: 1800 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 110, name: "英雄のブーツ", type: "足", baseName: "ブーツ", data: { spd: 3800, def: 1200 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 110, name: "俊足の靴", type: "足", baseName: "くつ", data: { spd: 7000 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 120 (勇者シリーズ) ---
    { rank: 120, name: "勇者のつるぎ", type: "武器", baseName: "剣", data: { atk: 2200, elmAtk: {'光':15} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 120, name: "覇王の戦斧", type: "武器", baseName: "斧", data: { atk: 3100, spd: -160, attack_Fear: 25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 120, name: "オリハルコンナイフ", type: "武器", baseName: "短剣", data: { atk: 1300, spd: 900, attack_InstantDeath: 3 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 120, name: "アルテマスタッフ", type: "武器", baseName: "杖", data: { mag: 2100, mp: 600 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 120, name: "女神の盾", type: "盾", baseName: "盾", data: { def: 1900, elmRes: {'全':15}, resists_Debuff: 25 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 120, name: "勇気の紋章", type: "盾", baseName: "腕輪", data: { def: 900, atk: 1100, hp: 300 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 120, name: "王者の冠", type: "頭", baseName: "兜", data: { def: 1400, resists_Fear: 25 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 120, name: "司教のミトラ", type: "頭", baseName: "帽子", data: { def: 1000, mag: 1900, resists_SpellSeal: 25 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 120, name: "王者のマント", type: "体", baseName: "鎧", data: { def: 3300, finRed: 15 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 120, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 2200, mag: 2300, elmRes: {'光':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 120, name: "勇者の具足", type: "足", baseName: "ブーツ", data: { spd: 4800, def: 1500, resists_Shock: 40 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 120, name: "星降る靴", type: "足", baseName: "くつ", data: { spd: 9000, fastestAction: 15 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 130 (竜神シリーズ) ---
    { rank: 130, name: "竜神王の剣", type: "武器", baseName: "剣", data: { atk: 2600, elmAtk: {'火':20} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 130, name: "ミョルニル", type: "武器", baseName: "斧", data: { atk: 3700, spd: -200, elmAtk: {'雷':20} }, possibleOpts: ['atk', 'finDmg', 'elmAtk'] },
    { rank: 130, name: "月下の小太刀", type: "武器", baseName: "短剣", data: { atk: 1600, spd: 1300, attack_Poison: 30 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 130, name: "世界樹の杖", type: "武器", baseName: "杖", data: { mag: 2500, hpRegen: 3 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 130, name: "竜神の盾", type: "盾", baseName: "盾", data: { def: 2400, elmRes: {'火':30} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 130, name: "輝石のバングル", type: "盾", baseName: "腕輪", data: { def: 1100, mag: 600, resists_Debuff: 30 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 130, name: "龍神の兜", type: "頭", baseName: "兜", data: { def: 1800, hp: 800, resists_Fear: 30 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 130, name: "マジカルリボン", type: "頭", baseName: "帽子", data: { def: 1200, mag: 2400 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 130, name: "竜神のよろい", type: "体", baseName: "鎧", data: { def: 4000, finRed: 15, elmRes: {'火':20} }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 130, name: "虹色のローブ", type: "体", baseName: "ローブ", data: { def: 2700, mag: 2800, elmRes: {'全':15} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 130, name: "竜神の靴", type: "足", baseName: "ブーツ", data: { spd: 6500, def: 1800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 130, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 12000, mpRegen: 3 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 140 ---
    { rank: 140, name: "ラグナロク", type: "武器", baseName: "剣", data: { atk: 3200, elmAtk: {'闇':25}, attack_Fear: 10 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 140, name: "バハムートアクス", type: "武器", baseName: "斧", data: { atk: 4800, spd: -300, pierce: 15 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 140, name: "ソウルイーター", type: "武器", baseName: "短剣", data: { atk: 1900, spd: 1800, attack_InstantDeath: 5 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 140, name: "虚空の杖", type: "武器", baseName: "杖", data: { mag: 3200, mp: 1000 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 140, name: "イージスの盾", type: "盾", baseName: "盾", data: { def: 3200, finRed: 15, resists_Debuff: 40 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 140, name: "星座の腕輪", type: "盾", baseName: "腕輪", data: { def: 1500, spd: 500 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 140, name: "黄金のマスク", type: "頭", baseName: "兜", data: { def: 2200, hp: 1000, resists_InstantDeath: 20 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 140, name: "星座のベレー", type: "頭", baseName: "帽子", data: { def: 1600, mag: 3200 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 140, name: "天界の鎧", type: "体", baseName: "鎧", data: { def: 5000, finRed: 20 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 140, name: "星辰の法衣", type: "体", baseName: "ローブ", data: { def: 3300, mag: 3500, elmRes: {'闇':20} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 140, name: "戦神のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 8500, def: 2200 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 140, name: "飛翔の靴", type: "足", baseName: "くつ", data: { spd: 16000, spdMod: 20 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 150 (メタルキングシリーズ) ---
    { rank: 150, name: "メタルキングの剣", type: "武器", baseName: "剣", data: { atk: 3800, spd: 50, attack_Fear: 15 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 150, name: "メタルキングの大斧", type: "武器", baseName: "斧", data: { atk: 5500, spd: -400, attack_Fear: 30 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 150, name: "メタルキングダガー", type: "武器", baseName: "短剣", data: { atk: 2200, spd: 2500, attack_Poison: 40, attack_InstantDeath: 8 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 150, name: "メタルキングの杖", type: "武器", baseName: "杖", data: { mag: 4500, mp: 1200, magCrit: 15 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 150, name: "メタルキングの盾", type: "盾", baseName: "盾", data: { def: 4200, elmRes: {'全':25}, resists_Debuff: 40 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 150, name: "メタルキングの紋章", type: "盾", baseName: "腕輪", data: { def: 2000, atk: 1500, finDmg: 10 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 150, name: "メタルキングヘルム", type: "頭", baseName: "兜", data: { def: 2800, resists_InstantDeath: 50, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear', 'resists_InstantDeath'] },
    { rank: 150, name: "メタルキングの大冠", type: "頭", baseName: "帽子", data: { def: 2100, mag: 4200, resists_SpellSeal: 50 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 150, name: "メタルキングの鎧", type: "体", baseName: "鎧", data: { def: 6000, finRed: 20, resists_SkillSeal: 50, resists_SpellSeal: 50 }, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 150, name: "メタルキングローブ", type: "体", baseName: "ローブ", data: { def: 4000, mag: 4800, resists_HealSeal: 50 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 150, name: "メタルキングブーツ", type: "足", baseName: "ブーツ", data: { spd: 11000, def: 2800, resists_Shock: 70 }, possibleOpts: ['def', 'spd', 'finRed', 'elmRes'] },
    { rank: 150, name: "メタルキングのくつ", type: "足", baseName: "くつ", data: { spd: 20000, fastestAction: 25 }, possibleOpts: ['spd', 'finDmg', 'elmAtk'] },

    // --- Rank 160 ---
    { rank: 160, name: "終焉の剣", type: "武器", baseName: "剣", data: { atk: 4200, elmAtk: {'闇':30} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 160, name: "ヴォルカノン", type: "武器", baseName: "斧", data: { atk: 6200, spd: -500, elmAtk: {'火':30} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 160, name: "宵闇の牙", type: "武器", baseName: "短剣", data: { atk: 2500, spd: 3500, attack_InstantDeath: 12 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 160, name: "コスモロッド", type: "武器", baseName: "杖", data: { mag: 5200, elmAtk: {'光':10,'闇':10} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 160, name: "天界の盾", type: "盾", baseName: "盾", data: { def: 4800, elmRes: {'光':30}, finRed: 15 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 160, name: "太陽のバングル", type: "盾", baseName: "腕輪", data: { def: 2400, atk: 1800, elmAtk: {'火':20} }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 160, name: "星詠みの兜", type: "頭", baseName: "兜", data: { def: 3200, mp: 1000, resists_Fear: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 160, name: "精霊の冠", type: "頭", baseName: "帽子", data: { def: 2500, mag: 5500, elmRes: {'全':10} }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 160, name: "鳳凰の鎧", type: "体", baseName: "鎧", data: { def: 7000, hpRegen: 5 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 160, name: "聖者のガウン", type: "体", baseName: "ローブ", data: { def: 4800, mag: 5800, resists_Debuff: 30 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 160, name: "幻影のブーツ", type: "足", baseName: "ブーツ", data: { spd: 15000, doubleAction: 10 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 160, name: "水面の靴", type: "足", baseName: "くつ", data: { spd: 30000, spdMod: 30 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 170 ---
    { rank: 170, name: "創世の剣", type: "武器", baseName: "剣", data: { atk: 4800, hp: 1500 }, possibleOpts: ['atk', 'mag', 'finDmg'] },
    { rank: 170, name: "ガルガリン", type: "武器", baseName: "斧", data: { atk: 7500, spd: -650, pierce: 25 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 170, name: "時空の針", type: "武器", baseName: "短剣", data: { atk: 2800, spd: 5000, fastestAction: 15 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 170, name: "神託の杖", type: "武器", baseName: "杖", data: { mag: 6500, mp: 2000, magCrit: 20 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 170, name: "輪廻の盾", type: "盾", baseName: "盾", data: { def: 5500, finRed: 20, resists_Debuff: 45 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 170, name: "月光のバングル", type: "盾", baseName: "腕輪", data: { def: 2800, mag: 1200, resists_Fear: 40 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 170, name: "真実の仮面", type: "頭", baseName: "兜", data: { def: 3800, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 170, name: "夢幻の帽子", type: "頭", baseName: "帽子", data: { def: 2900, mag: 6800, mp: 2500 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 170, name: "星座のよろい", type: "体", baseName: "鎧", data: { def: 8500, finRed: 20, resists_SkillSeal: 45 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 170, name: "女神のドレス", type: "体", baseName: "ローブ", data: { def: 5500, mag: 7500, resists_HealSeal: 45 }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 170, name: "明星のグリーヴ", type: "足", baseName: "ブーツ", data: { spd: 18000, def: 3500 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 170, name: "無音の靴", type: "足", baseName: "くつ", data: { spd: 45000, resists_Shock: 45 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 180 ---
    { rank: 180, name: "オメガブレイド", type: "武器", baseName: "剣", data: { atk: 5500, finDmg: 20, elmAtk: {'混沌':10} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 180, name: "天変地異", type: "武器", baseName: "斧", data: { atk: 8500, spd: -800, attack_Fear: 40 }, possibleOpts: ['atk', 'finDmg', 'attack_Fear'] },
    { rank: 180, name: "無音の暗殺刃", type: "武器", baseName: "短剣", data: { atk: 3200, spd: 7000, attack_InstantDeath: 15 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 180, name: "始祖の魔杖", type: "武器", baseName: "杖", data: { mag: 8000, magCrit: 25, resists_SpellSeal: 45 }, possibleOpts: ['mag', 'finDmg'] },
    { rank: 180, name: "ゼウスの盾", type: "盾", baseName: "盾", data: { def: 6500, elmRes: {'雷':50}, finRed: 20 }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 180, name: "混沌の腕輪", type: "盾", baseName: "腕輪", data: { def: 3200, atk: 2200, elmAtk: {'混沌':15} }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 180, name: "神々の王冠", type: "頭", baseName: "兜", data: { def: 4500, hp: 3000, resists_Fear: 60 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 180, name: "審判のカチュール", type: "頭", baseName: "帽子", data: { def: 3400, mag: 9000, resists_HealSeal: 60 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 180, name: "神威の装束", type: "体", baseName: "鎧", data: { def: 11000, resists_Debuff: 40 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 180, name: "虚無の法衣", type: "体", baseName: "ローブ", data: { def: 6500, mag: 10000, elmRes: {'混沌':20} }, possibleOpts: ['mp', 'mag', 'def'] },
    { rank: 180, name: "獅子のレガース", type: "足", baseName: "ブーツ", data: { spd: 25000, atk: 800 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 180, name: "光速のサンダル", type: "足", baseName: "くつ", data: { spd: 70000, fastestAction: 30 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 190 ---
    { rank: 190, name: "究極の聖剣", type: "武器", baseName: "剣", data: { atk: 6200, elmAtk: {'光':40}, finDmg: 20 }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 190, name: "ゼウスのアクス", type: "武器", baseName: "斧", data: { atk: 10500, spd: -1000, elmAtk: {'雷':40} }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 190, name: "神殺しの匕首", type: "武器", baseName: "短剣", data: { atk: 3800, spd: 12000, pierce: 30, attack_InstantDeath: 20 }, possibleOpts: ['mag', 'finDmg', 'attack_Poison'] },
    { rank: 190, name: "アポカリプス", type: "武器", baseName: "杖", data: { mag: 12000, elmAtk: {'混沌':25} }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 190, name: "アカシックシールド", type: "盾", baseName: "盾", data: { def: 8500, finRed: 20, elmRes: {'混沌':30} }, possibleOpts: ['def', 'finRed', 'elmRes'] },
    { rank: 190, name: "神話の紋章", type: "盾", baseName: "腕輪", data: { def: 4500, atk: 3500, spd: 1000 }, possibleOpts: ['atk', 'def', 'finDmg'] },
    { rank: 190, name: "虚空の兜", type: "頭", baseName: "兜", data: { def: 6000, hp: 5000, resists_InstantDeath: 40 }, possibleOpts: ['hp', 'mp', 'def'] },
    { rank: 190, name: "明星の帽子", type: "頭", baseName: "帽子", data: { def: 4500, mag: 13000, hp: 2000 }, possibleOpts: ['hp', 'mp', 'mag'] },
    { rank: 190, name: "至高の神鎧", type: "体", baseName: "鎧", data: { def: 16000, finRed: 30 }, possibleOpts: ['hp', 'mp', 'def', 'finRed'] },
    { rank: 190, name: "宇宙のケープ", type: "体", baseName: "ローブ", data: { def: 9500, mag: 15000, elmRes: {'全':25} }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 190, name: "神話のブーツ", type: "足", baseName: "ブーツ", data: { spd: 40000, def: 5000 }, possibleOpts: ['def', 'spd', 'finRed'] },
    { rank: 190, name: "時空の靴", type: "足", baseName: "くつ", data: { spd: 110000, doubleAction: 15 }, possibleOpts: ['spd', 'finDmg'] },

    // --- Rank 200 (悠久・創世：マスタデータの頂点。ここから真・無限厳選の世界へ) ---
    { rank: 200, name: "悠久の真剣", type: "武器", baseName: "剣", data: { atk: 7500, spd: 200, attack_Fear: 20, elmAtk: {'混沌':30} }, possibleOpts: ['atk', 'mag', 'finDmg', 'elmAtk'] },
    { rank: 200, name: "破滅の断罪斧", type: "武器", baseName: "斧", data: { atk: 12000, spd: -1500, pierce: 50, attack_Fear: 50 }, possibleOpts: ['atk', 'finDmg', 'elmAtk', 'attack_Fear'] },
    { rank: 200, name: "幻想の終止符", type: "武器", baseName: "短剣", data: { atk: 4500, spd: 25000, attack_Poison: 50, attack_InstantDeath: 30 }, possibleOpts: ['mag', 'finDmg', 'elmAtk', 'attack_Poison'] },
    { rank: 200, name: "全知の神杖", type: "武器", baseName: "杖", data: { mag: 8500, mp: 3000, magCrit: 30, resists_SpellSeal: 50 }, possibleOpts: ['mag', 'finDmg', 'elmAtk'] },
    { rank: 200, name: "エタニティガード", type: "盾", baseName: "盾", data: { def: 12000, finRed: 30, elmRes: {'混沌':50}, resists_Debuff: 50 }, possibleOpts: ['def', 'finRed', 'elmRes', 'resists_Debuff'] },
    { rank: 200, name: "創世の腕輪", type: "盾", baseName: "腕輪", data: { def: 6000, atk: 5000, finDmg: 20, resists_Debuff: 50 }, possibleOpts: ['atk', 'def', 'finDmg', 'elmAtk'] },
    { rank: 200, name: "無窮の冠", type: "頭", baseName: "兜", data: { def: 8500, hp: 10000, resists_InstantDeath: 50, resists_Fear: 50 }, possibleOpts: ['hp', 'mp', 'def', 'resists_Fear', 'resists_InstantDeath'] },
    { rank: 200, name: "叡智の宝冠", type: "頭", baseName: "帽子", data: { def: 6500, mag: 11000, mp: 5000, resists_SpellSeal: 50, resists_HealSeal: 50 }, possibleOpts: ['hp', 'mp', 'mag', 'elmRes'] },
    { rank: 200, name: "創世の神鎧", type: "体", baseName: "鎧", data: { def: 22000, hp: 15000, mdef: 200, cri: 5, hit: 5, eva: 5, finRed: 35, resists_SkillSeal: 50 ,traits: [{ id: 15, level: 3 },{ id: 18, level: 2 }]}, possibleOpts: ['hp', 'mp', 'def', 'finRed', 'elmRes'] },
    { rank: 200, name: "終焉の神衣", type: "体", baseName: "ローブ", data: { def: 14000, mag: 15000, mp: 8000, elmRes: {'混沌':50}, resists_Debuff: 50 }, possibleOpts: ['mp', 'mag', 'def', 'elmAtk'] },
    { rank: 200, name: "終焉の足跡", type: "足", baseName: "ブーツ", data: { spd: 45000, def: 8000, doubleAction: 20, resists_Shock: 50 }, possibleOpts: ['def', 'spd', 'finDmg', 'finRed', 'elmRes'] },
    { rank: 200, name: "悠久の歩み", type: "足", baseName: "くつ", data: { spd: 180000, fastestAction: 40, resists_Shock: 50 }, possibleOpts: ['spd', 'finDmg', 'finRed', 'elmAtk'] }
];

window.EQUIP_MASTER = EQUIP_MASTER;