/* ==========================================================================
   equips.js - 装備品マスタデータベース (旧システム互換体裁)
   ========================================================================== */

const EQUIP_MASTER = [
    { eid:1, noRandom: false, rank: 1, name: "ひのきのぼう", type: "武器", baseName: "剣", data: { atk: 12, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:2, noRandom: false, rank: 1, name: "石のオノ", type: "武器", baseName: "斧", data: { atk: 20, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:3, noRandom: false, rank: 1, name: "銅のナイフ", type: "武器", baseName: "短剣", data: { atk: 5, mag: 5, cri: 2 }, possibleOpts: [], traits: [] },
    { eid:4, noRandom: false, rank: 1, name: "樫の杖", type: "武器", baseName: "杖", data: { mag: 15 }, possibleOpts: [], traits: [] },
    { eid:5, noRandom: false, rank: 1, name: "たけのやり", type: "武器", baseName: "槍", data: { atk: 15 }, possibleOpts: [], traits: [] },
    { eid:6, noRandom: false, rank: 1, name: "おもちゃの弓", type: "武器", baseName: "弓", data: { atk: 15, cri: 5, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:7, noRandom: false, rank: 1, name: "おなべのふた", type: "盾", baseName: "盾", data: { def: 10, mdef: 5 }, possibleOpts: [], traits: [] },
    { eid:8, noRandom: false, rank: 1, name: "銅のバングル", type: "盾", baseName: "腕輪", data: { atk: 5, def: 5, mag: 5, mdef: 5 }, possibleOpts: [], traits: [] },
    { eid:9, noRandom: false, rank: 1, name: "皮のぼうし", type: "頭", baseName: "兜", data: { def: 8, mdef: 2, hp: 20, mp: 10 }, possibleOpts: [], traits: [] },
    { eid:10, noRandom: false, rank: 1, name: "ターバン", type: "頭", baseName: "帽子", data: { def: 2, mdef: 8, hp: 10, mp: 20 }, possibleOpts: [], traits: [] },
    { eid:11, noRandom: false, rank: 1, name: "布の服", type: "体", baseName: "鎧", data: { def: 10, mdef: 3 }, possibleOpts: [], traits: [] },
    { eid:12, noRandom: false, rank: 1, name: "旅人の服", type: "体", baseName: "ローブ", data: { def: 5, mag: 5, mdef: 5 }, possibleOpts: [], traits: [] },
    { eid:13, noRandom: false, rank: 1, name: "皮のくつ", type: "足", baseName: "ブーツ", data: { def: 5, mdef: 5, spd: 5 }, possibleOpts: [], traits: [] },
    { eid:14, noRandom: false, rank: 1, name: "わらじ", type: "足", baseName: "くつ", data: { spd: 10, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:21, noRandom: false, rank: 10, name: "銅のつるぎ", type: "武器", baseName: "剣", data: { atk: 45, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:22, noRandom: false, rank: 10, name: "鉄のオノ", type: "武器", baseName: "斧", data: { atk: 65, spd: -10, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:23, noRandom: false, rank: 10, name: "鉄のナイフ", type: "武器", baseName: "短剣", data: { atk: 30, mag: 30, cri: 5 }, possibleOpts: [], traits: [] },
    { eid:24, noRandom: false, rank: 10, name: "魔導士の杖", type: "武器", baseName: "杖", data: { mag: 55 }, possibleOpts: [], traits: [] },
    { eid:25, noRandom: false, rank: 10, name: "鉄のやり", type: "武器", baseName: "槍", data: { atk: 55 }, possibleOpts: [], traits: [] },
    { eid:26, noRandom: false, rank: 10, name: "ショートボウ", type: "武器", baseName: "弓", data: { atk: 55, cri: 5, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:27, noRandom: false, rank: 10, name: "皮のたて", type: "盾", baseName: "盾", data: { def: 45, mdef: 25 }, possibleOpts: [], traits: [] },
    { eid:28, noRandom: false, rank: 10, name: "鉄の腕輪", type: "盾", baseName: "腕輪", data: { atk: 15, def: 20, mag: 15, mdef: 25 }, possibleOpts: [], traits: [] },
    { eid:29, noRandom: false, rank: 10, name: "木のヘルメット", type: "頭", baseName: "兜", data: { def: 30, mdef: 15, hp: 40, mp: 80 }, possibleOpts: [], traits: [] },
    { eid:30, noRandom: false, rank: 10, name: "羽根ぼうし", type: "頭", baseName: "帽子", data: { def: 15, mdef: 30, hp: 80, mp: 40 }, possibleOpts: [], traits: [] },
    { eid:31, noRandom: false, rank: 10, name: "皮のよろい", type: "体", baseName: "鎧", data: { def: 55, mdef: 30 }, possibleOpts: [], traits: [] },
    { eid:32, noRandom: false, rank: 10, name: "稽古着", type: "体", baseName: "ローブ", data: { def: 35, mag: 35, mdef: 45 }, possibleOpts: [], traits: [] },
    { eid:33, noRandom: false, rank: 10, name: "鉄のグリーヴ", type: "足", baseName: "ブーツ", data: { def: 30, spd: 30 }, possibleOpts: [], traits: [] },
    { eid:34, noRandom: false, rank: 10, name: "旅人のくつ", type: "足", baseName: "くつ", data: { spd: 55, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:41, noRandom: false, rank: 20, name: "鉄のつるぎ", type: "武器", baseName: "剣", data: { atk: 108, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:42, noRandom: false, rank: 20, name: "バトルアックス", type: "武器", baseName: "斧", data: { atk: 156, spd: -24, hit: -10 }, possibleOpts: [], traits: [{"id":9,"level":3}] },
    { eid:43, noRandom: false, rank: 20, name: "どくがのナイフ", type: "武器", baseName: "短剣", data: { atk: 72, mag: 72, cri: 5, attack_Poison: 10 }, possibleOpts: [], traits: [] },
    { eid:44, noRandom: false, rank: 20, name: "ルーンスタッフ", type: "武器", baseName: "杖", data: { mag: 132 }, possibleOpts: [], traits: [] },
    { eid:45, noRandom: false, rank: 20, name: "パルチザン", type: "武器", baseName: "槍", data: { atk: 132 }, possibleOpts: [], traits: [] },
    { eid:46, noRandom: false, rank: 20, name: "クロスボウ", type: "武器", baseName: "弓", data: { atk: 132, cri: 5, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:47, noRandom: false, rank: 20, name: "鉄のたて", type: "盾", baseName: "盾", data: { def: 108, mdef: 60 }, possibleOpts: [], traits: [] },
    { eid:48, noRandom: false, rank: 20, name: "銀のバングル", type: "盾", baseName: "腕輪", data: { atk: 36, def: 48, mag: 36, mdef: 60 }, possibleOpts: [], traits: [] },
    { eid:49, noRandom: false, rank: 20, name: "鉄かぶと", type: "頭", baseName: "兜", data: { def: 72, mdef: 36, hp: 96, mp: 192 }, possibleOpts: [], traits: [] },
    { eid:50, noRandom: false, rank: 20, name: "魔道士の帽子", type: "頭", baseName: "帽子", data: { def: 36, mdef: 72, hp: 192, mp: 96 }, possibleOpts: [], traits: [] },
    { eid:51, noRandom: false, rank: 20, name: "鎖かたびら", type: "体", baseName: "鎧", data: { def: 132, mdef: 72, finRed: 3 }, possibleOpts: [], traits: [] },
    { eid:52, noRandom: false, rank: 20, name: "絹のローブ", type: "体", baseName: "ローブ", data: { def: 84, mag: 84, mdef: 108 }, possibleOpts: [], traits: [] },
    { eid:53, noRandom: false, rank: 20, name: "鋼のブーツ", type: "足", baseName: "ブーツ", data: { def: 72, spd: 72 }, possibleOpts: [], traits: [] },
    { eid:54, noRandom: false, rank: 20, name: "ラバーソール", type: "足", baseName: "くつ", data: { spd: 132, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:61, noRandom: false, rank: 30, name: "はがねのつるぎ", type: "武器", baseName: "剣", data: { atk: 162, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:62, noRandom: false, rank: 30, name: "鋼鉄のギロチン", type: "武器", baseName: "斧", data: { atk: 234, spd: -36, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:63, noRandom: false, rank: 30, name: "アサシンダガー", type: "武器", baseName: "短剣", data: { atk: 108, mag: 108, cri: 5, attack_InstantDeath: 2 }, possibleOpts: ['attack_InstantDeath'], traits: [{"id":61,"level":1}] },
    { eid:64, noRandom: false, rank: 30, name: "まどろみの杖", type: "武器", baseName: "杖", data: { mag: 198 }, possibleOpts: [], traits: [{"id":31,"level":3}] },
    { eid:65, noRandom: false, rank: 30, name: "はがねのやり", type: "武器", baseName: "槍", data: { atk: 198 }, possibleOpts: [], traits: [] },
    { eid:66, noRandom: false, rank: 30, name: "ロングボウ", type: "武器", baseName: "弓", data: { atk: 198, cri: 7, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:67, noRandom: false, rank: 30, name: "はがねのたて", type: "盾", baseName: "盾", data: { def: 162, mdef: 90 }, possibleOpts: [], traits: [] },
    { eid:68, noRandom: false, rank: 30, name: "鋼鉄の腕輪", type: "盾", baseName: "腕輪", data: { atk: 54, def: 72, mag: 54, mdef: 90 }, possibleOpts: [], traits: [] },
    { eid:69, noRandom: false, rank: 30, name: "はがねのかぶと", type: "頭", baseName: "兜", data: { def: 108, mdef: 54, hp: 144, mp: 288 }, possibleOpts: [], traits: [] },
    { eid:70, noRandom: false, rank: 30, name: "銀の髪飾り", type: "頭", baseName: "帽子", data: { def: 54, mdef: 108, hp: 288, mp: 144 }, possibleOpts: [], traits: [] },
    { eid:71, noRandom: false, rank: 30, name: "鉄のよろい", type: "体", baseName: "鎧", data: { def: 198, mdef: 108, finRed: 5 }, possibleOpts: [], traits: [] },
    { eid:72, noRandom: false, rank: 30, name: "魔道士の服", type: "体", baseName: "ローブ", data: { def: 126, mag: 126, mdef: 162 }, possibleOpts: [], traits: [] },
    { eid:73, noRandom: false, rank: 30, name: "銀のブーツ", type: "足", baseName: "ブーツ", data: { def: 108, spd: 108 }, possibleOpts: [], traits: [] },
    { eid:74, noRandom: false, rank: 30, name: "俊足のサンダル", type: "足", baseName: "くつ", data: { spd: 198, eva: 5 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:81, noRandom: false, rank: 40, name: "破邪の剣", type: "武器", baseName: "剣", data: { atk: 216, hit: 10 }, possibleOpts: [], traits: [{"id":33,"level":3}] },
    { eid:82, noRandom: false, rank: 40, name: "大地のオノ", type: "武器", baseName: "斧", data: { atk: 312, spd: -48, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:83, noRandom: false, rank: 40, name: "ミスリルナイフ", type: "武器", baseName: "短剣", data: { atk: 144, mag: 144, cri: 5 }, possibleOpts: [], traits: [{"id":8,"level":5}] },
    { eid:84, noRandom: false, rank: 40, name: "ホーリーランス", type: "武器", baseName: "槍", data: { atk: 264, finRed: 5 }, possibleOpts: [], traits: [] },
    { eid:85, noRandom: false, rank: 40, name: "狩人の弓", type: "武器", baseName: "弓", data: { atk: 264, cri: 10, hit: -15, attack_Poison: 10 }, possibleOpts: [], traits: [{"id":34,"level":3}] },
    { eid:86, noRandom: false, rank: 40, name: "マジカルスタッフ", type: "武器", baseName: "杖", data: { mag: 264 }, possibleOpts: [], traits: [] },
    { eid:87, noRandom: false, rank: 40, name: "魔法の盾", type: "盾", baseName: "盾", data: { def: 216, mdef: 120 }, possibleOpts: [], traits: [{"id":16,"level":3}] },
    { eid:88, noRandom: false, rank: 40, name: "黄金のブレスレット", type: "盾", baseName: "腕輪", data: { atk: 72, def: 96, mag: 72, mdef: 120 }, possibleOpts: [], traits: [] },
    { eid:89, noRandom: false, rank: 40, name: "知力の兜", type: "頭", baseName: "兜", data: { def: 144, mdef: 72, hp: 192, mp: 384 }, possibleOpts: [], traits: [] },
    { eid:90, noRandom: false, rank: 40, name: "黄金のティアラ", type: "頭", baseName: "帽子", data: { def: 72, mdef: 144, hp: 384, mp: 192 }, possibleOpts: [], traits: [] },
    { eid:91, noRandom: false, rank: 40, name: "はがねのよろい", type: "体", baseName: "鎧", data: { def: 264, mdef: 144, finRed: 8 }, possibleOpts: [], traits: [] },
    { eid:92, noRandom: false, rank: 40, name: "魔法の法衣", type: "体", baseName: "ローブ", data: { def: 168, mag: 168, mdef: 216 }, possibleOpts: [], traits: [] },
    { eid:93, noRandom: false, rank: 40, name: "黄金のグリーヴ", type: "足", baseName: "ブーツ", data: { def: 144, spd: 144 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:94, noRandom: false, rank: 40, name: "魔法のサンダル", type: "足", baseName: "くつ", data: { spd: 264, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:101, noRandom: false, rank: 50, name: "ドラゴンキラー", type: "武器", baseName: "剣", data: { atk: 270, hit: 10 }, possibleOpts: [], traits: [{"id":36,"level":5}] },
    { eid:102, noRandom: false, rank: 50, name: "魔神のオノ", type: "武器", baseName: "斧", data: { atk: 390, spd: -60, cri: 30, hit: -30 }, possibleOpts: [], traits: [] },
    { eid:103, noRandom: false, rank: 50, name: "グラディウス", type: "武器", baseName: "短剣", data: { atk: 180, mag: 180, cri: 5 }, possibleOpts: [], traits: [] },
    { eid:104, noRandom: false, rank: 50, name: "賢者の杖", type: "武器", baseName: "杖", data: { mag: 330 }, possibleOpts: [], traits: [{"id":11,"level":3}] },
    { eid:105, noRandom: false, rank: 50, name: "トライデント", type: "武器", baseName: "槍", data: { atk: 330 }, possibleOpts: [], traits: [] },
    { eid:106, noRandom: false, rank: 50, name: "コンポジットボウ", type: "武器", baseName: "弓", data: { atk: 330, cri: 12, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:107, noRandom: false, rank: 50, name: "ドラゴンシールド", type: "盾", baseName: "盾", data: { def: 270, mdef: 150 }, possibleOpts: [], traits: [{"id":17,"level":3}] },
    { eid:108, noRandom: false, rank: 50, name: "竜のうろこ", type: "盾", baseName: "腕輪", data: { atk: 90, def: 120, mag: 90, mdef: 150 }, possibleOpts: [], traits: [] },
    { eid:109, noRandom: false, rank: 50, name: "ミスリルヘルム", type: "頭", baseName: "兜", data: { def: 180, mdef: 90, hp: 240, mp: 480 }, possibleOpts: [], traits: [] },
    { eid:110, noRandom: false, rank: 50, name: "司祭の帽子", type: "頭", baseName: "帽子", data: { def: 90, mdef: 180, hp: 480, mp: 240 }, possibleOpts: [], traits: [] },
    { eid:111, noRandom: false, rank: 50, name: "魔法の鎧", type: "体", baseName: "鎧", data: { def: 330, mdef: 180, finRed: 10 }, possibleOpts: [], traits: [] },
    { eid:112, noRandom: false, rank: 50, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 210, mag: 210, mdef: 270 }, possibleOpts: [], traits: [] },
    { eid:113, noRandom: false, rank: 50, name: "ミスリルブーツ", type: "足", baseName: "ブーツ", data: { def: 180, spd: 180 }, possibleOpts: [], traits: [] },
    { eid:114, noRandom: false, rank: 50, name: "フェザーシューズ", type: "足", baseName: "くつ", data: { spd: 330, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:121, noRandom: false, rank: 60, name: "プラチナソード", type: "武器", baseName: "剣", data: { atk: 324, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:122, noRandom: false, rank: 60, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 468, spd: -72, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:123, noRandom: false, rank: 60, name: "ソウルブレイカー", type: "武器", baseName: "短剣", data: { atk: 216, mag: 216, cri: 5, attack_Fear: 10 }, possibleOpts: [], traits: [] },
    { eid:124, noRandom: false, rank: 60, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 396 }, possibleOpts: [], traits: [] },
    { eid:125, noRandom: false, rank: 60, name: "プラチナランス", type: "武器", baseName: "槍", data: { atk: 396 }, possibleOpts: [], traits: [] },
    { eid:126, noRandom: false, rank: 60, name: "プラチナボウ", type: "武器", baseName: "弓", data: { atk: 396, cri: 15, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:127, noRandom: false, rank: 60, name: "プラチナシールド", type: "盾", baseName: "盾", data: { def: 324, mdef: 180, resists_Debuff: 5 }, possibleOpts: [], traits: [] },
    { eid:128, noRandom: false, rank: 60, name: "ミスリルバングル", type: "盾", baseName: "腕輪", data: { atk: 108, def: 144, mag: 108, mdef: 180 }, possibleOpts: [], traits: [] },
    { eid:129, noRandom: false, rank: 60, name: "プラチナヘッド", type: "頭", baseName: "兜", data: { def: 216, mdef: 108, hp: 288, mp: 576 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:130, noRandom: false, rank: 60, name: "賢者のターバン", type: "頭", baseName: "帽子", data: { def: 108, mdef: 216, hp: 576, mp: 288 }, possibleOpts: [], traits: [{"id":20,"level":5}] },
    { eid:131, noRandom: false, rank: 60, name: "ドラゴンメイル", type: "体", baseName: "鎧", data: { def: 396, mdef: 216 }, possibleOpts: [], traits: [{"id":17,"level":3}] },
    { eid:132, noRandom: false, rank: 60, name: "ミスリルケープ", type: "体", baseName: "ローブ", data: { def: 252, mag: 252, mdef: 324 }, possibleOpts: [], traits: [] },
    { eid:133, noRandom: false, rank: 60, name: "竜のブーツ", type: "足", baseName: "ブーツ", data: { def: 216, spd: 216 }, possibleOpts: [], traits: [] },
    { eid:134, noRandom: false, rank: 60, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 396, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:141, noRandom: false, rank: 70, name: "隼の剣", type: "武器", baseName: "剣", data: { atk: 378, hit: 10, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:142, noRandom: false, rank: 70, name: "破壊の鉄球", type: "武器", baseName: "斧", data: { atk: 546, spd: -84, hit: -10 }, possibleOpts: [], traits: [{"id":9,"level":5}] },
    { eid:143, noRandom: false, rank: 70, name: "フェニックスダガー", type: "武器", baseName: "短剣", data: { atk: 252, mag: 252, cri: 5 }, possibleOpts: [], traits: [] },
    { eid:144, noRandom: false, rank: 70, name: "精霊の杖", type: "武器", baseName: "杖", data: { mag: 462 }, possibleOpts: [], traits: [] },
    { eid:145, noRandom: false, rank: 70, name: "竜の髭", type: "武器", baseName: "槍", data: { atk: 462 }, possibleOpts: [], traits: [{"id":12,"level":5}] },
    { eid:146, noRandom: false, rank: 70, name: "風の弓", type: "武器", baseName: "弓", data: { atk: 462, cri: 18, hit: -15 }, possibleOpts: [], traits: [{"id":25,"level":3}] },
    { eid:147, noRandom: false, rank: 70, name: "鏡の盾", type: "盾", baseName: "盾", data: { def: 378, mdef: 210 }, possibleOpts: [], traits: [{"id":50,"level":3}] },
    { eid:148, noRandom: false, rank: 70, name: "守りのルーン", type: "盾", baseName: "腕輪", data: { atk: 126, def: 168, mag: 126, mdef: 210, resists_Debuff: 10 }, possibleOpts: [], traits: [] },
    { eid:149, noRandom: false, rank: 70, name: "隼の兜", type: "頭", baseName: "兜", data: { def: 252, mdef: 126, hp: 336, mp: 672 }, possibleOpts: [], traits: [] },
    { eid:150, noRandom: false, rank: 70, name: "精霊の帽子", type: "頭", baseName: "帽子", data: { def: 126, mdef: 252, hp: 672, mp: 336 }, possibleOpts: [], traits: [] },
    { eid:151, noRandom: false, rank: 70, name: "刃のよろい", type: "体", baseName: "鎧", data: { def: 462, mdef: 252 }, possibleOpts: [], traits: [{"id":49,"level":3}] },
    { eid:152, noRandom: false, rank: 70, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 294, mag: 294, mdef: 378 }, possibleOpts: [], traits: [] },
    { eid:153, noRandom: false, rank: 70, name: "天使のブーツ", type: "足", baseName: "ブーツ", data: { def: 252, spd: 252 }, possibleOpts: [], traits: [] },
    { eid:154, noRandom: false, rank: 70, name: "韋駄天のくつ", type: "足", baseName: "くつ", data: { spd: 462, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:161, noRandom: false, rank: 80, name: "はぐれメタルの剣", type: "武器", baseName: "剣", data: { atk: 432, cri: 10, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:162, noRandom: false, rank: 80, name: "はぐれメタルのオノ", type: "武器", baseName: "斧", data: { atk: 624, spd: -96, hit: -10, attack_Fear: 10 }, possibleOpts: [], traits: [] },
    { eid:163, noRandom: false, rank: 80, name: "はぐれメタルの短剣", type: "武器", baseName: "短剣", data: { atk: 288, mag: 288, cri: 5, attack_Poison: 15 }, possibleOpts: [], traits: [] },
    { eid:164, noRandom: false, rank: 80, name: "はぐれメタルの杖", type: "武器", baseName: "杖", data: { mag: 528, finDmg: 10 }, possibleOpts: [], traits: [] },
    { eid:165, noRandom: false, rank: 80, name: "はぐれメタルのやり", type: "武器", baseName: "槍", data: { atk: 528, cri: 5, hit: 5 }, possibleOpts: [], traits: [] },
    { eid:166, noRandom: false, rank: 80, name: "はぐれメタルの弓", type: "武器", baseName: "弓", data: { atk: 528, cri: 20, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:167, noRandom: false, rank: 80, name: "はぐれメタルの盾", type: "盾", baseName: "盾", data: { def: 432, mdef: 240 }, possibleOpts: [], traits: [] },
    { eid:168, noRandom: false, rank: 80, name: "はぐれメタルの腕輪", type: "盾", baseName: "腕輪", data: { atk: 144, def: 192, mag: 144, mdef: 240 }, possibleOpts: [], traits: [{"id":22,"level":5}] },
    { eid:169, noRandom: false, rank: 80, name: "はぐれメタルヘルム", type: "頭", baseName: "兜", data: { def: 288, mdef: 144, hp: 384, mp: 768, resists_Fear: 10 }, possibleOpts: [], traits: [] },
    { eid:170, noRandom: false, rank: 80, name: "はぐれメタルの帽子", type: "頭", baseName: "帽子", data: { def: 144, mdef: 288, hp: 768, mp: 384 }, possibleOpts: [], traits: [] },
    { eid:171, noRandom: false, rank: 80, name: "はぐれメタルの鎧", type: "体", baseName: "鎧", data: { def: 528, mdef: 288, finRed: 10 }, possibleOpts: [], traits: [] },
    { eid:172, noRandom: false, rank: 80, name: "はぐれメタルのローブ", type: "体", baseName: "ローブ", data: { def: 336, mag: 336, mdef: 432 }, possibleOpts: [], traits: [] },
    { eid:173, noRandom: false, rank: 80, name: "はぐれメタルのブーツ", type: "足", baseName: "ブーツ", data: { def: 288, spd: 288 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:174, noRandom: false, rank: 80, name: "はぐれメタルのくつ", type: "足", baseName: "くつ", data: { spd: 528, eva: 5 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:181, noRandom: false, rank: 90, name: "真魔剛竜剣", type: "武器", baseName: "剣", data: { atk: 486, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:182, noRandom: false, rank: 90, name: "ギガントアックス", type: "武器", baseName: "斧", data: { atk: 702, spd: -108, hit: -10, attack_Fear: 10 }, possibleOpts: [], traits: [{"id":9,"level":5}] },
    { eid:183, noRandom: false, rank: 90, name: "神速の暗器", type: "武器", baseName: "短剣", data: { atk: 324, mag: 324, cri: 5, attack_Poison: 15, attack_InstantDeath: 2 }, possibleOpts: [], traits: [{"id":32,"level":5}] },
    { eid:184, noRandom: false, rank: 90, name: "ドラゴンの杖", type: "武器", baseName: "杖", data: { mag: 594 }, possibleOpts: [], traits: [{"id":23,"level":5}] },
    { eid:185, noRandom: false, rank: 90, name: "ゲイボルグ", type: "武器", baseName: "槍", data: { atk: 594, finDmg: 5 }, possibleOpts: [], traits: [] },
    { eid:186, noRandom: false, rank: 90, name: "アルテミスの弓", type: "武器", baseName: "弓", data: { atk: 594, cri: 20, hit: -15 }, possibleOpts: [], traits: [] },
    { eid:187, noRandom: false, rank: 90, name: "覇者の盾", type: "盾", baseName: "盾", data: { def: 486, mdef: 270, resists_Debuff: 15 }, possibleOpts: [], traits: [] },
    { eid:188, noRandom: false, rank: 90, name: "覇者の紋章", type: "盾", baseName: "腕輪", data: { atk: 162, def: 216, mag: 162, mdef: 270 }, possibleOpts: [], traits: [] },
    { eid:189, noRandom: false, rank: 90, name: "天獄の兜", type: "頭", baseName: "兜", data: { def: 324, mdef: 162, hp: 432, mp: 864 }, possibleOpts: [], traits: [] },
    { eid:190, noRandom: false, rank: 90, name: "星天のティアラ", type: "頭", baseName: "帽子", data: { def: 162, mdef: 324, hp: 864, mp: 432, resists_SpellSeal: 10 }, possibleOpts: [], traits: [] },
    { eid:191, noRandom: false, rank: 90, name: "覇王の鎧", type: "体", baseName: "鎧", data: { def: 594, mdef: 324, finRed: 10 }, possibleOpts: [], traits: [] },
    { eid:192, noRandom: false, rank: 90, name: "プリンセスローブ", type: "体", baseName: "ローブ", data: { def: 378, mag: 378, mdef: 486 }, possibleOpts: [], traits: [{"id":39,"level":5}] },
    { eid:193, noRandom: false, rank: 90, name: "冥府のグリーヴ", type: "足", baseName: "ブーツ", data: { def: 324, spd: 324 }, possibleOpts: [], traits: [] },
    { eid:194, noRandom: false, rank: 90, name: "ペガサスの靴", type: "足", baseName: "くつ", data: { spd: 594, eva: 5 }, possibleOpts: [], traits: [] },
    { eid:201, noRandom: false, rank: 100, name: "王者の剣", type: "武器", baseName: "剣", data: { atk: 900, hit: 10, attack_Fear: 10 }, possibleOpts: [], traits: [] },
    { eid:202, noRandom: false, rank: 100, name: "天罰の巨斧", type: "武器", baseName: "斧", data: { atk: 1300, spd: -200, hit: -10, attack_Fear: 10 }, possibleOpts: [], traits: [] },
    { eid:203, noRandom: false, rank: 100, name: "トリトンダガー", type: "武器", baseName: "短剣", data: { atk: 600, mag: 600, cri: 10, attack_Poison: 15 }, possibleOpts: [], traits: [] },
    { eid:204, noRandom: false, rank: 100, name: "神鳥の杖", type: "武器", baseName: "杖", data: { mag: 1100, finDmg: 10 }, possibleOpts: [], traits: [{"id":12,"level":5}] },
    { eid:205, noRandom: false, rank: 100, name: "聖槍ロンギヌス", type: "武器", baseName: "槍", data: { atk: 1100 }, possibleOpts: [], traits: [] },
    { eid:206, noRandom: false, rank: 100, name: "天之麻迦古弓", type: "武器", baseName: "弓", data: { atk: 1100, cri: 20, hit: -15, attack_InstantDeath: 5 }, possibleOpts: [], traits: [] },
    { eid:207, noRandom: false, rank: 100, name: "地獄の盾", type: "盾", baseName: "盾", data: { def: 900, mdef: 500 }, possibleOpts: [], traits: [] },
    { eid:208, noRandom: false, rank: 100, name: "神の腕輪", type: "盾", baseName: "腕輪", data: { atk: 300, def: 400, mag: 300, mdef: 500, finDmg: 5 }, possibleOpts: [], traits: [] },
    { eid:209, noRandom: false, rank: 100, name: "天帝の冠", type: "頭", baseName: "兜", data: { def: 600, mdef: 300, hp: 800, mp: 1600, resists_Fear: 20 }, possibleOpts: [], traits: [] },
    { eid:210, noRandom: false, rank: 100, name: "神の知恵袋", type: "頭", baseName: "帽子", data: { def: 300, mdef: 600, hp: 1600, mp: 800, resists_SpellSeal: 20 }, possibleOpts: [], traits: [] },
    { eid:211, noRandom: false, rank: 100, name: "天のゼウスメイル", type: "体", baseName: "鎧", data: { def: 1100, mdef: 600, finRed: 10 }, possibleOpts: [], traits: [{"id":53,"level":5}] },
    { eid:212, noRandom: false, rank: 100, name: "常世の法衣", type: "体", baseName: "ローブ", data: { def: 700, mag: 700, mdef: 900 }, possibleOpts: [], traits: [{"id":52,"level":5}] },
    { eid:213, noRandom: false, rank: 100, name: "オーディンレッグ", type: "足", baseName: "ブーツ", data: { def: 600, spd: 600 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:214, noRandom: false, rank: 100, name: "神速の具足", type: "足", baseName: "くつ", data: { spd: 1100, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:221, noRandom: false, rank: 110, name: "英雄の剣", type: "武器", baseName: "剣", data: { atk: 990, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:222, noRandom: false, rank: 110, name: "覇者の大斧", type: "武器", baseName: "斧", data: { atk: 1430, spd: -220, hit: -10, attack_Fear: 10 }, possibleOpts: [], traits: [{"id":9,"level":5}] },
    { eid:223, noRandom: false, rank: 110, name: "飛燕のダガー", type: "武器", baseName: "短剣", data: { atk: 660, mag: 660, cri: 10, attack_Poison: 15 }, possibleOpts: [], traits: [] },
    { eid:224, noRandom: false, rank: 110, name: "大賢者の杖", type: "武器", baseName: "杖", data: { mag: 1210 }, possibleOpts: [], traits: [{"id":11,"level":5}] },
    { eid:225, noRandom: false, rank: 110, name: "英雄の槍", type: "武器", baseName: "槍", data: { atk: 1210, finRed: 5 }, possibleOpts: [], traits: [{"id":51,"level":5}] },
    { eid:226, noRandom: false, rank: 110, name: "英雄の弓", type: "武器", baseName: "弓", data: { atk: 1210, cri: 25, hit: -20 }, possibleOpts: [], traits: [{"id":36,"level":5}] },
    { eid:227, noRandom: false, rank: 110, name: "英雄の盾", type: "盾", baseName: "盾", data: { def: 990, mdef: 550, resists_Debuff: 20 }, possibleOpts: [], traits: [] },
    { eid:228, noRandom: false, rank: 110, name: "英雄の腕輪", type: "盾", baseName: "腕輪", data: { atk: 330, def: 440, mag: 330, mdef: 550 }, possibleOpts: [], traits: [] },
    { eid:229, noRandom: false, rank: 110, name: "英雄の兜", type: "頭", baseName: "兜", data: { def: 660, mdef: 330, hp: 880, mp: 1760 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:230, noRandom: false, rank: 110, name: "賢者の帽子", type: "頭", baseName: "帽子", data: { def: 330, mdef: 660, hp: 1760, mp: 880 }, possibleOpts: [], traits: [{"id":20,"level":5}] },
    { eid:231, noRandom: false, rank: 110, name: "英雄の鎧", type: "体", baseName: "鎧", data: { def: 1210, mdef: 660, finRed: 10 }, possibleOpts: [], traits: [{"id":37,"level":5}] },
    { eid:232, noRandom: false, rank: 110, name: "賢者のローブ", type: "体", baseName: "ローブ", data: { def: 770, mag: 770, mdef: 990 }, possibleOpts: [], traits: [] },
    { eid:233, noRandom: false, rank: 110, name: "英雄のブーツ", type: "足", baseName: "ブーツ", data: { def: 660, spd: 660 }, possibleOpts: [], traits: [] },
    { eid:234, noRandom: false, rank: 110, name: "俊足の靴", type: "足", baseName: "くつ", data: { spd: 1210, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:241, noRandom: false, rank: 120, name: "勇者のつるぎ", type: "武器", baseName: "剣", data: { atk: 1080, hit: 10 }, possibleOpts: [], traits: [{"id":38,"level":5}] },
    { eid:242, noRandom: false, rank: 120, name: "覇王の戦斧", type: "武器", baseName: "斧", data: { atk: 1560, spd: -240, hit: -10, attack_Fear: 10 }, possibleOpts: [], traits: [{"id":9,"level":5}] },
    { eid:243, noRandom: false, rank: 120, name: "オリハルコンナイフ", type: "武器", baseName: "短剣", data: { atk: 720, mag: 720, cri: 10, attack_InstantDeath: 3 }, possibleOpts: [], traits: [] },
    { eid:244, noRandom: false, rank: 120, name: "アルテマスタッフ", type: "武器", baseName: "杖", data: { mag: 1320 }, possibleOpts: [], traits: [] },
    { eid:245, noRandom: false, rank: 120, name: "勇者の槍", type: "武器", baseName: "槍", data: { atk: 1320, hit: 10 }, possibleOpts: [], traits: [{"id":37,"level":5}] },
    { eid:246, noRandom: false, rank: 120, name: "勇者の弓", type: "武器", baseName: "弓", data: { atk: 1320, cri: 25, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:247, noRandom: false, rank: 120, name: "女神の盾", type: "盾", baseName: "盾", data: { def: 1080, mdef: 600, resists_InstantDeath: 20, resists_Debuff: 20 }, possibleOpts: [], traits: [] },
    { eid:248, noRandom: false, rank: 120, name: "勇気の紋章", type: "盾", baseName: "腕輪", data: { atk: 360, def: 480, mag: 360, mdef: 600 }, possibleOpts: [], traits: [] },
    { eid:249, noRandom: false, rank: 120, name: "王者の冠", type: "頭", baseName: "兜", data: { def: 720, mdef: 360, hp: 960, mp: 1920, resists_Fear: 25 }, possibleOpts: [], traits: [{"id":52,"level":5}] },
    { eid:250, noRandom: false, rank: 120, name: "司教のミトラ", type: "頭", baseName: "帽子", data: { def: 360, mdef: 720, hp: 1920, mp: 960, resists_SpellSeal: 25 }, possibleOpts: [], traits: [{"id":53,"level":5}] },
    { eid:251, noRandom: false, rank: 120, name: "王者のマント", type: "体", baseName: "鎧", data: { def: 1320, mdef: 720, finRed: 15 }, possibleOpts: [], traits: [] },
    { eid:252, noRandom: false, rank: 120, name: "天使のローブ", type: "体", baseName: "ローブ", data: { def: 840, mag: 840, mdef: 1080 }, possibleOpts: [], traits: [{"id":13,"level":5}] },
    { eid:253, noRandom: false, rank: 120, name: "勇者の具足", type: "足", baseName: "ブーツ", data: { def: 720, spd: 720, resists_Shock: 40 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:254, noRandom: false, rank: 120, name: "星降る靴", type: "足", baseName: "くつ", data: { spd: 1320, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:261, noRandom: false, rank: 130, name: "竜神王の剣", type: "武器", baseName: "剣", data: { atk: 1170, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:262, noRandom: false, rank: 130, name: "ミョルニル", type: "武器", baseName: "斧", data: { atk: 1690, spd: -260, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:263, noRandom: false, rank: 130, name: "月下の小太刀", type: "武器", baseName: "短剣", data: { atk: 780, mag: 780, cri: 10, attack_Poison: 20 }, possibleOpts: [], traits: [{"id":8,"level":5}] },
    { eid:264, noRandom: false, rank: 130, name: "世界樹の杖", type: "武器", baseName: "杖", data: { mag: 1430, finRed: 10 }, possibleOpts: [], traits: [{"id":13,"level":5}] },
    { eid:265, noRandom: false, rank: 130, name: "竜神の槍", type: "武器", baseName: "槍", data: { atk: 1430 }, possibleOpts: [], traits: [] },
    { eid:266, noRandom: false, rank: 130, name: "竜神の弓", type: "武器", baseName: "弓", data: { atk: 1430, cri: 25, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:267, noRandom: false, rank: 130, name: "竜神の盾", type: "盾", baseName: "盾", data: { def: 1170, mdef: 650 }, possibleOpts: [], traits: [] },
    { eid:268, noRandom: false, rank: 130, name: "輝石のバングル", type: "盾", baseName: "腕輪", data: { atk: 390, def: 520, mag: 390, mdef: 650, resists_Debuff: 30 }, possibleOpts: [], traits: [] },
    { eid:269, noRandom: false, rank: 130, name: "龍神の兜", type: "頭", baseName: "兜", data: { def: 780, mdef: 390, hp: 1040, mp: 2080, resists_Fear: 30 }, possibleOpts: [], traits: [] },
    { eid:270, noRandom: false, rank: 130, name: "マジカルリボン", type: "頭", baseName: "帽子", data: { def: 390, mdef: 780, hp: 2080, mp: 1040 }, possibleOpts: [], traits: [] },
    { eid:271, noRandom: false, rank: 130, name: "竜神のよろい", type: "体", baseName: "鎧", data: { def: 1430, mdef: 780, finRed: 15 }, possibleOpts: [], traits: [] },
    { eid:272, noRandom: false, rank: 130, name: "虹色のローブ", type: "体", baseName: "ローブ", data: { def: 910, mag: 910, mdef: 1170 }, possibleOpts: [], traits: [] },
    { eid:273, noRandom: false, rank: 130, name: "竜神の靴", type: "足", baseName: "ブーツ", data: { def: 780, spd: 780 }, possibleOpts: [], traits: [] },
    { eid:274, noRandom: false, rank: 130, name: "エルフのサンダル", type: "足", baseName: "くつ", data: { spd: 1430, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:281, noRandom: false, rank: 140, name: "ラグナロク", type: "武器", baseName: "剣", data: { atk: 1260, hit: 10, attack_Fear: 10 }, possibleOpts: [], traits: [{"id":29,"level":5}] },
    { eid:282, noRandom: false, rank: 140, name: "バハムートアクス", type: "武器", baseName: "斧", data: { atk: 1820, spd: -280, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:283, noRandom: false, rank: 140, name: "ソウルイーター", type: "武器", baseName: "短剣", data: { atk: 840, mag: 840, cri: 10, attack_InstantDeath: 5 }, possibleOpts: [], traits: [] },
    { eid:284, noRandom: false, rank: 140, name: "虚空の杖", type: "武器", baseName: "杖", data: { mag: 1540, finRed: 10, finDmg: 10 }, possibleOpts: [], traits: [] },
    { eid:285, noRandom: false, rank: 140, name: "ブリューナク", type: "武器", baseName: "槍", data: { atk: 1540 }, possibleOpts: [], traits: [] },
    { eid:286, noRandom: false, rank: 140, name: "バハムートボウ", type: "武器", baseName: "弓", data: { atk: 1540, cri: 25, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:287, noRandom: false, rank: 140, name: "イージスの盾", type: "盾", baseName: "盾", data: { def: 1260, mdef: 700, finRed: 10, resists_Debuff: 30 }, possibleOpts: [], traits: [{"id":17,"level":5}] },
    { eid:288, noRandom: false, rank: 140, name: "星座の腕輪", type: "盾", baseName: "腕輪", data: { atk: 420, def: 560, mag: 420, mdef: 700 }, possibleOpts: [], traits: [] },
    { eid:289, noRandom: false, rank: 140, name: "黄金のマスク", type: "頭", baseName: "兜", data: { def: 840, mdef: 420, hp: 1120, mp: 2240, resists_InstantDeath: 20 }, possibleOpts: [], traits: [] },
    { eid:290, noRandom: false, rank: 140, name: "星座のベレー", type: "頭", baseName: "帽子", data: { def: 420, mdef: 840, hp: 2240, mp: 1120 }, possibleOpts: [], traits: [] },
    { eid:291, noRandom: false, rank: 140, name: "天界の鎧", type: "体", baseName: "鎧", data: { def: 1540, mdef: 840, finRed: 20 }, possibleOpts: [], traits: [] },
    { eid:292, noRandom: false, rank: 140, name: "星辰の法衣", type: "体", baseName: "ローブ", data: { def: 980, mag: 980, mdef: 1260 }, possibleOpts: [], traits: [] },
    { eid:293, noRandom: false, rank: 140, name: "戦神のグリーヴ", type: "足", baseName: "ブーツ", data: { def: 840, spd: 840 }, possibleOpts: [], traits: [] },
    { eid:294, noRandom: false, rank: 140, name: "飛翔の靴", type: "足", baseName: "くつ", data: { spd: 1540, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:301, noRandom: false, rank: 150, name: "メタルキングの剣", type: "武器", baseName: "剣", data: { atk: 1350, cri: 15, hit: 10 }, possibleOpts: [], traits: [] },
    { eid:302, noRandom: false, rank: 150, name: "メタルキングの大斧", type: "武器", baseName: "斧", data: { atk: 1950, spd: -300, hit: -10, attack_Fear: 15 }, possibleOpts: [], traits: [{"id":9,"level":5}] },
    { eid:303, noRandom: false, rank: 150, name: "メタルキングダガー", type: "武器", baseName: "短剣", data: { atk: 900, mag: 900, cri: 10, attack_Poison: 20, attack_InstantDeath: 5 }, possibleOpts: [], traits: [] },
    { eid:304, noRandom: false, rank: 150, name: "メタルキングの杖", type: "武器", baseName: "杖", data: { mag: 1650, finDmg: 10 }, possibleOpts: [], traits: [] },
    { eid:305, noRandom: false, rank: 150, name: "メタルキングの槍", type: "武器", baseName: "槍", data: { atk: 1650, cri: 10 }, possibleOpts: [], traits: [] },
    { eid:306, noRandom: false, rank: 150, name: "メタルキングの弓", type: "武器", baseName: "弓", data: { atk: 1650, cri: 25, hit: -20 }, possibleOpts: [], traits: [{"id":34,"level":5}] },
    { eid:307, noRandom: false, rank: 150, name: "メタルキングの盾", type: "盾", baseName: "盾", data: { def: 1350, mdef: 750, resists_Debuff: 30 }, possibleOpts: [], traits: [{"id":16,"level":5}] },
    { eid:308, noRandom: false, rank: 150, name: "メタルキングの紋章", type: "盾", baseName: "腕輪", data: { atk: 450, def: 600, mag: 450, mdef: 750, finDmg: 10 }, possibleOpts: [], traits: [{"id":22,"level":5}] },
    { eid:309, noRandom: false, rank: 150, name: "メタルキングヘルム", type: "頭", baseName: "兜", data: { def: 900, mdef: 450, hp: 1200, mp: 2400, resists_Fear: 50, resists_InstantDeath: 50 }, possibleOpts: [], traits: [{"id":15,"level":3},{"id":17,"level":3}] },
    { eid:310, noRandom: false, rank: 150, name: "メタルキングの大冠", type: "頭", baseName: "帽子", data: { def: 450, mdef: 900, hp: 2400, mp: 1200, resists_SpellSeal: 50 }, possibleOpts: [], traits: [{"id":16,"level":5}] },
    { eid:311, noRandom: false, rank: 150, name: "メタルキングの鎧", type: "体", baseName: "鎧", data: { def: 1650, mdef: 900, finRed: 20, resists_SkillSeal: 50, resists_SpellSeal: 50 }, possibleOpts: [], traits: [{"id":16,"level":5},{"id":17,"level":5}] },
    { eid:312, noRandom: false, rank: 150, name: "メタルキングローブ", type: "体", baseName: "ローブ", data: { def: 1050, mag: 1050, mdef: 1350, resists_HealSeal: 50 }, possibleOpts: [], traits: [{"id":11,"level":5},{"id":13,"level":5}] },
    { eid:313, noRandom: false, rank: 150, name: "メタルキングブーツ", type: "足", baseName: "ブーツ", data: { def: 900, spd: 900, resists_Shock: 70 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:314, noRandom: false, rank: 150, name: "メタルキングのくつ", type: "足", baseName: "くつ", data: { spd: 1650, eva: 10 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:321, noRandom: false, rank: 160, name: "終焉の剣", type: "武器", baseName: "剣", data: { atk: 1440, hit: 10, attack_InstantDeath: 2 }, possibleOpts: [], traits: [] },
    { eid:322, noRandom: false, rank: 160, name: "ヴォルカノン", type: "武器", baseName: "斧", data: { atk: 2080, spd: -320, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:323, noRandom: false, rank: 160, name: "宵闇の牙", type: "武器", baseName: "短剣", data: { atk: 960, mag: 960, cri: 10, attack_InstantDeath: 7 }, possibleOpts: [], traits: [] },
    { eid:324, noRandom: false, rank: 160, name: "コスモロッド", type: "武器", baseName: "杖", data: { mag: 1760 }, possibleOpts: [], traits: [] },
    { eid:325, noRandom: false, rank: 160, name: "アビスランス", type: "武器", baseName: "槍", data: { atk: 1760 }, possibleOpts: [], traits: [{"id":28,"level":5}] },
    { eid:326, noRandom: false, rank: 160, name: "フェイルノート", type: "武器", baseName: "弓", data: { atk: 1760, cri: 25, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:327, noRandom: false, rank: 160, name: "天界の盾", type: "盾", baseName: "盾", data: { def: 1440, mdef: 800, finRed: 10 }, possibleOpts: [], traits: [] },
    { eid:328, noRandom: false, rank: 160, name: "太陽のバングル", type: "盾", baseName: "腕輪", data: { atk: 480, def: 640, mag: 480, mdef: 800 }, possibleOpts: [], traits: [] },
    { eid:329, noRandom: false, rank: 160, name: "星詠みの兜", type: "頭", baseName: "兜", data: { def: 960, mdef: 480, hp: 1280, mp: 2560, resists_Fear: 40 }, possibleOpts: [], traits: [] },
    { eid:330, noRandom: false, rank: 160, name: "精霊の冠", type: "頭", baseName: "帽子", data: { def: 480, mdef: 960, hp: 2560, mp: 1280 }, possibleOpts: [], traits: [] },
    { eid:331, noRandom: false, rank: 160, name: "鳳凰の鎧", type: "体", baseName: "鎧", data: { def: 1760, mdef: 960 }, possibleOpts: [], traits: [] },
    { eid:332, noRandom: false, rank: 160, name: "聖者のガウン", type: "体", baseName: "ローブ", data: { def: 1120, mag: 1120, mdef: 1440, resists_Debuff: 30 }, possibleOpts: [], traits: [] },
    { eid:333, noRandom: false, rank: 160, name: "幻影のブーツ", type: "足", baseName: "ブーツ", data: { def: 960, spd: 960 }, possibleOpts: [], traits: [{"id":14,"level":5}] },
    { eid:334, noRandom: false, rank: 160, name: "水面の靴", type: "足", baseName: "くつ", data: { spd: 1760, eva: 10 }, possibleOpts: [], traits: [] },
    { eid:341, noRandom: false, rank: 170, name: "ツインカノン", type: "武器", baseName: "剣", data: { atk: 1530, hit: 10, eva: 10 }, possibleOpts: [], traits: [{"id":8,"level":5}] },
    { eid:342, noRandom: false, rank: 170, name: "ガルガリン", type: "武器", baseName: "斧", data: { atk: 2210, spd: -340, hit: -10 }, possibleOpts: [], traits: [{"id":18,"level":5}] },
    { eid:343, noRandom: false, rank: 170, name: "時空の針", type: "武器", baseName: "短剣", data: { atk: 1020, mag: 1020, cri: 10, attack_Poison: 20 }, possibleOpts: [], traits: [{"id":8,"level":5}] },
    { eid:344, noRandom: false, rank: 170, name: "神託の杖", type: "武器", baseName: "杖", data: { mag: 1870, finRed: 10 }, possibleOpts: [], traits: [{"id":18,"level":5}] },
    { eid:345, noRandom: false, rank: 170, name: "創世の槍", type: "武器", baseName: "槍", data: { atk: 1870, finRed: 10 }, possibleOpts: [], traits: [] },
    { eid:346, noRandom: false, rank: 170, name: "明星の弓", type: "武器", baseName: "弓", data: { atk: 1870, cri: 25, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:347, noRandom: false, rank: 170, name: "輪廻の盾", type: "盾", baseName: "盾", data: { def: 1530, mdef: 850, finRed: 10, resists_Debuff: 30 }, possibleOpts: [], traits: [{"id":50,"level":10}] },
    { eid:348, noRandom: false, rank: 170, name: "月光のバングル", type: "盾", baseName: "腕輪", data: { atk: 510, def: 680, mag: 510, mdef: 850, resists_Fear: 40 }, possibleOpts: [], traits: [] },
    { eid:349, noRandom: false, rank: 170, name: "真実の仮面", type: "頭", baseName: "兜", data: { def: 1020, mdef: 510, hp: 1360, mp: 2720, resists_Fear: 50 }, possibleOpts: [], traits: [] },
    { eid:350, noRandom: false, rank: 170, name: "夢幻の帽子", type: "頭", baseName: "帽子", data: { def: 510, mdef: 1020, hp: 2720, mp: 1360 }, possibleOpts: [], traits: [] },
    { eid:351, noRandom: false, rank: 170, name: "星座のよろい", type: "体", baseName: "鎧", data: { def: 1870, mdef: 1020, finRed: 20, resists_SkillSeal: 45 }, possibleOpts: [], traits: [] },
    { eid:352, noRandom: false, rank: 170, name: "女神のドレス", type: "体", baseName: "ローブ", data: { def: 1190, mag: 1190, mdef: 1530, resists_HealSeal: 40 }, possibleOpts: [], traits: [] },
    { eid:353, noRandom: false, rank: 170, name: "明星のグリーヴ", type: "足", baseName: "ブーツ", data: { def: 1020, spd: 1020 }, possibleOpts: [], traits: [] },
    { eid:354, noRandom: false, rank: 170, name: "無音の靴", type: "足", baseName: "くつ", data: { spd: 1870, eva: 10, resists_Shock: 45 }, possibleOpts: [], traits: [{"id":42,"level":5}] },
    { eid:361, noRandom: false, rank: 180, name: "オメガブレイド", type: "武器", baseName: "剣", data: { atk: 1620, hit: 10, finDmg: 15 }, possibleOpts: [], traits: [] },
    { eid:362, noRandom: false, rank: 180, name: "天変地異", type: "武器", baseName: "斧", data: { atk: 2340, spd: -360, hit: -10, attack_Fear: 20 }, possibleOpts: [], traits: [] },
    { eid:363, noRandom: false, rank: 180, name: "無音の暗殺刃", type: "武器", baseName: "短剣", data: { atk: 1080, mag: 1080, cri: 10, attack_Poison: 30, attack_InstantDeath: 8 }, possibleOpts: ['attack_InstantDeath'], traits: [{"id":61,"level":5}] },
    { eid:364, noRandom: false, rank: 180, name: "始祖の魔杖", type: "武器", baseName: "杖", data: { mag: 1980, resists_SpellSeal: 30 }, possibleOpts: [], traits: [] },
    { eid:365, noRandom: false, rank: 180, name: "ロンゴミニアド", type: "武器", baseName: "槍", data: { atk: 1980, finDmg: 10 }, possibleOpts: [], traits: [] },
    { eid:366, noRandom: false, rank: 180, name: "オメガボウ", type: "武器", baseName: "弓", data: { atk: 1980, cri: 25, hit: -20 }, possibleOpts: [], traits: [{"id":29,"level":5}] },
    { eid:367, noRandom: false, rank: 180, name: "ゼウスの盾", type: "盾", baseName: "盾", data: { def: 1620, mdef: 900, finRed: 15 }, possibleOpts: [], traits: [] },
    { eid:368, noRandom: false, rank: 180, name: "混沌の腕輪", type: "盾", baseName: "腕輪", data: { atk: 540, def: 720, mag: 540, mdef: 900 }, possibleOpts: [], traits: [] },
    { eid:369, noRandom: false, rank: 180, name: "神々の王冠", type: "頭", baseName: "兜", data: { def: 1080, mdef: 540, hp: 1440, mp: 2880, resists_Fear: 60 }, possibleOpts: [], traits: [{"id":21,"level":5}] },
    { eid:370, noRandom: false, rank: 180, name: "審判のカチュール", type: "頭", baseName: "帽子", data: { def: 540, mdef: 1080, hp: 2880, mp: 1440, resists_HealSeal: 50 }, possibleOpts: [], traits: [{"id":20,"level":5}] },
    { eid:371, noRandom: false, rank: 180, name: "神威の装束", type: "体", baseName: "鎧", data: { def: 1980, mdef: 1080, resists_Debuff: 40 }, possibleOpts: [], traits: [{"id":40,"level":5}] },
    { eid:372, noRandom: false, rank: 180, name: "虚無の法衣", type: "体", baseName: "ローブ", data: { def: 1260, mag: 1260, mdef: 1620 }, possibleOpts: [], traits: [] },
    { eid:373, noRandom: false, rank: 180, name: "獅子のレガース", type: "足", baseName: "ブーツ", data: { def: 1080, spd: 1080 }, possibleOpts: [], traits: [] },
    { eid:374, noRandom: false, rank: 180, name: "光速のサンダル", type: "足", baseName: "くつ", data: { spd: 1980, eva: 15 }, possibleOpts: [], traits: [] },
    { eid:381, noRandom: false, rank: 190, name: "エクスカリバー", type: "武器", baseName: "剣", data: { atk: 1710, hit: 10, finDmg: 15 }, possibleOpts: [], traits: [{"id":27,"level":5}] },
    { eid:382, noRandom: false, rank: 190, name: "ゼウスのアクス", type: "武器", baseName: "斧", data: { atk: 2470, spd: -380, hit: -10 }, possibleOpts: [], traits: [] },
    { eid:383, noRandom: false, rank: 190, name: "神殺しの匕首", type: "武器", baseName: "短剣", data: { atk: 1140, mag: 1140, cri: 10, attack_Poison: 30, attack_InstantDeath: 9 }, possibleOpts: ['attack_InstantDeath'], traits: [] },
    { eid:384, noRandom: false, rank: 190, name: "アポカリプス", type: "武器", baseName: "杖", data: { mag: 2090, finDmg: 10 }, possibleOpts: [], traits: [] },
    { eid:385, noRandom: false, rank: 190, name: "究極の聖槍", type: "武器", baseName: "槍", data: { atk: 2090, finDmg: 10 }, possibleOpts: [], traits: [{"id":27,"level":5}] },
    { eid:386, noRandom: false, rank: 190, name: "究極の神弓", type: "武器", baseName: "弓", data: { atk: 2090, cri: 30, hit: -20 }, possibleOpts: [], traits: [] },
    { eid:387, noRandom: false, rank: 190, name: "アカシックシールド", type: "盾", baseName: "盾", data: { def: 1710, mdef: 950, finRed: 15 }, possibleOpts: [], traits: [{"id":15,"level":5}] },
    { eid:388, noRandom: false, rank: 190, name: "神話の紋章", type: "盾", baseName: "腕輪", data: { atk: 570, def: 760, mag: 570, mdef: 950 }, possibleOpts: [], traits: [] },
    { eid:389, noRandom: false, rank: 190, name: "虚空の兜", type: "頭", baseName: "兜", data: { def: 1140, mdef: 570, hp: 1520, mp: 3040, resists_InstantDeath: 40 }, possibleOpts: [], traits: [] },
    { eid:390, noRandom: false, rank: 190, name: "明星の帽子", type: "頭", baseName: "帽子", data: { def: 570, mdef: 1140, hp: 3040, mp: 1520 }, possibleOpts: [], traits: [] },
    { eid:391, noRandom: false, rank: 190, name: "至高の神鎧", type: "体", baseName: "鎧", data: { def: 2090, mdef: 1140, finRed: 20 }, possibleOpts: [], traits: [{"id":37,"level":5}] },
    { eid:392, noRandom: false, rank: 190, name: "宇宙のケープ", type: "体", baseName: "ローブ", data: { def: 1330, mag: 1330, mdef: 1710 }, possibleOpts: [], traits: [] },
    { eid:393, noRandom: false, rank: 190, name: "神話のブーツ", type: "足", baseName: "ブーツ", data: { def: 1140, spd: 1140 }, possibleOpts: [], traits: [] },
    { eid:394, noRandom: false, rank: 190, name: "時空の靴", type: "足", baseName: "くつ", data: { spd: 2090, eva: 15 }, possibleOpts: [], traits: [] },
    { eid:401, noRandom: false, rank: 200, name: "滅神の剣", type: "武器", baseName: "剣", data: { atk: 2250, hit: 10 }, possibleOpts: [], traits: [{"id":10,"level":10}] },
    { eid:402, noRandom: false, rank: 200, name: "破滅の断罪斧", type: "武器", baseName: "斧", data: { atk: 3250, spd: -500, hit: -10, attack_Fear: 20 }, possibleOpts: ['attack_InstantDeath'], traits: [{"id":9,"level":10}] },
    { eid:403, noRandom: false, rank: 200, name: "幻想の終止符", type: "武器", baseName: "短剣", data: { atk: 1500, mag: 1500, cri: 15, attack_Poison: 50, attack_InstantDeath: 10 }, possibleOpts: [], traits: [{"id":61,"level":5}] },
    { eid:404, noRandom: false, rank: 200, name: "全知の神杖", type: "武器", baseName: "杖", data: { mag: 2750, resists_SpellSeal: 50 }, possibleOpts: [], traits: [{"id":30,"level":10}] },
    { eid:405, noRandom: false, rank: 200, name: "神滅の魔槍", type: "武器", baseName: "槍", data: { atk: 2750, finDmg: 10 }, possibleOpts: [], traits: [{"id":10,"level":10}] },
    { eid:406, noRandom: false, rank: 200, name: "幻想の真弓", type: "武器", baseName: "弓", data: { atk: 2750, cri: 40, hit: -25, finDmg: 20 }, possibleOpts: [], traits: [{"id":6,"level":10}] },
    { eid:407, noRandom: false, rank: 200, name: "エタニティガード", type: "盾", baseName: "盾", data: { def: 2250, mdef: 1250, finRed: 15, resists_Debuff: 50 }, possibleOpts: [], traits: [{"id":15,"level":5},{"id":16,"level":5},{"id":17,"level":5}] },
    { eid:408, noRandom: false, rank: 200, name: "創世の腕輪", type: "盾", baseName: "腕輪", data: { atk: 750, def: 1000, mag: 750, mdef: 1250, finDmg: 20, resists_Debuff: 50 }, possibleOpts: [], traits: [{"id":20,"level":5},{"id":21,"level":5}] },
    { eid:409, noRandom: false, rank: 200, name: "無窮の冠", type: "頭", baseName: "兜", data: { def: 1500, mdef: 750, hp: 2000, mp: 4000, resists_Fear: 50, resists_InstantDeath: 50 }, possibleOpts: [], traits: [{"id":10,"level":10}] },
    { eid:410, noRandom: false, rank: 200, name: "叡智の宝冠", type: "頭", baseName: "帽子", data: { def: 750, mdef: 1500, hp: 4000, mp: 2000, resists_SpellSeal: 50, resists_HealSeal: 50 }, possibleOpts: [], traits: [{"id":11,"level":10}] },
    { eid:411, noRandom: false, rank: 200, name: "創世の神鎧", type: "体", baseName: "鎧", data: { def: 2750, mdef: 1500, finRed: 25, resists_SkillSeal: 50 }, possibleOpts: [], traits: [{"id":15,"level":8},{"id":18,"level":5}] },
    { eid:412, noRandom: false, rank: 200, name: "終焉の神衣", type: "体", baseName: "ローブ", data: { def: 1750, mag: 1750, mdef: 2250, resists_Debuff: 50 }, possibleOpts: [], traits: [{"id":11,"level":8},{"id":16,"level":5}] },
    { eid:413, noRandom: false, rank: 200, name: "終焉の足跡", type: "足", baseName: "ブーツ", data: { def: 1500, spd: 1500, resists_Shock: 50 }, possibleOpts: [], traits: [{"id":14,"level":5},{"id":48,"level":5}] },
    { eid:414, noRandom: false, rank: 200, name: "悠久の歩み", type: "足", baseName: "くつ", data: { spd: 2750, eva: 20, resists_Shock: 50 }, possibleOpts: [], traits: [{"id":14,"level":5},{"id":44,"level":5}] }
];

window.EQUIP_MASTER = EQUIP_MASTER;