/* items.js - canonical authored item and material data */
window.ITEMS_DATA = [
    {
        "id": 1,
        "rank": 1,
        "name": "やくそう",
        "type": "HP回復",
        "val": 25,
        "desc": "HPを25回復",
        "target": "単体",
        "price": 10
    },
    {
        "id": 8,
        "rank": 1,
        "name": "毒消し草",
        "type": "状態異常回復",
        "cures": [
            "Poison",
            "ToxicPoison"
        ],
        "desc": "毒・猛毒を解毒する",
        "target": "単体",
        "price": 20
    },
    {
        "id": 3,
        "rank": 5,
        "name": "魔法の小瓶",
        "type": "MP回復",
        "val": 12,
        "desc": "MPを12回復",
        "target": "単体",
        "price": 100
    },
    {
        "id": 2,
        "rank": 5,
        "name": "上やくそう",
        "type": "HP回復",
        "val": 60,
        "desc": "HPを60回復",
        "target": "単体",
        "price": 50
    },
    {
        "id": 9,
        "rank": 10,
        "name": "やまびこ草",
        "type": "状態異常回復",
        "cures": [
            "SpellSeal"
        ],
        "desc": "呪文封印を解除する",
        "target": "単体",
        "price": 150
    },
    {
        "id": 10,
        "rank": 10,
        "name": "記憶の実",
        "type": "状態異常回復",
        "cures": [
            "SkillSeal"
        ],
        "desc": "特技封印を解除する",
        "target": "単体",
        "price": 150
    },
    {
        "id": 11,
        "rank": 10,
        "name": "妖精の涙",
        "type": "状態異常回復",
        "cures": [
            "HealSeal"
        ],
        "desc": "回復封印を解除する",
        "target": "単体",
        "price": 150
    },
    {
        "id": 4,
        "rank": 20,
        "name": "魔法の聖水",
        "type": "MP回復",
        "val": 40,
        "desc": "MPを40回復",
        "target": "単体",
        "price": 500
    },
    {
        "id": 5,
        "rank": 30,
        "name": "世界樹の葉",
        "type": "蘇生",
        "val": 100,
        "desc": "死んだ仲間をHP全快で生き返らせる",
        "target": "単体",
        "price": 20000
    },
    {
        "id": 13,
        "rank": 40,
        "name": "超やくそう",
        "type": "HP回復",
        "val": 180,
        "desc": "HPを180回復",
        "target": "単体",
        "price": 20000
    },
    {
        "id": 12,
        "rank": 50,
        "name": "世界樹の木の実",
        "type": "状態異常回復",
        "CureAilments": true,
        "debuff_reset": true,
        "desc": "味方ひとりの全状態異常を治す",
        "target": "単体",
        "price": 20000,
        "cures": [
            "Poison",
            "ToxicPoison",
            "SpellSeal",
            "SkillSeal",
            "HealSeal",
            "Shock"
        ]
    },
    {
        "id": 14,
        "rank": 60,
        "name": "賢者の聖水",
        "type": "MP回復",
        "val": 90,
        "desc": "MPを90回復",
        "target": "単体",
        "price": 50000
    },
    {
        "id": 7,
        "rank": 70,
        "name": "エルフの飲み薬",
        "type": "MP回復",
        "val": 999999,
        "desc": "MPを全回復",
        "target": "単体",
        "price": 300000
    },
    {
        "id": 6,
        "rank": 80,
        "name": "世界樹の雫",
        "type": "HP回復",
        "val": 999999,
        "desc": "味方全員のHPを全回復",
        "target": "全体",
        "price": 500000
    },
    {
        "id": 98,
        "rank": 99,
        "name": "災厄の楔",
        "type": "貴重品",
        "val": 0,
        "desc": "メダル交換所で災厄の王と戦えるようになる呪物",
        "target": "なし",
        "price": 0
    },
    {
        "id": 99,
        "rank": 99,
        "name": "ちいさなメダル",
        "type": "貴重品",
        "val": 0,
        "desc": "世界各地に散らばるなぞのメダル",
        "target": "なし",
        "price": 0
    },
    {
        "id": 108,
        "rank": 99,
        "name": "魔法の小舟",
        "type": "貴重品",
        "val": 0,
        "desc": "持っていると、海を小舟に乗って移動できる。",
        "target": "なし",
        "price": 0
    },
    {
        "id": 109,
        "rank": 99,
        "name": "光の翼",
        "type": "乗り物",
        "val": 0,
        "desc": "使用すると空を飛ぶことができる。OKボタンで着地する。",
        "target": "なし",
        "price": 0
    },
    {
        "id": 110,
        "rank": 1,
        "name": "スカイプリズム",
        "type": "移動",
        "val": 0,
        "desc": "訪れたことのある場所の入口へ移動する。ダンジョン内でも使用できる。",
        "target": "なし",
        "price": 3000
    },
    {
        "id": 111,
        "rank": 99,
        "name": "星詠みの触媒器",
        "type": "貴重品",
        "val": 0,
        "desc": "王から託された加工用の触媒器。所持していると、メニューから鍛冶と錬金を利用できる。",
        "target": "なし",
        "price": 0
    },
    {
        "id": 100,
        "name": "いのちのきのみ",
        "type": "育成",
        "desc": "最大HPを3増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 101,
        "name": "ふしぎのきのみ",
        "type": "育成",
        "desc": "最大MPを2増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 102,
        "name": "ちからのたね",
        "type": "育成",
        "desc": "攻撃力を1増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 103,
        "name": "まりょくのたね",
        "type": "育成",
        "desc": "魔力を1増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 104,
        "name": "すばやさのたね",
        "type": "育成",
        "desc": "素早さを1増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 105,
        "name": "まもりのたね",
        "type": "育成",
        "desc": "防御力を1増加",
        "target": "単体",
        "price": 0
    },
    {
        "id": 106,
        "name": "スキルのたね",
        "type": "育成",
        "desc": "スキルポイント(SP)を1加算",
        "target": "単体",
        "price": 0
    },
    {
        "id": 107,
        "name": "転生の実",
        "type": "育成",
        "desc": "能力を維持したままLv1に戻る禁断の果実",
        "target": "単体",
        "price": 0
    },
    {
        "id": 112,
        "rank": 99,
        "name": "剣の特性書",
        "type": "特性書",
        "traitId": 1,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「剣」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 113,
        "rank": 99,
        "name": "槍の特性書",
        "type": "特性書",
        "traitId": 2,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「槍」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 114,
        "rank": 99,
        "name": "斧の特性書",
        "type": "特性書",
        "traitId": 3,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「斧」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 115,
        "rank": 99,
        "name": "短剣の特性書",
        "type": "特性書",
        "traitId": 4,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「短剣」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 116,
        "rank": 99,
        "name": "弓の特性書",
        "type": "特性書",
        "traitId": 5,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「弓」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 117,
        "rank": 99,
        "name": "杖の特性書",
        "type": "特性書",
        "traitId": 7,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「杖」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 118,
        "rank": 99,
        "name": "鷹の目の特性書",
        "type": "特性書",
        "traitId": 6,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「鷹の目」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 119,
        "rank": 99,
        "name": "武術の特性書",
        "type": "特性書",
        "traitId": 10,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「武術」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 120,
        "rank": 99,
        "name": "呪文の特性書",
        "type": "特性書",
        "traitId": 11,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「呪文」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 121,
        "rank": 99,
        "name": "息吹の特性書",
        "type": "特性書",
        "traitId": 12,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「息吹」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 122,
        "rank": 99,
        "name": "治癒の特性書",
        "type": "特性書",
        "traitId": 13,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "交換可能な特性枠1つを「治癒」に変更する。元の特性Lvは引き継ぐ。重複不可。使用後になくなる。"
    },
    {
        "id": 123,
        "rank": 99,
        "name": "超越の実",
        "type": "育成",
        "effectKind": "limitBreak",
        "limitBreakAmount": 1,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": true,
        "target": "単体",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "仲間ひとりのLBを1増加させる。試練による上限を越えて使用することはできない。"
    },
    {
        "id": 301,
        "rank": 8,
        "name": "妖精の聖水",
        "type": "貴重品",
        "desc": "火山の炎を鎮めるための聖水",
        "target": "なし",
        "price": 0
    },
    {
        "id": 302,
        "rank": 23,
        "name": "青の結晶",
        "type": "貴重品",
        "desc": "海底神殿への道を示す結晶",
        "target": "なし",
        "price": 0
    },
    {
        "id": 303,
        "rank": 75,
        "name": "闇祓いの欠片",
        "type": "素材",
        "desc": "闇の神殿跡地で見つかる素材",
        "target": "なし",
        "price": 1200
    },
    {
        "id": 304,
        "rank": 85,
        "name": "禁則の残滓",
        "type": "素材",
        "desc": "禁則地に漂う魔力の結晶",
        "target": "なし",
        "price": 1800
    },
    {
        "id": 305,
        "rank": 90,
        "name": "天使の羽片",
        "type": "素材",
        "desc": "試練の天使が落とす淡い羽片",
        "target": "なし",
        "price": 3000
    },
    {
        "id": 306,
        "rank": 30,
        "name": "調律の羅針片",
        "type": "貴重品",
        "desc": "火と水の流れを読む小さな羅針片",
        "target": "なし",
        "price": 0
    },
    {
        "id": 5108,
        "rank": 99,
        "name": "ニ刀流の特性書",
        "type": "特性書",
        "traitId": 8,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「ニ刀流」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5109,
        "rank": 99,
        "name": "両手持ちの特性書",
        "type": "特性書",
        "traitId": 9,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「両手持ち」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5114,
        "rank": 99,
        "name": "体さばきの特性書",
        "type": "特性書",
        "traitId": 14,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「体さばき」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5115,
        "rank": 99,
        "name": "頑丈の特性書",
        "type": "特性書",
        "traitId": 15,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「頑丈」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5116,
        "rank": 99,
        "name": "魔法壁の特性書",
        "type": "特性書",
        "traitId": 16,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「魔法壁」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5117,
        "rank": 99,
        "name": "心頭滅却の特性書",
        "type": "特性書",
        "traitId": 17,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「心頭滅却」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5118,
        "rank": 99,
        "name": "根性の特性書",
        "type": "特性書",
        "traitId": 18,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「根性」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5119,
        "rank": 99,
        "name": "底力の特性書",
        "type": "特性書",
        "traitId": 19,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「底力」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5120,
        "rank": 99,
        "name": "冷静の特性書",
        "type": "特性書",
        "traitId": 20,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「冷静」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5121,
        "rank": 99,
        "name": "強靭の特性書",
        "type": "特性書",
        "traitId": 21,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「強靭」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5122,
        "rank": 99,
        "name": "急所狙いの特性書",
        "type": "特性書",
        "traitId": 22,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「急所狙い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5123,
        "rank": 99,
        "name": "火の扱いの特性書",
        "type": "特性書",
        "traitId": 23,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「火の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5124,
        "rank": 99,
        "name": "水の扱いの特性書",
        "type": "特性書",
        "traitId": 24,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「水の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5125,
        "rank": 99,
        "name": "風の扱いの特性書",
        "type": "特性書",
        "traitId": 25,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「風の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5126,
        "rank": 99,
        "name": "雷の扱いの特性書",
        "type": "特性書",
        "traitId": 26,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「雷の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5127,
        "rank": 99,
        "name": "光の扱いの特性書",
        "type": "特性書",
        "traitId": 27,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「光の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5128,
        "rank": 99,
        "name": "闇の扱いの特性書",
        "type": "特性書",
        "traitId": 28,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「闇の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5129,
        "rank": 99,
        "name": "混沌の扱いの特性書",
        "type": "特性書",
        "traitId": 29,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「混沌の扱い」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5130,
        "rank": 99,
        "name": "解析の特性書",
        "type": "特性書",
        "traitId": 30,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「解析」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5131,
        "rank": 99,
        "name": "呪い体質の特性書",
        "type": "特性書",
        "traitId": 31,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「呪い体質」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5132,
        "rank": 99,
        "name": "人体知識の特性書",
        "type": "特性書",
        "traitId": 32,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「人体知識」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5133,
        "rank": 99,
        "name": "悪魔ばらいの特性書",
        "type": "特性書",
        "traitId": 33,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「悪魔ばらい」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5134,
        "rank": 99,
        "name": "獣狩りの特性書",
        "type": "特性書",
        "traitId": 34,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「獣狩り」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5135,
        "rank": 99,
        "name": "メカニックの特性書",
        "type": "特性書",
        "traitId": 35,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「メカニック」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5136,
        "rank": 99,
        "name": "竜殺しの特性書",
        "type": "特性書",
        "traitId": 36,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「竜殺し」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5137,
        "rank": 99,
        "name": "護衛の特性書",
        "type": "特性書",
        "traitId": 37,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「護衛」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5138,
        "rank": 99,
        "name": "勇猛の特性書",
        "type": "特性書",
        "traitId": 38,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「勇猛」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5139,
        "rank": 99,
        "name": "応援の特性書",
        "type": "特性書",
        "traitId": 39,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「応援」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5140,
        "rank": 99,
        "name": "司令塔の特性書",
        "type": "特性書",
        "traitId": 40,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「司令塔」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5141,
        "rank": 99,
        "name": "警戒の特性書",
        "type": "特性書",
        "traitId": 41,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「警戒」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5142,
        "rank": 99,
        "name": "忍び足の特性書",
        "type": "特性書",
        "traitId": 42,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「忍び足」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5143,
        "rank": 99,
        "name": "挑発の特性書",
        "type": "特性書",
        "traitId": 43,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「挑発」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5144,
        "rank": 99,
        "name": "潜伏の特性書",
        "type": "特性書",
        "traitId": 44,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「潜伏」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5145,
        "rank": 99,
        "name": "倍返しの特性書",
        "type": "特性書",
        "traitId": 45,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「倍返し」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5146,
        "rank": 99,
        "name": "追い討ちの特性書",
        "type": "特性書",
        "traitId": 46,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「追い討ち」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5147,
        "rank": 99,
        "name": "連携の特性書",
        "type": "特性書",
        "traitId": 47,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「連携」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5148,
        "rank": 99,
        "name": "先制の特性書",
        "type": "特性書",
        "traitId": 48,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「先制」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5149,
        "rank": 99,
        "name": "反撃の特性書",
        "type": "特性書",
        "traitId": 49,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「反撃」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5150,
        "rank": 99,
        "name": "理力の壁の特性書",
        "type": "特性書",
        "traitId": 50,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「理力の壁」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5151,
        "rank": 99,
        "name": "献身の特性書",
        "type": "特性書",
        "traitId": 51,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「献身」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5152,
        "rank": 99,
        "name": "再生の特性書",
        "type": "特性書",
        "traitId": 52,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「再生」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5153,
        "rank": 99,
        "name": "魔力循環の特性書",
        "type": "特性書",
        "traitId": 53,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「魔力循環」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5154,
        "rank": 99,
        "name": "応急手当の特性書",
        "type": "特性書",
        "traitId": 54,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「応急手当」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5155,
        "rank": 99,
        "name": "魔力充填の特性書",
        "type": "特性書",
        "traitId": 55,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「魔力充填」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5156,
        "rank": 99,
        "name": "解体の特性書",
        "type": "特性書",
        "traitId": 56,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「解体」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5157,
        "rank": 99,
        "name": "目利きの特性書",
        "type": "特性書",
        "traitId": 57,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「目利き」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5158,
        "rank": 99,
        "name": "大器晩成の特性書",
        "type": "特性書",
        "traitId": 58,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「大器晩成」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5159,
        "rank": 99,
        "name": "武の極みの特性書",
        "type": "特性書",
        "traitId": 59,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「武の極み」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5160,
        "rank": 99,
        "name": "魔の極みの特性書",
        "type": "特性書",
        "traitId": 60,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「魔の極み」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    },
    {
        "id": 5161,
        "rank": 99,
        "name": "暗殺術の特性書",
        "type": "特性書",
        "traitId": 61,
        "traitBookImplemented": false,
        "consumable": true,
        "battleUsable": false,
        "fieldUsable": false,
        "target": "特性枠",
        "shopAvailable": false,
        "abyssDrop": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-growth.png",
        "desc": "特性「暗殺術」へ交換するための書。マスター登録済みだが、交換機能は準備中。"
    }

];

window.ITEMS_DATA.push(
{
        "consumable": true,
        "id": 1000,
        "rank": 8,
        "name": "火炎玉",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "火",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い火属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1001,
        "rank": 50,
        "name": "業火の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "火",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い火属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1002,
        "rank": 25,
        "name": "爆炎球",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "火",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い火属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1003,
        "rank": 75,
        "name": "煉獄爆弾",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "火",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い火属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1004,
        "rank": 90,
        "name": "鳳凰の火筒",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "火",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い火属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1005,
        "rank": 8,
        "name": "水撃瓶",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "水",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い水属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1006,
        "rank": 50,
        "name": "激流の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "水",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い水属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1007,
        "rank": 25,
        "name": "氷雨の珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "水",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い水属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1008,
        "rank": 75,
        "name": "大津波の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "水",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い水属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1009,
        "rank": 90,
        "name": "水龍の逆鱗",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "水",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い水属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1010,
        "rank": 8,
        "name": "雷鳴石",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "雷",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い雷属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1011,
        "rank": 50,
        "name": "迅雷の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "雷",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い雷属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1012,
        "rank": 25,
        "name": "雷雲珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "雷",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い雷属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1013,
        "rank": 75,
        "name": "雷霆の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "雷",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い雷属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1014,
        "rank": 90,
        "name": "雷神太鼓",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "雷",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い雷属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1015,
        "rank": 8,
        "name": "風斬りの羽",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "風",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い風属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1016,
        "rank": 50,
        "name": "暴風の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "風",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い風属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1017,
        "rank": 25,
        "name": "旋風珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "風",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い風属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1018,
        "rank": 75,
        "name": "天嵐の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "風",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い風属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1019,
        "rank": 90,
        "name": "風神の扇",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "風",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い風属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1020,
        "rank": 8,
        "name": "閃光石",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "光",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い光属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1021,
        "rank": 50,
        "name": "聖光の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "光",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い光属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1022,
        "rank": 25,
        "name": "光輪珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "光",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い光属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1023,
        "rank": 75,
        "name": "神光の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "光",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い光属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1024,
        "rank": 90,
        "name": "天使の聖印",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "光",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い光属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1025,
        "rank": 8,
        "name": "闇の魔弾",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "闇",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い闇属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1026,
        "rank": 50,
        "name": "冥闇の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "闇",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い闇属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1027,
        "rank": 25,
        "name": "黒月珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "闇",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い闇属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1028,
        "rank": 75,
        "name": "奈落の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "闇",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い闇属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1029,
        "rank": 90,
        "name": "魔王の瞳",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "闇",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い闇属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "id": 1030,
        "rank": 8,
        "name": "混沌の欠片",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "混沌",
        "power": 90,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 300,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に弱い混沌属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1031,
        "rank": 50,
        "name": "崩界の壺",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "混沌",
        "power": 420,
        "hits": 1,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 8000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵単体に強い混沌属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1032,
        "rank": 25,
        "name": "魔蝕珠",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "混沌",
        "power": 130,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 1800,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に弱い混沌属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1033,
        "rank": 75,
        "name": "終焉の器",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "混沌",
        "power": 520,
        "hits": 1,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": false,
        "shopAvailable": true,
        "price": 25000,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵全体に強い混沌属性固定ダメージを与える"
    },
    {
        "consumable": true,
        "id": 1034,
        "rank": 90,
        "name": "神喰の緋月石",
        "type": "攻撃道具",
        "effectKind": "damage",
        "element": "混沌",
        "power": 280,
        "hits": 3,
        "target": "ランダム",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-attack.png",
        "desc": "敵へランダムに3回強い混沌属性固定ダメージを与える（3回）"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1040,
        "rank": 20,
        "name": "魔力の霧",
        "type": "MP回復",
        "val": 30,
        "target": "全体",
        "price": 1200,
        "desc": "味方全員のMPを30回復"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1041,
        "rank": 45,
        "name": "賢者の香",
        "type": "MP回復",
        "val": 100,
        "target": "全体",
        "price": 6000,
        "desc": "味方全員のMPを100回復"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1042,
        "rank": 65,
        "name": "星海の聖水",
        "type": "MP回復",
        "val": 200,
        "target": "全体",
        "price": 18000,
        "desc": "味方全員のMPを200回復"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1043,
        "rank": 95,
        "name": "神霊の雫",
        "type": "MP回復",
        "val": 999,
        "target": "全体",
        "price": 0,
        "medalOnly": true,
        "shopAvailable": false,
        "desc": "味方全員のMPを999回復"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1044,
        "rank": 18,
        "name": "いやしの大粉",
        "type": "HP回復",
        "val": 80,
        "target": "全体",
        "price": 700,
        "desc": "味方全員のHPを80回復"
    },
    {
        "consumable": true,
        "battleUsable": true,
        "fieldUsable": true,
        "fieldGroup": true,
        "id": 1045,
        "rank": 55,
        "name": "生命の大霊薬",
        "type": "HP回復",
        "val": 350,
        "target": "全体",
        "price": 9000,
        "desc": "味方全員のHPを350回復"
    },
    {
        "consumable": true,
        "id": 1050,
        "rank": 35,
        "name": "剛力の霊薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "atk": 1.5
        },
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 2500,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の攻撃を50%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1051,
        "rank": 65,
        "name": "剛力の戦香",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "atk": 1.3
        },
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 15000,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方全体の攻撃を30%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1052,
        "rank": 35,
        "name": "堅守の霊薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "def": 1.5
        },
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 2500,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の防御を50%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1053,
        "rank": 65,
        "name": "堅守の戦香",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "def": 1.3
        },
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 15000,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方全体の防御を30%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1054,
        "rank": 35,
        "name": "叡智の霊薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "mag": 1.5
        },
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 2500,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の魔力を50%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1055,
        "rank": 65,
        "name": "叡智の戦香",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "mag": 1.3
        },
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 15000,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方全体の魔力を30%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1056,
        "rank": 35,
        "name": "魔障の霊薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "mdef": 1.5
        },
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 2500,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の魔法防御を50%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1057,
        "rank": 65,
        "name": "魔障の戦香",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "mdef": 1.3
        },
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 15000,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方全体の魔法防御を30%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1058,
        "rank": 35,
        "name": "七彩の霊薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "elmResUp": 50
        },
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 2500,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の全属性耐性を50%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1059,
        "rank": 65,
        "name": "七彩の戦香",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "elmResUp": 30
        },
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 15000,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方全体の全属性耐性を30%上げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1060,
        "rank": 40,
        "name": "精霊の野営具",
        "type": "キャンプ",
        "effectKind": "camp",
        "target": "全体",
        "battleUsable": false,
        "fieldUsable": true,
        "fieldGroup": true,
        "price": 6000,
        "desc": "戦闘不能者を蘇生し、味方全員のHP・MPを全回復する。戦闘中は使用不可"
    },
    {
        "consumable": true,
        "id": 1061,
        "rank": 85,
        "name": "鷹眼の秘薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "cri": 1.3
        },
        "turn": 2,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の会心率を30%上げる（2ターン）"
    },
    {
        "consumable": true,
        "id": 1062,
        "rank": 85,
        "name": "幻影の秘薬",
        "type": "強化道具",
        "effectKind": "buff",
        "buff": {
            "eva": 1.3
        },
        "turn": 2,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "medalOnly": true,
        "shopAvailable": false,
        "price": 0,
        "icon": "assets/ui/menu-icons/item-buff.png",
        "desc": "味方単体の回避率を30%上げる（2ターン）"
    },
    {
        "consumable": true,
        "id": 1070,
        "rank": 40,
        "name": "脱力の呪瓶",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "atk": 0.5
        },
        "successRate": 100,
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 3500,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵単体の攻撃を50%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1071,
        "rank": 70,
        "name": "脱力の呪香",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "atk": 0.7
        },
        "successRate": 100,
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 18000,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵全体の攻撃を30%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1072,
        "rank": 40,
        "name": "軟化の呪瓶",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "def": 0.5
        },
        "successRate": 100,
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 3500,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵単体の防御を50%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1073,
        "rank": 70,
        "name": "軟化の呪香",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "def": 0.7
        },
        "successRate": 100,
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 18000,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵全体の防御を30%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1074,
        "rank": 40,
        "name": "忘却の呪瓶",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "mag": 0.5
        },
        "successRate": 100,
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 3500,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵単体の魔力を50%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1075,
        "rank": 70,
        "name": "忘却の呪香",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "mag": 0.7
        },
        "successRate": 100,
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 18000,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵全体の魔力を30%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1076,
        "rank": 40,
        "name": "破魔の呪瓶",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "mdef": 0.5
        },
        "successRate": 100,
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 3500,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵単体の魔法防御を50%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1077,
        "rank": 70,
        "name": "破魔の呪香",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "mdef": 0.7
        },
        "successRate": 100,
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 18000,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵全体の魔法防御を30%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1078,
        "rank": 40,
        "name": "無彩の呪瓶",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "elmResDown": 50
        },
        "successRate": 100,
        "turn": 4,
        "target": "単体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 3500,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵単体の全属性耐性を50%下げる（4ターン）"
    },
    {
        "consumable": true,
        "id": 1079,
        "rank": 70,
        "name": "無彩の呪香",
        "type": "弱体道具",
        "effectKind": "debuff",
        "debuff": {
            "elmResDown": 30
        },
        "successRate": 100,
        "turn": 4,
        "target": "全体",
        "battleUsable": true,
        "fieldUsable": false,
        "price": 18000,
        "icon": "assets/ui/menu-icons/item-debuff.png",
        "desc": "敵全体の全属性耐性を30%下げる（4ターン）"
    },
    {
        "consumable": false,
        "id": 2000,
        "rank": 5,
        "materialRank": "G",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "鉄くず",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2001,
        "rank": 15,
        "materialRank": "F",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "青銅の鉱石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2002,
        "rank": 30,
        "materialRank": "E",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "黒鉄の鉱石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2003,
        "rank": 45,
        "materialRank": "D",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "ミスリルの鉱石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2004,
        "rank": 60,
        "materialRank": "C",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "オリハルコンの欠片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2005,
        "rank": 80,
        "materialRank": "B",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "星銀鋼",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2006,
        "rank": 110,
        "materialRank": "A",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "神鉄インゴット",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2007,
        "rank": 150,
        "materialRank": "S",
        "materialType": "metal",
        "materialLabel": "金属",
        "name": "アビスメタル",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "金属系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2008,
        "rank": 5,
        "materialRank": "G",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "枯れた枝",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2009,
        "rank": 15,
        "materialRank": "F",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "丈夫な木材",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2010,
        "rank": 30,
        "materialRank": "E",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "霊木の欠片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2011,
        "rank": 45,
        "materialRank": "D",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "古代樹の木片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2012,
        "rank": 60,
        "materialRank": "C",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "世界樹の枝",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2013,
        "rank": 80,
        "materialRank": "B",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "天樹の幹",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2014,
        "rank": 110,
        "materialRank": "A",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "神木の欠片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2015,
        "rank": 150,
        "materialRank": "S",
        "materialType": "wood",
        "materialLabel": "木材",
        "name": "始原樹の枝",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "木材系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2016,
        "rank": 5,
        "materialRank": "G",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "劣化魔石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2017,
        "rank": 15,
        "materialRank": "F",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "小さな魔石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2018,
        "rank": 30,
        "materialRank": "E",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "大きな魔石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2019,
        "rank": 45,
        "materialRank": "D",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "魔晶石",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2020,
        "rank": 60,
        "materialRank": "C",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "魔結晶",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2021,
        "rank": 80,
        "materialRank": "B",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "虹の結晶",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2022,
        "rank": 110,
        "materialRank": "A",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "賢者の石片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2023,
        "rank": 150,
        "materialRank": "S",
        "materialType": "magicStone",
        "materialLabel": "魔石",
        "name": "混沌の核",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "魔石系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2024,
        "rank": 5,
        "materialRank": "G",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "ぼろぼろの羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2025,
        "rank": 15,
        "materialRank": "F",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "鷹の尾羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2026,
        "rank": 30,
        "materialRank": "E",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "ふわふわの羽毛",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2027,
        "rank": 45,
        "materialRank": "D",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "幻鳥の羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2028,
        "rank": 60,
        "materialRank": "C",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "霊鳥の羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2029,
        "rank": 80,
        "materialRank": "B",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "天馬の羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2030,
        "rank": 110,
        "materialRank": "A",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "天使の羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2031,
        "rank": 150,
        "materialRank": "S",
        "materialType": "feather",
        "materialLabel": "羽",
        "name": "始祖鳥の羽",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "羽系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2032,
        "rank": 5,
        "materialRank": "G",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "欠けた爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2033,
        "rank": 15,
        "materialRank": "F",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "鋭い爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2034,
        "rank": 30,
        "materialRank": "E",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "魔獣の爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2035,
        "rank": 45,
        "materialRank": "D",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "飛竜の爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2036,
        "rank": 60,
        "materialRank": "C",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "地獄の爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2037,
        "rank": 80,
        "materialRank": "B",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "古竜の爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2038,
        "rank": 110,
        "materialRank": "A",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "神獣の爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2039,
        "rank": 150,
        "materialRank": "S",
        "materialType": "claw",
        "materialLabel": "爪",
        "name": "深淵竜の剛爪",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "爪系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2040,
        "rank": 5,
        "materialRank": "G",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "粗末な毛皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2041,
        "rank": 15,
        "materialRank": "F",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "獣の毛皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2042,
        "rank": 30,
        "materialRank": "E",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "魔獣の皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2043,
        "rank": 45,
        "materialRank": "D",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "霊獣の毛皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2044,
        "rank": 60,
        "materialRank": "C",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "地竜の鱗",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2045,
        "rank": 80,
        "materialRank": "B",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "幻獣の毛皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2046,
        "rank": 110,
        "materialRank": "A",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "神獣の聖皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2047,
        "rank": 150,
        "materialRank": "S",
        "materialType": "fur",
        "materialLabel": "毛皮",
        "name": "混沌獣の黒皮",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "毛皮系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2048,
        "rank": 5,
        "materialRank": "G",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "濁った粘液",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2049,
        "rank": 15,
        "materialRank": "F",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "青い薬液",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2050,
        "rank": 30,
        "materialRank": "E",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "魔獣の血",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2051,
        "rank": 45,
        "materialRank": "D",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "精霊の涙",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2052,
        "rank": 60,
        "materialRank": "C",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "水竜の血",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2053,
        "rank": 80,
        "materialRank": "B",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "星の涙",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2054,
        "rank": 110,
        "materialRank": "A",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "御神水",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2055,
        "rank": 150,
        "materialRank": "S",
        "materialType": "liquid",
        "materialLabel": "液体",
        "name": "深淵原液",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "液体系 Rank S 素材"
    },
    {
        "consumable": false,
        "id": 2056,
        "rank": 5,
        "materialRank": "G",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "謎の欠片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 10,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank G 素材"
    },
    {
        "consumable": false,
        "id": 2057,
        "rank": 15,
        "materialRank": "F",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "古びた部品",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 30,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank F 素材"
    },
    {
        "consumable": false,
        "id": 2058,
        "rank": 30,
        "materialRank": "E",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "異形の骨",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 90,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank E 素材"
    },
    {
        "consumable": false,
        "id": 2059,
        "rank": 45,
        "materialRank": "D",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "呪いのお札",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 250,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank D 素材"
    },
    {
        "consumable": false,
        "id": 2060,
        "rank": 60,
        "materialRank": "C",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "時空の砂",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 700,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank C 素材"
    },
    {
        "consumable": false,
        "id": 2061,
        "rank": 80,
        "materialRank": "B",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "世界の断片",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 1800,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank B 素材"
    },
    {
        "consumable": false,
        "id": 2062,
        "rank": 110,
        "materialRank": "A",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "神代遺物",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 5000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank A 素材"
    },
    {
        "consumable": false,
        "id": 2063,
        "rank": 150,
        "materialRank": "S",
        "materialType": "unknown",
        "materialLabel": "分類不能",
        "name": "終焉の黒玉",
        "type": "素材",
        "target": "なし",
        "battleUsable": false,
        "fieldUsable": false,
        "shopAvailable": false,
        "price": 0,
        "sellPrice": 15000,
        "icon": "assets/ui/menu-icons/item-material.png",
        "desc": "分類不能系 Rank S 素材"
    }
);

/*
 * Expanded battle consumables and ranked materials are authored explicitly
 * above. Keep item records in this file; runtime item generation is forbidden.
 */
(() => {
    'use strict';

    const items = window.ITEMS_DATA;
    const ICONS = Object.freeze({
        damage: 'assets/ui/menu-icons/item-attack.png',
        buff: 'assets/ui/menu-icons/item-buff.png',
        debuff: 'assets/ui/menu-icons/item-debuff.png',
        material: 'assets/ui/menu-icons/item-material.png'
    });
    const ELEMENTS = Object.freeze(['火', '水', '雷', '風', '光', '闇', '混沌']);
    const MATERIAL_GRADES = Object.freeze([
        { grade: 'G', rank: 5, sellPrice: 10 },
        { grade: 'F', rank: 15, sellPrice: 30 },
        { grade: 'E', rank: 30, sellPrice: 90 },
        { grade: 'D', rank: 45, sellPrice: 250 },
        { grade: 'C', rank: 60, sellPrice: 700 },
        { grade: 'B', rank: 80, sellPrice: 1800 },
        { grade: 'A', rank: 110, sellPrice: 5000 },
        { grade: 'S', rank: 150, sellPrice: 15000 }
    ]);
    const MATERIAL_CATEGORIES = Object.freeze([
        { key: 'metal', label: '金属' },
        { key: 'wood', label: '木材' },
        { key: 'magicStone', label: '魔石' },
        { key: 'feather', label: '羽' },
        { key: 'claw', label: '爪' },
        { key: 'fur', label: '毛皮' },
        { key: 'liquid', label: '液体' },
        { key: 'unknown', label: '分類不能' }
    ]);
    const TOOL_TYPE_ORDER = Object.freeze([
        '乗り物',
        '移動',
        'HP回復',
        'MP回復',
        '状態異常回復',
        '蘇生',
        '育成',
        '特性書',
        '攻撃道具',
        '強化道具',
        '弱体道具'
    ]);
    const getToolTypeSortRank = item => {
        if (!item) return TOOL_TYPE_ORDER.length + 1;
        if (Number(item.id) === 110 || item.name === 'スカイプリズム') return 1;
        const rank = TOOL_TYPE_ORDER.indexOf(String(item.type || ''));
        return rank >= 0 ? rank : TOOL_TYPE_ORDER.length;
    };
    const compareToolsByTypeAndId = (left, right) => {
        const typeDiff = getToolTypeSortRank(left) - getToolTypeSortRank(right);
        if (typeDiff !== 0) return typeDiff;
        const idDiff = Number(left?.id || 0) - Number(right?.id || 0);
        if (idDiff !== 0) return idDiff;
        return String(left?.name || '').localeCompare(String(right?.name || ''), 'ja');
    };
    const combatItems = items.filter(item => Number(item.id) >= 1000 && Number(item.id) < 2000);
    const pickAbyssChestItem = (floor, random = Math.random) => {
        const maxRank = Math.max(1, Number(floor) || 1);
        const eligible = items.filter(item =>
            Number(item.id) !== 99 &&
            item.type !== '貴重品' &&
            item.type !== '乗り物' &&
            item.type !== '移動' &&
            item.medalOnly !== true &&
            item.abyssDrop !== false &&
            Number(item.rank || 1) <= maxRank
        );
        const materials = eligible.filter(item => item.type === '素材');
        const usable = eligible.filter(item => item.type !== '素材');
        const preferMaterials = materials.length > 0 && random() < 0.35;
        const pool = preferMaterials ? materials : (usable.length ? usable : materials);
        return pool.length ? pool[Math.floor(random() * pool.length)] : null;
    };

    window.PRISMA_ITEM_CATALOG = Object.freeze({
        icons: ICONS,
        elements: ELEMENTS,
        materialGrades: MATERIAL_GRADES,
        materialCategories: MATERIAL_CATEGORIES,
        toolTypeOrder: TOOL_TYPE_ORDER,
        getToolTypeSortRank,
        compareToolsByTypeAndId,
        combatItems,
        pickAbyssChestItem,
        getMaterialItemId: (categoryIndex, gradeIndex) => 2000 + categoryIndex * 8 + gradeIndex,
        getMaterialGradeIndexForRank: rank => {
            const value = Math.max(1, Number(rank) || 1);
            if (value <= 10) return 0;
            if (value <= 25) return 1;
            if (value <= 45) return 2;
            if (value <= 65) return 3;
            if (value <= 85) return 4;
            if (value <= 110) return 5;
            if (value <= 150) return 6;
            return 7;
        }
    });
})();
