/* skills.js - skill IDs reorganized by category; generated 2026-06-21 */
/*
 * 任意: 各スキルへ battleFx を追加すると、polish.js の自動判定より優先して戦闘エフェクトを指定できます。
 *   "battleFx": "meteor"
 *   "battleFx": { "screen": "meteor", "hit": "spell-fire" }
 *   "battleFx": "assets/effect/fx-meteor-ai.png"
 * 未指定の場合は従来通り、type / elm / name / desc などから自動判定します。
 */
window.SKILLS_DATA = [
    { "id": 1, "name": "こうげき",
      "type": "通常攻撃", "target": "単体", "mp": 0, "rate": 1, "hitRate": 100, "critRate": 0, "count": 1, "base": 0, "desc": "通常攻撃" },
    { "id": 2, "name": "ぼうぎょ",
      "type": "特殊", "target": "自分", "mp": 0, "rate": 0, "count": 0, "base": 20, "desc": "ダメージ軽減" },
    { "id": 3, "name": "こうげき",
      "type": "物理", "target": "単体", "mp": 1, "rate": 0.8, "count": 2, "base": 0, "desc": "2回攻撃", "drain": true },
    { "id": 9, "name": "逃げる",
      "type": "特殊", "target": "自分", "mp": 0, "rate": 0, "count": 0, "base": 20, "desc": "戦闘から離脱" },
    { "id": 100, "name": "メタル斬り",
      "type": "物理", "target": "単体", "mp": 2, "rate": 0, "count": 1, "base": 1, "desc": "メタルに固定ダメージ", "fix": true },
    { "id": 101, "name": "疾風突き",
      "type": "物理", "target": "単体", "mp": 2, "rate": 0.5, "count": 1, "base": 0, "desc": "疾風の如き速さの一撃", "priority": 2 },
    { "id": 102, "name": "はやぶさ斬り",
      "type": "物理", "target": "単体", "mp": 2, "rate": 0.6, "count": 2, "base": 2, "desc": "2回攻撃" },
    { "id": 103, "name": "ウイングアッパー",
      "type": "物理", "target": "単体", "mp": 2, "rate": 0.6, "count": 2, "base": 6, "elm": "風", "desc": "風の拳" },
    { "id": 104, "name": "火炎斬り",
      "type": "物理", "target": "単体", "mp": 2, "rate": 1.1, "count": 1, "base": 6, "elm": "火", "desc": "炎の剣技" },
    { "id": 105, "name": "氷結斬り",
      "type": "物理", "target": "単体", "mp": 2, "rate": 1.1, "count": 1, "base": 6, "elm": "水", "desc": "氷の剣技" },
    { "id": 106, "name": "雷鳴突き",
      "type": "物理", "target": "単体", "mp": 2, "rate": 1.1, "count": 1, "base": 6, "elm": "雷", "desc": "雷の槍技" },
    { "id": 107, "name": "兜割り",
      "type": "物理", "target": "単体", "mp": 4, "rate": 0.9, "count": 1, "base": 6, "desc": "敵の守備を下げる", "SuccessRate": 100, "turn": 5, "debuff": {"def": 0.8} },
    { "id": 108, "name": "ミラクルソード",
      "type": "物理", "target": "単体", "mp": 3, "rate": 0.8, "count": 1, "base": 5, "desc": "奇跡の剣技・HP回復", "drain": true },
    { "id": 109, "name": "ブラッドソード",
      "type": "物理", "target": "単体", "mp": 3, "rate": 1.2, "count": 1, "base": 7, "elm": "混沌", "desc": "HP吸収", "drain": true },
    { "id": 110, "name": "ヴァイパーファング",
      "type": "物理", "target": "単体", "mp": 4, "rate": 0.7, "count": 1, "base": 1, "desc": "どく攻撃", "SuccessRate": 90, "HitRate": 100, "Poison": true },
    { "id": 111, "name": "せいけん突き",
      "type": "物理", "target": "単体", "mp": 7, "rate": 1.4, "count": 1, "base": 5, "desc": "力強い一撃" },
    { "id": 112, "name": "魔人斬り",
      "type": "物理", "target": "単体", "mp": 7, "rate": 1.5, "count": 1, "base": 0, "desc": "当たる確率は低いが、防御無視の会心攻撃", "HitRate": 30, "IgnoreDefense": true },
    { "id": 113, "name": "渾身斬り",
      "type": "物理", "target": "単体", "mp": 10, "rate": 1.5, "count": 1, "base": 18, "desc": "渾身の一撃" },
    { "id": 114, "name": "暗黒剣",
      "type": "物理", "target": "単体", "mp": 12, "rate": 1.4, "count": 1, "base": 19, "elm": "闇", "desc": "闇の剣技" },
    { "id": 115, "name": "フォースブレイク",
      "type": "物理", "target": "単体", "mp": 15, "rate": 1.0, "count": 1, "base": 0, "desc": "敵の全属性耐性を激減させる", "SuccessRate": 190, "turn": 2, "debuff": {"elmResDown": 100} },
    { "id": 116, "name": "マジックアロー",
      "type": "物理", "target": "単体", "mp": 4, "rate": 0.9, "count": 1, "base": 6, "desc": "相手の魔力を下げる一撃", "SuccessRate": 90, "HitRate": 100, "turn": 5, "debuff": {"mag": 0.7} },
    { "id": 117, "name": "やいばくだき",
      "type": "物理", "target": "単体", "mp": 4, "rate": 0.9, "count": 1, "base": 6, "desc": "相手の攻撃力を下げる一撃", "SuccessRate": 90, "HitRate": 100, "turn": 5, "debuff": {"atk": 0.7} },
    { "id": 118, "name": "サンダーボルト",
      "type": "物理", "target": "単体", "mp": 15, "rate": 1.2, "count": 1, "base": 15, "elm": "雷", "desc": "敵を感電させる強力な一撃", "SuccessRate": 70, "HitRate": 100, "Shock": true },
    { "id": 119, "name": "ぶんまわし",
      "type": "物理", "target": "全体", "mp": 8, "rate": 0.6, "count": 1, "base": 4, "desc": "全体物理攻撃" },
    { "id": 120, "name": "さみだれ斬り",
      "type": "物理", "target": "全体", "mp": 8, "rate": 0.8, "count": 1, "base": 6, "desc": "全体物理攻撃" },
    { "id": 121, "name": "さみだれ突き",
      "type": "物理", "target": "ランダム", "mp": 8, "rate": 0.4, "count": 4, "base": 1, "desc": "4回攻撃" },
    { "id": 122, "name": "氷結乱撃",
      "type": "物理", "target": "単体", "mp": 10, "rate": 0.4, "count": 4, "base": 1, "elm": "水", "desc": "氷の4回攻撃" },
    { "id": 123, "name": "ばくれつけん",
      "type": "物理", "target": "ランダム", "mp": 14, "rate": 0.6, "count": 4, "base": 1, "desc": "4回攻撃" },
    { "id": 124, "name": "さみだれ剣",
      "type": "物理", "target": "ランダム", "mp": 17, "rate": 0.7, "count": 4, "base": 4, "desc": "4回斬撃" },
    { "id": 125, "name": "キラージャグリング",
      "type": "物理", "target": "ランダム", "mp": 18, "rate": 0.4, "count": 6, "base": 4, "desc": "6回ランダム攻撃" },
    { "id": 126, "name": "ギガスラッシュ",
      "type": "物理", "target": "全体", "mp": 20, "rate": 1.1, "count": 1, "base": 20, "elm": "光", "desc": "光の剣技" },
    { "id": 127, "name": "しんくうは",
      "type": "物理", "target": "全体", "mp": 20, "rate": 0.5, "count": 2, "base": 6, "elm": "風", "desc": "敵全体に真空の刃" },
    { "id": 128, "name": "狼牙突き",
      "type": "物理", "target": "全体", "mp": 15, "rate": 0.8, "count": 1, "base": 12, "desc": "全体物理攻撃" },
    { "id": 129, "name": "オノむそう",
      "type": "物理", "target": "全体", "mp": 18, "rate": 1.0, "count": 1, "base": 20, "desc": "全体物理攻撃" },
    { "id": 130, "name": "デュアルカッター",
      "type": "物理", "target": "全体", "mp": 22, "rate": 0.6, "count": 2, "base": 24, "desc": "全体物理攻撃2連" },
    { "id": 131, "name": "タイガークロー",
      "type": "物理", "target": "単体", "mp": 15, "rate": 0.8, "count": 3, "base": 15, "desc": "強力な爪の3回攻撃" },
    { "id": 132, "name": "超はやぶさ斬り",
      "type": "物理", "target": "単体", "mp": 22, "rate": 0.7, "count": 4, "base": 4, "desc": "超高速の4連撃" },
    { "id": 133, "name": "不死鳥天舞",
      "type": "物理", "target": "単体", "mp": 28, "rate": 0.7, "count": 4, "base": 8, "desc": "再生を伴う4連撃", "drain": true },
    { "id": 134, "name": "九龍連斬",
      "type": "物理", "target": "単体", "mp": 35, "rate": 0.4, "count": 9, "base": 1, "desc": "9頭の龍の如き連撃" },
    { "id": 135, "name": "天下無双",
      "type": "物理", "target": "単体", "mp": 38, "rate": 0.6, "count": 6, "base": 10, "desc": "怒涛の6連撃" },
    { "id": 136, "name": "蒼天魔斬",
      "type": "物理", "target": "単体", "mp": 15, "rate": 1.5, "count": 1, "base": 20, "desc": "相手をひるませる強力な一撃", "SuccessRate": 90, "HitRate": 100, "turn": 1, "Fear": true },
    { "id": 137, "name": "黒の斬撃",
      "type": "物理", "target": "全体", "mp": 20, "rate": 1.1, "count": 1, "base": 24, "elm": "闇", "desc": "闇属性全体物理攻撃" },
    { "id": 138, "name": "ギガスロー",
      "type": "物理", "target": "全体", "mp": 20, "rate": 1.1, "count": 1, "base": 24, "elm": "雷", "desc": "雷属性全体物理攻撃" },
    { "id": 139, "name": "絶対零刀",
      "type": "物理", "target": "全体", "mp": 20, "rate": 1.1, "count": 1, "base": 24, "elm": "水", "desc": "氷属性全体物理攻撃" },
    { "id": 140, "name": "紫電一閃",
      "type": "物理", "target": "全体", "mp": 35, "rate": 1.5, "count": 1, "base": 40, "elm": "闇", "desc": "光速で放つ闇属性全体物理攻撃", "priority": 1 },
    { "id": 141, "name": "紅蓮剣舞",
      "type": "物理", "target": "全体", "mp": 40, "rate": 0.8, "count": 2, "base": 24, "elm": "火", "desc": "火属性全体物理攻撃2連" },
    { "id": 142, "name": "超さみだれ突き",
      "type": "物理", "target": "ランダム", "mp": 32, "rate": 0.8, "count": 4, "base": 6, "desc": "強力なランダム4回攻撃" },
    { "id": 143, "name": "鉄甲斬",
      "type": "物理", "target": "単体", "mp": 34, "rate": 1.5, "count": 1, "base": 40, "desc": "相手の守備力と素早さを下げる一撃", "SuccessRate": 100, "turn": 3, "debuff": {"def": 0.7, "spd": 0.7} },
    { "id": 144, "name": "真やいばくだき",
      "type": "物理", "target": "単体", "mp": 34, "rate": 1.5, "count": 1, "base": 40, "desc": "相手の攻撃力と魔力を大きく下げる一撃", "SuccessRate": 100, "turn": 3, "debuff": {"atk": 0.3, "mag": 0.3} },
    { "id": 145, "name": "天魔旋風脚",
      "type": "物理", "target": "全体", "mp": 37, "rate": 0.9, "count": 2, "base": 40, "desc": "全体物理攻撃2連" },
    { "id": 146, "name": "シャイニングボウ",
      "type": "物理", "target": "ランダム", "mp": 35, "rate": 0.6, "count": 6, "base": 17, "elm": "光", "desc": "光のランダム6回攻撃" },
    { "id": 147, "name": "ゴッドジャグリング",
      "type": "物理", "target": "ランダム", "mp": 50, "rate": 0.5, "count": 8, "base": 3, "desc": "攻撃力をさげることがある8回ランダム攻撃", "SuccessRate": 70, "debuff": {"atk": 0.7} },
    { "id": 148, "name": "邪神の爪",
      "type": "物理", "target": "単体", "mp": 66, "rate": 0.8, "count": 3, "base": 50, "SuccessRate": 100, "turn": 10, "Poison": true, "desc": "邪神の３連続攻撃" },
    { "id": 149, "name": "魔人の絶技",
      "type": "物理", "target": "単体", "mp": 66, "rate": 0.7, "count": 6, "base": 5, "desc": "魔人のごとき6連続攻撃" },
    { "id": 150, "name": "八刀一閃",
      "type": "物理", "target": "単体", "mp": 88, "rate": 0.6, "count": 8, "base": 1, "desc": "誰よりも速く八つの刃で切り刻む", "priority": 4 },
    { "id": 151, "name": "大魔人斬り",
      "type": "物理", "target": "単体", "mp": 20, "rate": 2.5, "count": 1, "base": 0, "desc": "防御無視の強烈な会心攻撃", "HitRate": 70, "IgnoreDefense": true },
    { "id": 152, "name": "テールスイング",
      "type": "物理", "target": "全体", "mp": 99, "rate": 1.4, "count": 2, "base": 100, "desc": "強烈な尻尾攻撃2連" },
    { "id": 153, "name": "紅蓮連撃",
      "type": "物理", "target": "単体", "mp": 50, "rate": 0.65, "count": 6, "base": 20, "elm": "火", "desc": "敵単体に6連続の炎属性物理ダメージ" },
    { "id": 154, "name": "ライガークラッシュ",
      "type": "物理", "target": "単体", "mp": 70, "rate": 0.8, "count": 5, "base": 35, "desc": "強力な爪の5回攻撃" },
    { "id": 155, "name": "ギガブレイク",
      "type": "物理", "target": "全体", "mp": 45, "rate": 1.7, "count": 1, "base": 50, "elm": "雷", "desc": "伝説の剣技" },
    { "id": 156, "name": "ゴッドハンド",
      "type": "物理", "target": "単体", "mp": 38, "rate": 3.2, "count": 1, "base": 100, "elm": "光", "desc": "神の拳" },
    { "id": 157, "name": "ラグナブレード",
      "type": "物理", "target": "単体", "mp": 50, "rate": 3.4, "count": 1, "base": 200, "elm": "混沌", "desc": "守備力を大きく下げる神を切り裂く混沌の一撃", "turn": 5, "debuff": {"def": 0.5} },
    { "id": 158, "name": "ギガクロスブレイク",
      "type": "物理", "target": "単体", "mp": 75, "rate": 2.1, "count": 2, "base": 50, "elm": "雷", "desc": "伝説の雷の2連撃" },
    { "id": 159, "name": "グランドクロス",
      "type": "物理", "target": "全体", "mp": 70, "rate": 1.0, "count": 2, "base": 100, "elm": "風", "desc": "十字に切り裂く2連撃" },
    { "id": 160, "name": "グランドネビュラ",
      "type": "物理", "target": "全体", "mp": 60, "rate": 1.8, "count": 1, "base": 150, "elm": "光", "desc": "敵全体に聖なる光の一撃" },
    { "id": 161, "name": "疾風迅雷",
      "type": "物理", "target": "全体", "mp": 55, "rate": 0.9, "count": 2, "base": 0, "desc": "神速で敵全体を薙ぎ払う", "priority": 5 },
    { "id": 162, "name": "アルテマソード",
      "type": "物理", "target": "単体", "mp": 99, "rate": 3.3, "count": 1, "base": 42, "desc": "防御を無視する究極の剣技", "SuccessRate": 100, "IgnoreDefense": true },
    { "id": 163, "name": "ストックブレイク",
      "type": "物理", "target": "全体", "mp": 99, "rate": 3.0, "count": 1, "base": 300, "desc": "敵全体を打ち砕く必殺の一撃" },
    { "id": 164, "name": "ショック",
      "type": "物理", "target": "単体", "mp": 99, "rate": 4.0, "count": 1, "base": 400, "elm": "雷", "desc": "剣に収束させた雷を放出し敵を討ち滅ぼす" },
    { "id": 165, "name": "クライムハザード",
      "type": "物理", "target": "全体", "mp": 199, "rate": 4.5, "count": 1, "base": 500, "desc": "敵全体を打ち砕く極限の聖剣技" },
    { "id": 166, "name": "ラグナロク",
      "type": "物理", "target": "ランダム", "mp": 99, "rate": 0.9, "count": 5, "base": 66, "elm": "闇", "desc": "終焉の5連撃" },
    { "id": 167, "name": "王者の一閃",
      "type": "物理", "target": "単体", "mp": 99, "rate": 3.5, "count": 1, "base": 0, "desc": "王者の威光を纏った一撃", "priority": -1, "debuff": {"def": 0.5}, "IgnoreDefense": true, "SuccessRate": 100 },
    { "id": 168, "name": "プリズマエンド",
      "type": "物理", "target": "単体", "mp": 99, "rate": 3.4, "hitRate": 200, "isPerfect": true, "critRate": 100, "count": 1, "base": 41, "desc": "全てを断ち切る大魔王の右腕", "SuccessRate": 100, "IgnoreDefense": true, "buff_reset": true },

    { "id": 200, "name": "メラ",
      "type": "魔法", "target": "単体", "mp": 3, "rate": 1.1, "count": 1, "base": 6, "elm": "火", "desc": "小火球" },
    { "id": 201, "name": "ヒャド",
      "type": "魔法", "target": "単体", "mp": 4, "rate": 1.2, "count": 1, "base": 8, "elm": "水", "desc": "氷の刃" },
    { "id": 202, "name": "バギ",
      "type": "魔法", "target": "全体", "mp": 4, "rate": 0.7, "count": 1, "base": 4, "elm": "風", "desc": "真空の刃" },
    { "id": 203, "name": "ドルマ",
      "type": "魔法", "target": "単体", "mp": 4, "rate": 1.2, "count": 1, "base": 8, "elm": "闇", "desc": "闇の弾" },
    { "id": 204, "name": "ギラ",
      "type": "魔法", "target": "全体", "mp": 5, "rate": 0.8, "count": 1, "base": 5, "elm": "火", "desc": "炎の閃光" },
    { "id": 205, "name": "イオ",
      "type": "魔法", "target": "全体", "mp": 7, "rate": 1, "count": 1, "base": 6, "elm": "光", "desc": "光の小爆発" },
    { "id": 206, "name": "ライデイン",
      "type": "魔法", "target": "単体", "mp": 13, "rate": 1.4, "count": 1, "base": 25, "elm": "雷", "desc": "落雷" },
    { "id": 207, "name": "メラミ",
      "type": "魔法", "target": "単体", "mp": 13, "rate": 1.4, "count": 1, "base": 25, "elm": "火", "desc": "中火球" },
    { "id": 208, "name": "ドルクマ",
      "type": "魔法", "target": "単体", "mp": 13, "rate": 1.4, "count": 1, "base": 25, "elm": "闇", "desc": "闇の中爆発" },
    { "id": 209, "name": "ベギラマ",
      "type": "魔法", "target": "全体", "mp": 15, "rate": 0.95, "count": 1, "base": 10, "elm": "火", "desc": "灼熱の帯" },
    { "id": 210, "name": "ヒャダルコ",
      "type": "魔法", "target": "全体", "mp": 15, "rate": 0.95, "count": 1, "base": 10, "elm": "水", "desc": "氷の波動" },
    { "id": 211, "name": "バギマ",
      "type": "魔法", "target": "全体", "mp": 13, "rate": 0.85, "count": 1, "base": 8, "elm": "風", "desc": "真空の嵐" },
    { "id": 212, "name": "イオラ",
      "type": "魔法", "target": "全体", "mp": 18, "rate": 1.15, "count": 1, "base": 7, "elm": "光", "desc": "中爆発" },
    { "id": 213, "name": "メラゾーマ",
      "type": "魔法", "target": "単体", "mp": 28, "rate": 1.8, "count": 1, "base": 40, "elm": "火", "desc": "大火球" },
    { "id": 214, "name": "ドルモーア",
      "type": "魔法", "target": "単体", "mp": 28, "rate": 1.8, "count": 1, "base": 40, "elm": "闇", "desc": "闇の爆発" },
    { "id": 215, "name": "バギクロス",
      "type": "魔法", "target": "全体", "mp": 34, "rate": 1.2, "count": 1, "base": 20, "elm": "風", "desc": "真空の大嵐" },
    { "id": 216, "name": "ベギラゴン",
      "type": "魔法", "target": "全体", "mp": 38, "rate": 1.4, "count": 1, "base": 25, "elm": "火", "desc": "灼熱の波動" },
    { "id": 217, "name": "マヒャド",
      "type": "魔法", "target": "全体", "mp": 38, "rate": 1.4, "count": 1, "base": 25, "elm": "水", "desc": "貫く氷塊" },
    { "id": 218, "name": "イオナズン",
      "type": "魔法", "target": "全体", "mp": 42, "rate": 1.5, "count": 1, "base": 30, "elm": "光", "desc": "大爆発" },
    { "id": 219, "name": "プチメテオ",
      "type": "魔法", "target": "ランダム", "mp": 55, "rate": 0.35, "count": 7, "base": 10, "elm": "火", "desc": "小隕石落とし" },
    { "id": 220, "name": "ジゴスパーク",
      "type": "魔法", "target": "全体", "mp": 66, "rate": 1.8, "count": 1, "base": 66, "elm": "混沌", "desc": "地獄の雷" },
    { "id": 221, "name": "マヒャデドス",
      "type": "魔法", "target": "全体", "mp": 57, "rate": 1.65, "count": 1, "base": 45, "elm": "水", "desc": "極大氷呪文" },
    { "id": 222, "name": "バギムーチョ",
      "type": "魔法", "target": "全体", "mp": 52, "rate": 1.55, "count": 1, "base": 40, "elm": "風", "desc": "極大風魔法" },
    { "id": 223, "name": "ギラグレイド",
      "type": "魔法", "target": "全体", "mp": 57, "rate": 1.65, "count": 1, "base": 45, "elm": "火", "desc": "極大炎魔法" },
    { "id": 224, "name": "メラガイアー",
      "type": "魔法", "target": "単体", "mp": 42, "rate": 2.3, "count": 1, "base": 70, "elm": "火", "desc": "極大火炎呪文" },
    { "id": 225, "name": "ドルマドン",
      "type": "魔法", "target": "単体", "mp": 42, "rate": 2.3, "count": 1, "base": 70, "elm": "闇", "desc": "極大闇魔法" },
    { "id": 226, "name": "ギガデイン",
      "type": "魔法", "target": "全体", "mp": 66, "rate": 1.8, "count": 1, "base": 60, "elm": "雷", "desc": "極大雷呪文" },
    { "id": 227, "name": "イオグランデ",
      "type": "魔法", "target": "全体", "mp": 66, "rate": 1.8, "count": 1, "base": 60, "elm": "光", "desc": "極大爆発" },
    { "id": 228, "name": "シャイニング",
      "type": "魔法", "target": "全体", "mp": 72, "rate": 1.9, "count": 1, "base": 20, "elm": "光", "desc": "敵全体を打ち滅ぼす聖なる光" },
    { "id": 229, "name": "凍てつく氷錐",
      "type": "魔法", "target": "単体", "mp": 42, "rate": 2.3, "count": 1, "base": 70, "elm": "水", "desc": "凍てつく極大魔法" },
    { "id": 230, "name": "裁きの雷霆",
      "type": "魔法", "target": "ランダム", "mp": 88, "rate": 0.5, "count": 4, "base": 20, "elm": "雷", "desc": "雷魔法超ダメージ5連・感電付与", "SuccessRate": 100, "turn": 3, "Shock": true },
    { "id": 231, "name": "メテオ",
      "type": "魔法", "target": "ランダム", "mp": 74, "rate": 0.5, "count": 7, "base": 20, "elm": "火", "desc": "隕石落とし" },
    { "id": 232, "name": "イオマータ",
      "type": "魔法", "target": "ランダム", "mp": 70, "rate": 0.35, "count": 9, "base": 5, "elm": "光", "desc": "失われた8連続の爆発呪文" },
    { "id": 233, "name": "神速メラガイアー",
      "type": "魔法", "target": "ランダム", "mp": 99, "rate": 1.2, "count": 3, "base": 30, "elm": "火", "desc": "失われた3連続の極大火炎" },
    { "id": 234, "name": "連続ドルマドン",
      "type": "魔法", "target": "ランダム", "mp": 99, "rate": 1.2, "count": 3, "base": 30, "elm": "闇", "desc": "失われた3連続の極大闇魔法" },
    { "id": 235, "name": "氷塊マヒャデドス",
      "type": "魔法", "target": "全体", "mp": 99, "rate": 1.0, "count": 2, "base": 40, "elm": "水", "desc": "失われた2連続の極大氷呪文" },
    { "id": 236, "name": "烈風バギムーチョ",
      "type": "魔法", "target": "全体", "mp": 99, "rate": 0.5, "count": 4, "base": 20, "elm": "風", "desc": "失われた4連続の極大風呪文" },
    { "id": 237, "name": "ジゴデイン",
      "type": "魔法", "target": "全体", "mp": 99, "rate": 2.0, "count": 1, "base": 100, "elm": "雷", "desc": "失われた極大雷呪文" },
    { "id": 238, "name": "ビッグバン",
      "type": "魔法", "target": "全体", "mp": 99, "rate": 2.2, "count": 1, "base": 150, "elm": "混沌", "desc": "天地を創造した混沌の光" },
    { "id": 239, "name": "ねんじボール",
      "type": "魔法", "target": "ランダム", "mp": 66, "rate": 0.5, "count": 5, "base": 18, "elm": "混沌", "desc": "混沌を秘めた球を複数生み出して投げつける" },
    { "id": 240, "name": "ルーンショット",
      "type": "魔法", "target": "単体", "mp": 50, "rate": 0.8, "count": 1, "base": 100, "desc": "無属性魔法・HP吸収", "drain": true },
    { "id": 241, "name": "ルーンストーム",
      "type": "魔法", "target": "ランダム", "mp": 99, "rate": 0.45, "count": 4, "base": 40, "desc": "無属性ランダム4回攻撃魔法・HP吸収", "drain": true },
    { "id": 242, "name": "アビスウォール",
      "type": "魔法", "target": "全体", "mp": 166, "rate": 2.8, "count": 1, "base": 150, "elm": "混沌", "desc": "厄災の壁" },
    { "id": 243, "name": "フェニックスフレア",
      "type": "魔法", "target": "単体", "mp": 166, "rate": 3.5, "count": 1, "base": 200, "elm": "火", "desc": "大魔王のメラゾーマ" },
    { "id": 244, "name": "創世の魔力",
      "type": "魔法", "target": "全体", "mp": 166, "rate": 2.0, "count": 1, "base": 100, "elm": "混沌", "desc": "世界を創り変える力", "SuccessRate": 70, "HitRate": 100, "turn": 4, "debuff": {"atk": 0.7, "def": 0.7, "mag": 0.7, "spd": 0.7, "mdef": 0.7} },
    { "id": 245, "name": "カオスショック",
      "type": "魔法", "target": "全体", "mp": 0, "rate": 4, "count": 1, "base": 10, "elm": "混沌", "desc": "全MPを消費し混沌の大爆発", "priority": -1 },
    { "id": 246, "name": "イルミナティブレイク",
      "type": "魔法", "target": "ランダム", "mp": 0, "rate": 2, "count": 3, "base": 10, "elm": "光", "desc": "全MPを消費しランダムに3回光属性の大ダメージ", "priority": -1 },
    { "id": 247, "name": "ジエンド",
      "type": "魔法", "target": "単体", "mp": 0, "rate": 7, "count": 1, "base": 10, "elm": "闇", "desc": "全MPを消費し敵一人に闇属性の超ダメージ", "priority": -1 },
    { "id": 248, "name": "ロストプリズマ",
      "type": "魔法", "target": "全体", "mp": 199, "rate": 0, "count": 1, "base": 999, "desc": "全体極大ダメージ", "priority": -1, "fix": true },
    { "id": 300, "name": "火炎の息",
      "type": "ブレス", "target": "全体", "mp": 7, "rate": 0.6, "count": 1, "base": 6, "elm": "火", "desc": "炎の息" },
    { "id": 301, "name": "こごえる吹雪",
      "type": "ブレス", "target": "全体", "mp": 12, "rate": 0.8, "count": 1, "base": 17, "elm": "水", "desc": "冷たい息" },
    { "id": 302, "name": "はげしい炎",
      "type": "ブレス", "target": "全体", "mp": 12, "rate": 0.8, "count": 1, "base": 21, "elm": "火", "desc": "激しい炎" },
    { "id": 303, "name": "暗黒のきり",
      "type": "ブレス", "target": "全体", "mp": 16, "rate": 0.95, "count": 1, "base": 17, "elm": "闇", "desc": "暗黒のきりをまき散らし全体闇ダメージ" },
    { "id": 304, "name": "いなずま",
      "type": "ブレス", "target": "全体", "mp": 16, "rate": 0.95, "count": 1, "base": 17, "elm": "雷", "desc": "稲妻を呼び出し全体雷ダメージ" },
    { "id": 305, "name": "かがやく息",
      "type": "ブレス", "target": "全体", "mp": 30, "rate": 1.3, "count": 1, "base": 44, "elm": "水", "desc": "極寒の息" },
    { "id": 306, "name": "しゃくねつ",
      "type": "ブレス", "target": "全体", "mp": 30, "rate": 1.3, "count": 1, "base": 44, "elm": "火", "desc": "灼熱の業火" },
    { "id": 307, "name": "絶対零度",
      "type": "ブレス", "target": "全体", "mp": 50, "rate": 1.6, "count": 1, "base": 66, "elm": "水", "desc": "全てを凍らす息" },
    { "id": 308, "name": "煉獄火炎",
      "type": "ブレス", "target": "全体", "mp": 50, "rate": 1.6, "count": 1, "base": 66, "elm": "混沌", "desc": "地獄の炎で全体混沌ダメージ" },
    { "id": 309, "name": "霜白の氷塊",
      "type": "ブレス", "target": "全体", "mp": 70, "rate": 1.8, "count": 1, "base": 88, "elm": "水", "debuff": {"mag": 0.7}, "desc": "全体水属性極大ダメージ＋魔力低下" },
    { "id": 310, "name": "紅蓮の炎",
      "type": "ブレス", "target": "全体", "mp": 70, "rate": 1.8, "count": 1, "base": 88, "elm": "火", "desc": "全体火属性極大ダメージ＋攻撃低下", "debuff": {"atk": 0.7} },
    { "id": 311, "name": "ウイングダイブ",
      "type": "ブレス", "target": "全体", "mp": 88, "rate": 1.1, "count": 2, "base": 66, "elm": "風", "desc": "風属性全体2回攻撃＋速度大幅減", "turn": 5, "debuff": {"spd": 0.3} },
    { "id": 312, "name": "シャイニングブレス",
      "type": "ブレス", "target": "全体", "mp": 99, "rate": 2.3, "count": 1, "base": 99, "elm": "光", "desc": "全体光属性極大ダメージ＋スキル封印", "SuccessRate": 50, "turn": 3, "SpellSeal": true, "SkillSeal": true, "HealSeal": true },
    { "id": 313, "name": "ダークネスブレス",
      "type": "ブレス", "target": "全体", "mp": 99, "rate": 2.3, "count": 1, "base": 99, "elm": "闇", "desc": "全体闇属性極大ダメージ＋全属性耐性ダウン", "SuccessRate": 50, "turn": 3, "debuff": {"elmResDown": 50} },
    { "id": 314, "name": "闇の流星",
      "type": "ブレス", "target": "ランダム", "mp": 99, "rate": 0.66, "count": 6, "base": 66, "elm": "闇", "desc": "数多の流星がランダムに降り注ぎ闇の大ダメージ" },
    { "id": 315, "name": "魔触",
      "type": "ブレス", "target": "全体", "mp": 99, "rate": 0.5, "count": 1, "base": 66, "elm": "混沌", "desc": "闇の根源より漏れ出る災禍を操り異常をまき散らす", "HitRate": 100, "SuccessRate": 30, "turn": 2, "ToxicPoison": true, "Fear": false, "SpellSeal": true, "SkillSeal": true, "HealSeal": true },
    { "id": 400, "name": "ホイミ",
      "type": "回復", "target": "単体", "mp": 2, "rate": 0.6, "count": 1, "base": 20, "desc": "小回復" },
    { "id": 401, "name": "ベホイミ",
      "type": "回復", "target": "単体", "mp": 5, "rate": 1.0, "count": 1, "base": 50, "desc": "中回復" },
    { "id": 402, "name": "めいそう",
      "type": "回復", "target": "自分", "mp": 11, "ratio": 0.5, "rate": 0, "count": 1, "base": 0, "desc": "HPを50%回復" },
    { "id": 403, "name": "無念無想",
      "type": "MP回復", "target": "自分", "mp": 0, "ratio": 0.5, "rate": 0, "count": 1, "base": 0, "desc": "MPを50%回復" },
    { "id": 404, "name": "エリアヒール",
      "type": "回復", "target": "全体", "mp": 17, "rate": 0.6, "count": 1, "base": 25, "desc": "全体回復" },
    { "id": 405, "name": "キアリク",
      "type": "特殊", "target": "全体", "mp": 15, "rate": 0, "count": 1, "base": 0, "desc": "味方全体の状態異常を治療する", "CureAilments": true },
    { "id": 406, "name": "不撓不屈",
      "type": "特殊", "target": "自分", "mp": 8, "rate": 0, "count": 1, "base": 0, "desc": "自身の弱体・状態異常を解除", "CureAilments": true, "debuff_reset": true },
    { "id": 407, "name": "ザオラル",
      "type": "蘇生", "target": "単体", "mp": 10, "rate": 0.5, "count": 1, "base": 20, "desc": "50%蘇生", "SuccessRate": 50 },
    { "id": 408, "name": "ひかりのはどう",
      "type": "特殊", "target": "全体", "mp": 35, "rate": 0, "count": 1, "base": 0, "desc": "味方全体の状態異常と弱体を解除", "CureAilments": true, "debuff_reset": true },
    { "id": 409, "name": "いやしのあめ",
      "type": "特殊", "target": "全体", "mp": 26, "rate": 0, "count": 1, "base": 0, "desc": "毎ターンHP回復", "turn": 5, "HPRegen": 0.1 },
    { "id": 410, "name": "まりょくのかぜ",
      "type": "特殊", "target": "全体", "mp": 15, "rate": 0, "count": 1, "base": 0, "desc": "毎ターンMP回復", "turn": 5, "MPRegen": 0.05 },
    { "id": 411, "name": "ファストエイド",
      "type": "回復", "target": "単体", "mp": 10, "rate": 0.6, "count": 1, "base": 20, "desc": "使い手の少ない最速の回復呪文", "priority": 20 },
    { "id": 412, "name": "ベホイム",
      "type": "回復", "target": "単体", "mp": 20, "rate": 1.5, "count": 1, "base": 250, "desc": "超回復", "fix": false },
    { "id": 413, "name": "ベホマラー",
      "type": "回復", "target": "全体", "mp": 35, "rate": 1.0, "count": 1, "base": 120, "desc": "全体超回復", "fix": false },
    { "id": 414, "name": "ザオリク",
      "type": "蘇生", "target": "単体", "mp": 20, "rate": 1.0, "count": 1, "base": 50, "desc": "100%蘇生", "SuccessRate": 100 },
    { "id": 415, "name": "不死鳥の灰",
      "type": "回復", "target": "自分", "mp": 66, "rate": 1.0, "count": 1, "base": 500, "desc": "全てを受け止めて生還する不死鳥", "priority": -20, "CureAilments": true, "debuff_reset": true },
    { "id": 416, "name": "世界樹の陽光",
      "type": "回復", "target": "全体", "mp": 66, "rate": 1.5, "count": 1, "base": 300, "desc": "味方全体のHPを超回復し、状態異常を治療する", "CureAilments": true, "debuff_reset": true },
    { "id": 417, "name": "ベホマ",
      "type": "回復", "target": "単体", "mp": 40, "rate": 0, "count": 1, "base": 99999, "desc": "完全回復", "fix": true },
    { "id": 418, "name": "ベホマズン",
      "type": "回復", "target": "全体", "mp": 99, "rate": 0, "count": 1, "base": 99999, "desc": "全体完全回復", "fix": true },
    { "id": 419, "name": "ザオリーマ",
      "type": "蘇生", "target": "全体", "mp": 99, "rate": 1, "count": 1, "base": 50, "desc": "味方全員を完全蘇生", "SuccessRate": 100 },
    { "id": 500, "name": "バイキルト",
      "type": "強化", "target": "単体", "mp": 5, "rate": 0, "count": 1, "base": 20, "desc": "攻撃力アップ", "turn": 5, "buff": {"atk": 1.5} },
    { "id": 501, "name": "スクルト",
      "type": "強化", "target": "全体", "mp": 7, "rate": 0, "count": 1, "base": 20, "desc": "守備力アップ", "turn": 5, "buff": {"def": 1.5} },
    { "id": 502, "name": "ピオリム",
      "type": "強化", "target": "全体", "mp": 7, "rate": 0, "count": 1, "base": 20, "desc": "全体の素早さアップ", "turn": 5, "buff": {"spd": 1.3} },
    { "id": 503, "name": "マジックバリア",
      "type": "強化", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "全体の全属性耐性アップ", "turn": 5, "buff": {"elmResUp": 30} },
    { "id": 504, "name": "弓聖の守り星",
      "type": "強化", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "味方全体の状態異常耐性アップ", "turn": 3, "buff": {"resists_Poison": 80, "resists_Shock": 80, "resists_Fear": 80, "resists_Seal": 80, "resists_Debuff": 80, "resists_InstantDeath": 80} },
    { "id": 505, "name": "キラキラポーン",
      "type": "強化", "target": "単体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "状態異常をすべて治療し、さらに耐性を最大にする", "turn": 10, "buff": {"resists_Poison": 200, "resists_Shock": 200, "resists_Fear": 200, "resists_Seal": 200, "resists_Debuff": 200, "resists_InstantDeath": 200} },
    { "id": 506, "name": "魔力覚醒",
      "type": "強化", "target": "自分", "mp": 20, "rate": 0, "count": 1, "base": 0, "desc": "魔力超上昇", "turn": 4, "buff": {"mag": 2} },
    { "id": 507, "name": "臥薪嘗胆",
      "type": "強化", "target": "自分", "mp": 20, "rate": 0, "count": 0, "base": 0, "desc": "精神を集中し攻撃力を大幅に上げるが、防御力が下がる", "buff": {"atk": 2.5}, "turn": 4, "debuff": {"def": 0.7} },
    { "id": 508, "name": "たたかいのドラム",
      "type": "強化", "target": "全体", "mp": 45, "rate": 0, "count": 1, "base": 0, "desc": "味方全体の全ステータスUP", "turn": 5, "buff": {"atk": 1.2, "def": 1.2, "spd": 1.2, "mag": 1.2, "mdef": 1.2} },
    { "id": 509, "name": "パラディンガード",
      "type": "強化", "target": "全体", "mp": 60, "rate": 0, "count": 1, "base": 0, "desc": "味方全体の全属性耐性超上昇", "turn": 2, "buff": {"elmResUp": 80} },
    { "id": 510, "name": "やみのころも",
      "type": "強化", "target": "自分", "mp": 66, "rate": 0, "count": 1, "base": 0, "desc": "自身の全ステータス・属性耐性・状態異常耐性UP", "turn": 5, "buff": {"atk": 1.5, "def": 1.5, "spd": 1.5, "mag": 1.5, "mdef": 1.5, "elmResUp": 50, "resists_Poison": 100, "resists_Shock": 100, "resists_Fear": 100, "resists_Seal": 100, "resists_Debuff": 100, "resists_InstantDeath": 100}, "CureAilments": true, "debuff_reset": true },
    { "id": 600, "name": "ルカニ",
      "type": "弱体", "target": "単体", "mp": 5, "rate": 0, "count": 1, "base": 20, "desc": "敵の守備ダウン", "SuccessRate": 70, "turn": 5, "debuff": {"def": 0.7} },
    { "id": 601, "name": "ボミオス",
      "type": "弱体", "target": "全体", "mp": 7, "rate": 0, "count": 1, "base": 20, "desc": "敵の素早さダウン", "SuccessRate": 70, "turn": 5, "debuff": {"spd": 0.7} },
    { "id": 602, "name": "ルカナン",
      "type": "弱体", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 20, "desc": "敵の守備ダウン", "SuccessRate": 70, "turn": 5, "debuff": {"def": 0.7} },
    { "id": 603, "name": "ヘナトス",
      "type": "弱体", "target": "単体", "mp": 5, "rate": 0, "count": 1, "base": 20, "desc": "敵の攻撃ダウン", "SuccessRate": 70, "turn": 5, "debuff": {"atk": 0.7} },
    { "id": 604, "name": "やみのはどう",
      "type": "弱体", "target": "全体", "mp": 45, "rate": 0, "count": 1, "base": 20, "desc": "全能力ダウン", "SuccessRate": 80, "turn": 4, "debuff": {"atk": 0.7, "def": 0.7, "mag": 0.7, "spd": 0.7, "mdef": 0.7} },
    { "id": 700, "name": "どくのいき",
      "type": "特殊", "target": "全体", "mp": 3, "rate": 0, "count": 1, "base": 0, "desc": "どくのいき", "SuccessRate": 80, "turn": 10, "Poison": true },
    { "id": 701, "name": "おたけび",
      "type": "特殊", "target": "全体", "mp": 4, "rate": 0, "count": 1, "base": 0, "desc": "相手をひるませる叫び", "SuccessRate": 80, "turn": 1, "Fear": true },
    { "id": 702, "name": "もうどくのいき",
      "type": "特殊", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "もうどくのいき", "SuccessRate": 80, "turn": 10, "ToxicPoison": true },
    { "id": 703, "name": "マホトーン",
      "type": "特殊", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "魔法と回復を封印する", "SuccessRate": 80, "turn": 5, "SpellSeal": true, "HealSeal": true },
    { "id": 704, "name": "スキルブレイク",
      "type": "特殊", "target": "全体", "mp": 10, "rate": 0, "count": 1, "base": 0, "desc": "特技を封印する", "SuccessRate": 80, "HitRate": 100, "turn": 5, "SkillSeal": true },
    { "id": 705, "name": "いてつくはどう",
      "type": "特殊", "target": "全体", "mp": 15, "rate": 0, "count": 1, "base": 0, "desc": "敵全体の強化を解除", "buff_reset": true },
    { "id": 706, "name": "ザキ",
      "type": "特殊", "target": "単体", "mp": 16, "rate": 0, "count": 1, "base": 0, "desc": "即死呪文", "SuccessRate": 30, "PercentDamage": 1 },
    { "id": 707, "name": "死の踊り",
      "type": "特殊", "target": "全体", "mp": 28, "rate": 0, "count": 1, "base": 0, "desc": "敵全体を低確率で死にいざなう魔の踊り", "SuccessRate": 20, "PercentDamage": 1 },
    { "id": 708, "name": "ザラキ",
      "type": "特殊", "target": "全体", "mp": 28, "rate": 0, "count": 1, "base": 0, "desc": "即死呪文", "SuccessRate": 30, "PercentDamage": 1 },
    { "id": 709, "name": "ザラキーマ",
      "type": "特殊", "target": "全体", "mp": 66, "rate": 0, "count": 1, "base": 0, "desc": "高確率の即死呪文", "SuccessRate": 50, "PercentDamage": 1 },
    { "id": 710, "name": "地獄の舞い",
      "type": "特殊", "target": "ランダム", "mp": 66, "rate": 0, "count": 3, "base": 0, "desc": "敵を無差別に死にいざなう地獄の舞い", "SuccessRate": 70, "PercentDamage": 1 },
    { "id": 711, "name": "はげしいおたけび",
      "type": "特殊", "target": "全体", "mp": 34, "rate": 0, "count": 1, "base": 0, "desc": "恐ろしいおたけび", "HitRate": 100, "SuccessRate": 80, "PercentDamage": 0.2, "turn": 1, "Fear": true },
    { "id": 712, "name": "おぞましいおたけび",
      "type": "特殊", "target": "全体", "mp": 47, "rate": 0, "count": 1, "base": 0, "desc": "心まで凍り付く恐ろしいおたけび", "SuccessRate": 70, "HitRate": 100, "PercentDamage": 0.5, "turn": 1, "Fear": true },
    { "id": 713, "name": "死グモのトゲ",
      "type": "特殊", "target": "全体", "mp": 45, "rate": 0, "count": 1, "base": 0, "HitRate": 100, "SuccessRate": 90, "PercentDamage": 0.6 },
    { "id": 714, "name": "竜の咆哮",
      "type": "特殊", "target": "全体", "mp": 50, "rate": 1, "count": 1, "base": 0, "priority": -20, "SuccessRate": 190, "PercentDamage": 0.1, "turn": 1, "buff_reset": true, "Fear": true, "desc": "激しく咆哮し敵全体を怯ませていい効果を消し去る" },
    { "id": 715, "name": "心ない天使",
      "type": "特殊", "target": "単体", "mp": 99, "rate": 0, "count": 1, "base": 0, "desc": "無慈悲な一撃", "priority": -5, "SuccessRate": 100, "PercentDamage": 0.99 }
];
