/* skills_revised_final_v2.js - revised elemental/healing naming systems; generated 2026-07-30
 * Naming principles:
 * - Physical skills: practical names at lower tiers; school, legend, and mythic names at higher tiers.
 * - Attack magic: shared elemental roots and consistent tier suffixes.
 * - Fire magic: IGNA family for single-target spells; FLAMA family for all-target spells.
 * - Healing magic: LUNA progression. Revival magic: clear RIZA progression.
 * - IDs, costs, power, targeting, attributes, descriptions, and effect flags are unchanged.
 */
window.SKILLS_DATA = [
  {
    "id": 1,
    "name": "こうげき",
    "type": "通常攻撃",
    "target": "単体",
    "mp": 0,
    "rate": 1,
    "hitRate": 100,
    "critRate": 0,
    "count": 1,
    "base": 0,
    "desc": "通常攻撃"
  },
  {
    "id": 2,
    "name": "ぼうぎょ",
    "type": "特殊",
    "target": "自分",
    "mp": 0,
    "rate": 0,
    "count": 0,
    "base": 20,
    "desc": "ダメージ軽減"
  },
  {
    "id": 3,
    "name": "こうげき",
    "type": "物理",
    "target": "単体",
    "mp": 1,
    "rate": 0.8,
    "count": 2,
    "base": 0,
    "desc": "2回攻撃",
    "drain": true
  },
  {
    "id": 9,
    "name": "逃げる",
    "type": "特殊",
    "target": "自分",
    "mp": 0,
    "rate": 0,
    "count": 0,
    "base": 20,
    "desc": "戦闘から離脱"
  },
  {
    "id": 100,
    "name": "鋼穿ち",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 0,
    "count": 1,
    "base": 2,
    "desc": "硬質な敵を穿つ固定ダメージ攻撃",
    "fix": true
  },
  {
    "id": 101,
    "name": "先駆け",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 0.5,
    "count": 1,
    "base": 0,
    "desc": "誰よりも早く踏み込む先制の一撃",
    "priority": 2
  },
  {
    "id": 102,
    "name": "二段斬り",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 0.6,
    "count": 2,
    "base": 2,
    "desc": "2回攻撃"
  },
  {
    "id": 103,
    "name": "風切り拳",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 0.6,
    "count": 2,
    "base": 6,
    "elm": "風",
    "desc": "風の拳"
  },
  {
    "id": 104,
    "name": "焔斬り",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 1.1,
    "count": 1,
    "base": 6,
    "elm": "火",
    "desc": "炎の剣技"
  },
  {
    "id": 105,
    "name": "霜斬り",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 1.1,
    "count": 1,
    "base": 6,
    "elm": "水",
    "desc": "氷の剣技"
  },
  {
    "id": 106,
    "name": "雷突き",
    "type": "物理",
    "target": "単体",
    "mp": 2,
    "rate": 1.1,
    "count": 1,
    "base": 6,
    "elm": "雷",
    "desc": "雷の槍技"
  },
  {
    "id": 107,
    "name": "甲割り",
    "type": "物理",
    "target": "単体",
    "mp": 4,
    "rate": 0.9,
    "count": 1,
    "base": 6,
    "desc": "敵の守備を下げる",
    "SuccessRate": 100,
    "turn": 5,
    "debuff": {
      "def": 0.8
    }
  },
  {
    "id": 108,
    "name": "祈りの剣",
    "type": "物理",
    "target": "単体",
    "mp": 3,
    "rate": 0.8,
    "count": 1,
    "base": 5,
    "desc": "奇跡の剣技・HP回復",
    "drain": true
  },
  {
    "id": 109,
    "name": "血啜り",
    "type": "物理",
    "target": "単体",
    "mp": 3,
    "rate": 1.2,
    "count": 1,
    "base": 7,
    "elm": "混沌",
    "desc": "HP吸収",
    "drain": true
  },
  {
    "id": 110,
    "name": "毒牙",
    "type": "物理",
    "target": "単体",
    "mp": 4,
    "rate": 0.7,
    "count": 1,
    "base": 1,
    "desc": "どく攻撃",
    "SuccessRate": 90,
    "HitRate": 100,
    "Poison": true
  },
  {
    "id": 111,
    "name": "剛拳",
    "type": "物理",
    "target": "単体",
    "mp": 7,
    "rate": 1.4,
    "count": 1,
    "base": 5,
    "desc": "力強い一撃"
  },
  {
    "id": 112,
    "name": "羅刹斬り",
    "type": "物理",
    "target": "単体",
    "mp": 7,
    "rate": 1.5,
    "count": 1,
    "base": 0,
    "desc": "命中は不安定だが、防御を無視する会心の一刀",
    "HitRate": 30,
    "IgnoreDefense": true
  },
  {
    "id": 113,
    "name": "全霊斬り",
    "type": "物理",
    "target": "単体",
    "mp": 10,
    "rate": 1.5,
    "count": 1,
    "base": 18,
    "desc": "渾身の一撃"
  },
  {
    "id": 114,
    "name": "影葬",
    "type": "物理",
    "target": "単体",
    "mp": 12,
    "rate": 1.4,
    "count": 1,
    "base": 19,
    "elm": "闇",
    "desc": "闇の剣技"
  },
  {
    "id": 115,
    "name": "霊脈断ち",
    "type": "物理",
    "target": "単体",
    "mp": 15,
    "rate": 1,
    "count": 1,
    "base": 0,
    "desc": "敵の霊脈を断ち、全属性耐性を大きく下げる",
    "SuccessRate": 190,
    "turn": 2,
    "debuff": {
      "elmResDown": 100
    }
  },
  {
    "id": 116,
    "name": "魔封じの矢",
    "type": "物理",
    "target": "単体",
    "mp": 4,
    "rate": 0.9,
    "count": 1,
    "base": 6,
    "desc": "相手の魔力を下げる一撃",
    "SuccessRate": 90,
    "HitRate": 100,
    "turn": 5,
    "debuff": {
      "mag": 0.7
    }
  },
  {
    "id": 117,
    "name": "刃砕き",
    "type": "物理",
    "target": "単体",
    "mp": 4,
    "rate": 0.9,
    "count": 1,
    "base": 6,
    "desc": "相手の攻撃力を下げる一撃",
    "SuccessRate": 90,
    "HitRate": 100,
    "turn": 5,
    "debuff": {
      "atk": 0.7
    }
  },
  {
    "id": 118,
    "name": "雷震",
    "type": "物理",
    "target": "単体",
    "mp": 15,
    "rate": 1.2,
    "count": 1,
    "base": 15,
    "elm": "雷",
    "desc": "敵を感電させる強力な一撃",
    "SuccessRate": 70,
    "HitRate": 100,
    "Shock": true
  },
  {
    "id": 119,
    "name": "薙ぎ払い",
    "type": "物理",
    "target": "全体",
    "mp": 8,
    "rate": 0.6,
    "count": 1,
    "base": 4,
    "desc": "全体物理攻撃"
  },
  {
    "id": 120,
    "name": "霞斬り",
    "type": "物理",
    "target": "全体",
    "mp": 8,
    "rate": 0.8,
    "count": 1,
    "base": 6,
    "desc": "全体物理攻撃"
  },
  {
    "id": 121,
    "name": "雨垂れ突き",
    "type": "物理",
    "target": "ランダム",
    "mp": 8,
    "rate": 0.4,
    "count": 4,
    "base": 1,
    "desc": "4回攻撃"
  },
  {
    "id": 122,
    "name": "氷雨",
    "type": "物理",
    "target": "単体",
    "mp": 10,
    "rate": 0.4,
    "count": 4,
    "base": 1,
    "elm": "水",
    "desc": "氷の4回攻撃"
  },
  {
    "id": 123,
    "name": "烈拳乱舞",
    "type": "物理",
    "target": "ランダム",
    "mp": 14,
    "rate": 0.6,
    "count": 4,
    "base": 1,
    "desc": "4回攻撃"
  },
  {
    "id": 124,
    "name": "刃嵐",
    "type": "物理",
    "target": "ランダム",
    "mp": 17,
    "rate": 0.7,
    "count": 4,
    "base": 4,
    "desc": "4回斬撃"
  },
  {
    "id": 125,
    "name": "道化の刃",
    "type": "物理",
    "target": "ランダム",
    "mp": 18,
    "rate": 0.4,
    "count": 6,
    "base": 4,
    "desc": "舞うように刃を投じる6回ランダム攻撃"
  },
  {
    "id": 126,
    "name": "セレスティア",
    "type": "物理",
    "target": "全体",
    "mp": 20,
    "rate": 1.1,
    "count": 1,
    "base": 20,
    "elm": "光",
    "desc": "光の剣技"
  },
  {
    "id": 127,
    "name": "風刃の輪",
    "type": "物理",
    "target": "全体",
    "mp": 20,
    "rate": 0.5,
    "count": 2,
    "base": 6,
    "elm": "風",
    "desc": "敵全体に真空の刃"
  },
  {
    "id": 128,
    "name": "狼駆け",
    "type": "物理",
    "target": "全体",
    "mp": 15,
    "rate": 0.8,
    "count": 1,
    "base": 12,
    "desc": "全体物理攻撃"
  },
  {
    "id": 129,
    "name": "旋風斧",
    "type": "物理",
    "target": "全体",
    "mp": 18,
    "rate": 1,
    "count": 1,
    "base": 20,
    "desc": "全体物理攻撃"
  },
  {
    "id": 130,
    "name": "ヴァリオン",
    "type": "物理",
    "target": "全体",
    "mp": 22,
    "rate": 0.6,
    "count": 2,
    "base": 24,
    "desc": "全体物理攻撃2連"
  },
  {
    "id": 131,
    "name": "虎爪",
    "type": "物理",
    "target": "単体",
    "mp": 15,
    "rate": 0.8,
    "count": 3,
    "base": 15,
    "desc": "強力な爪の3回攻撃"
  },
  {
    "id": 132,
    "name": "クアドリア",
    "type": "物理",
    "target": "単体",
    "mp": 22,
    "rate": 0.7,
    "count": 4,
    "base": 4,
    "desc": "超高速の4連撃"
  },
  {
    "id": 133,
    "name": "フェニクシア",
    "type": "物理",
    "target": "単体",
    "mp": 28,
    "rate": 0.7,
    "count": 4,
    "base": 8,
    "desc": "不死鳥の軌跡を描く、再生を伴う4連撃",
    "drain": true
  },
  {
    "id": 134,
    "name": "九頭竜",
    "type": "物理",
    "target": "単体",
    "mp": 35,
    "rate": 0.4,
    "count": 9,
    "base": 1,
    "desc": "九頭の竜が襲うかのような9連撃"
  },
  {
    "id": 135,
    "name": "無尽の連牙",
    "type": "物理",
    "target": "単体",
    "mp": 38,
    "rate": 0.6,
    "count": 6,
    "base": 10,
    "desc": "途切れることのない怒涛の6連撃"
  },
  {
    "id": 136,
    "name": "蒼天落とし",
    "type": "物理",
    "target": "単体",
    "mp": 15,
    "rate": 1.5,
    "count": 1,
    "base": 20,
    "desc": "相手をひるませる強力な一撃",
    "SuccessRate": 90,
    "HitRate": 100,
    "turn": 1,
    "Fear": true
  },
  {
    "id": 137,
    "name": "ノクティルカ",
    "type": "物理",
    "target": "全体",
    "mp": 20,
    "rate": 1.1,
    "count": 1,
    "base": 24,
    "elm": "闇",
    "desc": "闇属性全体物理攻撃"
  },
  {
    "id": 138,
    "name": "ヴォルティガ",
    "type": "物理",
    "target": "全体",
    "mp": 20,
    "rate": 1.1,
    "count": 1,
    "base": 24,
    "elm": "雷",
    "desc": "雷属性全体物理攻撃"
  },
  {
    "id": 139,
    "name": "ニヴルヘイム",
    "type": "物理",
    "target": "全体",
    "mp": 20,
    "rate": 1.1,
    "count": 1,
    "base": 24,
    "elm": "水",
    "desc": "氷属性全体物理攻撃"
  },
  {
    "id": 140,
    "name": "紫電の葬閃",
    "type": "物理",
    "target": "全体",
    "mp": 35,
    "rate": 1.5,
    "count": 1,
    "base": 40,
    "elm": "闇",
    "desc": "闇をまとった神速の一閃で敵全体を断つ",
    "priority": 1
  },
  {
    "id": 141,
    "name": "紅蓮の輪舞",
    "type": "物理",
    "target": "全体",
    "mp": 40,
    "rate": 0.8,
    "count": 2,
    "base": 24,
    "elm": "火",
    "desc": "火属性全体物理攻撃2連"
  },
  {
    "id": 142,
    "name": "豪雨の槍",
    "type": "物理",
    "target": "ランダム",
    "mp": 32,
    "rate": 0.8,
    "count": 4,
    "base": 6,
    "desc": "強力なランダム4回攻撃"
  },
  {
    "id": 143,
    "name": "鎧穿ち",
    "type": "物理",
    "target": "単体",
    "mp": 34,
    "rate": 1.5,
    "count": 1,
    "base": 40,
    "desc": "相手の守備力と素早さを下げる一撃",
    "SuccessRate": 100,
    "turn": 3,
    "debuff": {
      "def": 0.7,
      "spd": 0.7
    }
  },
  {
    "id": 144,
    "name": "力脈断ち",
    "type": "物理",
    "target": "単体",
    "mp": 34,
    "rate": 1.5,
    "count": 1,
    "base": 40,
    "desc": "力の流れを断ち、攻撃力と魔力を大きく下げる",
    "SuccessRate": 100,
    "turn": 3,
    "debuff": {
      "atk": 0.3,
      "mag": 0.3
    }
  },
  {
    "id": 145,
    "name": "天輪脚",
    "type": "物理",
    "target": "全体",
    "mp": 37,
    "rate": 0.9,
    "count": 2,
    "base": 40,
    "desc": "全体物理攻撃2連"
  },
  {
    "id": 146,
    "name": "アステリア",
    "type": "物理",
    "target": "ランダム",
    "mp": 35,
    "rate": 0.6,
    "count": 6,
    "base": 17,
    "elm": "光",
    "desc": "光のランダム6回攻撃"
  },
  {
    "id": 147,
    "name": "アルレッキーノ",
    "type": "物理",
    "target": "ランダム",
    "mp": 50,
    "rate": 0.5,
    "count": 8,
    "base": 3,
    "desc": "幻惑する投擲で8回攻撃し、攻撃力を下げることがある",
    "SuccessRate": 70,
    "turn": 3,
    "debuff": {
      "atk": 0.7
    }
  },
  {
    "id": 148,
    "name": "アガレスの爪",
    "type": "物理",
    "target": "単体",
    "mp": 66,
    "rate": 0.8,
    "count": 3,
    "base": 50,
    "SuccessRate": 100,
    "turn": 10,
    "Poison": true,
    "desc": "邪神の爪による3連続攻撃"
  },
  {
    "id": 149,
    "name": "ヘキサグリム",
    "type": "物理",
    "target": "単体",
    "mp": 66,
    "rate": 0.7,
    "count": 6,
    "base": 5,
    "desc": "禍々しい気をまとった6連続攻撃"
  },
  {
    "id": 150,
    "name": "オクタヴィア",
    "type": "物理",
    "target": "単体",
    "mp": 88,
    "rate": 0.6,
    "count": 8,
    "base": 1,
    "desc": "八つの刃が一瞬で敵を切り刻む",
    "priority": 4
  },
  {
    "id": 151,
    "name": "羅刹一文字",
    "type": "物理",
    "target": "単体",
    "mp": 20,
    "rate": 2.5,
    "count": 1,
    "base": 0,
    "desc": "防御無視の強烈な会心攻撃",
    "HitRate": 70,
    "IgnoreDefense": true
  },
  {
    "id": 152,
    "name": "ドラグヴェント",
    "type": "物理",
    "target": "全体",
    "mp": 99,
    "rate": 1.4,
    "count": 2,
    "base": 100,
    "desc": "強烈な尻尾攻撃2連"
  },
  {
    "id": 153,
    "name": "イグニス・セクスタ",
    "type": "物理",
    "target": "単体",
    "mp": 50,
    "rate": 0.65,
    "count": 6,
    "base": 20,
    "elm": "火",
    "desc": "敵単体を焼き裂く6連続の火属性物理攻撃"
  },
  {
    "id": 154,
    "name": "レグルスの五爪",
    "type": "物理",
    "target": "単体",
    "mp": 70,
    "rate": 0.8,
    "count": 5,
    "base": 35,
    "desc": "強力な爪の5回攻撃"
  },
  {
    "id": 155,
    "name": "ケラウノス",
    "type": "物理",
    "target": "全体",
    "mp": 45,
    "rate": 1.7,
    "count": 1,
    "base": 50,
    "elm": "雷",
    "desc": "雷霆を剣に宿して敵全体を断つ伝説の剣技"
  },
  {
    "id": 156,
    "name": "デウス・マヌス",
    "type": "物理",
    "target": "単体",
    "mp": 38,
    "rate": 3.2,
    "count": 1,
    "base": 100,
    "elm": "光",
    "desc": "神威を宿した拳による究極の一撃"
  },
  {
    "id": 157,
    "name": "ラグナヴェイン",
    "type": "物理",
    "target": "単体",
    "mp": 50,
    "rate": 3.4,
    "count": 1,
    "base": 200,
    "elm": "混沌",
    "desc": "神すら切り裂く混沌の一撃で守備力を大きく下げる",
    "turn": 5,
    "debuff": {
      "def": 0.5
    }
  },
  {
    "id": 158,
    "name": "ケラウノス・ディア",
    "type": "物理",
    "target": "単体",
    "mp": 75,
    "rate": 2.1,
    "count": 2,
    "base": 50,
    "elm": "雷",
    "desc": "雷霆を交差させる伝説の2連撃"
  },
  {
    "id": 159,
    "name": "セラフィカ",
    "type": "物理",
    "target": "全体",
    "mp": 70,
    "rate": 1,
    "count": 2,
    "base": 100,
    "elm": "風",
    "desc": "十字に切り裂く2連撃"
  },
  {
    "id": 160,
    "name": "アストライア",
    "type": "物理",
    "target": "全体",
    "mp": 60,
    "rate": 1.8,
    "count": 1,
    "base": 150,
    "elm": "光",
    "desc": "敵全体を聖なる星光で討ち滅ぼす"
  },
  {
    "id": 161,
    "name": "神速薙ぎ",
    "type": "物理",
    "target": "全体",
    "mp": 55,
    "rate": 0.9,
    "count": 2,
    "base": 0,
    "desc": "神速で敵全体を薙ぎ払う",
    "priority": 5
  },
  {
    "id": 162,
    "name": "エクスティンクション",
    "type": "物理",
    "target": "単体",
    "mp": 99,
    "rate": 3.3,
    "count": 1,
    "base": 42,
    "desc": "防御を無視して存在そのものを断つ究極剣技",
    "SuccessRate": 100,
    "IgnoreDefense": true
  },
  {
    "id": 163,
    "name": "グランディオス",
    "type": "物理",
    "target": "全体",
    "mp": 99,
    "rate": 3,
    "count": 1,
    "base": 300,
    "desc": "大地を砕く衝撃で敵全体を打ち崩す"
  },
  {
    "id": 164,
    "name": "ヴォルテクシア",
    "type": "物理",
    "target": "単体",
    "mp": 99,
    "rate": 4,
    "count": 1,
    "base": 400,
    "elm": "雷",
    "desc": "剣に収束させた雷を解き放ち、敵を討ち滅ぼす"
  },
  {
    "id": 165,
    "name": "アルカディオン",
    "type": "物理",
    "target": "全体",
    "mp": 199,
    "rate": 4.5,
    "count": 1,
    "base": 500,
    "desc": "極限まで高めた聖剣の力で敵全体を滅する"
  },
  {
    "id": 166,
    "name": "フィンブルヴェイン",
    "type": "物理",
    "target": "ランダム",
    "mp": 99,
    "rate": 0.9,
    "count": 5,
    "base": 66,
    "elm": "闇",
    "desc": "終焉を告げる闇の5連撃"
  },
  {
    "id": 167,
    "name": "レガリア",
    "type": "物理",
    "target": "単体",
    "mp": 99,
    "rate": 3.5,
    "count": 1,
    "base": 0,
    "desc": "王者の威光で敵を屈服させる一撃",
    "priority": -1,
    "turn": 3,
    "debuff": {
      "def": 0.5
    },
    "IgnoreDefense": true,
    "SuccessRate": 100
  },
  {
    "id": 168,
    "name": "プリズマ・レクイエム",
    "type": "物理",
    "target": "単体",
    "mp": 99,
    "rate": 3.4,
    "hitRate": 200,
    "isPerfect": true,
    "critRate": 100,
    "count": 1,
    "base": 41,
    "desc": "万象を断ち切る大魔王の奥義",
    "SuccessRate": 100,
    "IgnoreDefense": true,
    "buff_reset": true
  },
  {
    "id": 200,
    "name": "イグナ",
    "type": "魔法",
    "target": "単体",
    "mp": 3,
    "rate": 1.1,
    "count": 1,
    "base": 6,
    "elm": "火",
    "desc": "小火球"
  },
  {
    "id": 201,
    "name": "ニヴァ",
    "type": "魔法",
    "target": "単体",
    "mp": 4,
    "rate": 1.2,
    "count": 1,
    "base": 8,
    "elm": "水",
    "desc": "氷の刃"
  },
  {
    "id": 202,
    "name": "ヴェント",
    "type": "魔法",
    "target": "全体",
    "mp": 4,
    "rate": 0.7,
    "count": 1,
    "base": 4,
    "elm": "風",
    "desc": "真空の刃"
  },
  {
    "id": 203,
    "name": "ノクス",
    "type": "魔法",
    "target": "単体",
    "mp": 4,
    "rate": 1.2,
    "count": 1,
    "base": 8,
    "elm": "闇",
    "desc": "闇の弾"
  },
  {
    "id": 204,
    "name": "フラマ",
    "type": "魔法",
    "target": "全体",
    "mp": 5,
    "rate": 0.8,
    "count": 1,
    "base": 5,
    "elm": "火",
    "desc": "炎の閃光"
  },
  {
    "id": 205,
    "name": "ルクス",
    "type": "魔法",
    "target": "全体",
    "mp": 7,
    "rate": 1,
    "count": 1,
    "base": 6,
    "elm": "光",
    "desc": "光の小爆発"
  },
  {
    "id": 206,
    "name": "ヴォルタ",
    "type": "魔法",
    "target": "単体",
    "mp": 13,
    "rate": 1.4,
    "count": 1,
    "base": 25,
    "elm": "雷",
    "desc": "落雷"
  },
  {
    "id": 207,
    "name": "イグニア",
    "type": "魔法",
    "target": "単体",
    "mp": 13,
    "rate": 1.4,
    "count": 1,
    "base": 25,
    "elm": "火",
    "desc": "中火球"
  },
  {
    "id": 208,
    "name": "ノクティア",
    "type": "魔法",
    "target": "単体",
    "mp": 13,
    "rate": 1.4,
    "count": 1,
    "base": 25,
    "elm": "闇",
    "desc": "闇の中爆発"
  },
  {
    "id": 209,
    "name": "フラミア",
    "type": "魔法",
    "target": "全体",
    "mp": 15,
    "rate": 0.95,
    "count": 1,
    "base": 10,
    "elm": "火",
    "desc": "灼熱の帯"
  },
  {
    "id": 210,
    "name": "ニヴァリオ",
    "type": "魔法",
    "target": "全体",
    "mp": 15,
    "rate": 0.95,
    "count": 1,
    "base": 10,
    "elm": "水",
    "desc": "氷の波動"
  },
  {
    "id": 211,
    "name": "ヴェンティア",
    "type": "魔法",
    "target": "全体",
    "mp": 13,
    "rate": 0.85,
    "count": 1,
    "base": 8,
    "elm": "風",
    "desc": "真空の嵐"
  },
  {
    "id": 212,
    "name": "ルクシア",
    "type": "魔法",
    "target": "全体",
    "mp": 18,
    "rate": 1.15,
    "count": 1,
    "base": 7,
    "elm": "光",
    "desc": "中爆発"
  },
  {
    "id": 213,
    "name": "イグナリス",
    "type": "魔法",
    "target": "単体",
    "mp": 28,
    "rate": 1.8,
    "count": 1,
    "base": 40,
    "elm": "火",
    "desc": "大火球"
  },
  {
    "id": 214,
    "name": "ノクタリス",
    "type": "魔法",
    "target": "単体",
    "mp": 28,
    "rate": 1.8,
    "count": 1,
    "base": 40,
    "elm": "闇",
    "desc": "闇の爆発"
  },
  {
    "id": 215,
    "name": "ヴェントリス",
    "type": "魔法",
    "target": "全体",
    "mp": 34,
    "rate": 1.2,
    "count": 1,
    "base": 20,
    "elm": "風",
    "desc": "真空の大嵐"
  },
  {
    "id": 216,
    "name": "フラマリス",
    "type": "魔法",
    "target": "全体",
    "mp": 38,
    "rate": 1.4,
    "count": 1,
    "base": 25,
    "elm": "火",
    "desc": "灼熱の波動"
  },
  {
    "id": 217,
    "name": "ニヴァロア",
    "type": "魔法",
    "target": "全体",
    "mp": 38,
    "rate": 1.4,
    "count": 1,
    "base": 25,
    "elm": "水",
    "desc": "貫く氷塊"
  },
  {
    "id": 218,
    "name": "ルクシオン",
    "type": "魔法",
    "target": "全体",
    "mp": 42,
    "rate": 1.5,
    "count": 1,
    "base": 30,
    "elm": "光",
    "desc": "大爆発"
  },
  {
    "id": 219,
    "name": "アステラ",
    "type": "魔法",
    "target": "ランダム",
    "mp": 55,
    "rate": 0.35,
    "count": 7,
    "base": 10,
    "elm": "火",
    "desc": "小さな星片を連続して降らせる"
  },
  {
    "id": 220,
    "name": "ケイオスヴォルト",
    "type": "魔法",
    "target": "全体",
    "mp": 66,
    "rate": 1.8,
    "count": 1,
    "base": 66,
    "elm": "混沌",
    "desc": "地獄の雷"
  },
  {
    "id": 221,
    "name": "ニヴァノヴァ",
    "type": "魔法",
    "target": "全体",
    "mp": 57,
    "rate": 1.65,
    "count": 1,
    "base": 45,
    "elm": "水",
    "desc": "極大氷呪文"
  },
  {
    "id": 222,
    "name": "ヴェントノヴァ",
    "type": "魔法",
    "target": "全体",
    "mp": 52,
    "rate": 1.55,
    "count": 1,
    "base": 40,
    "elm": "風",
    "desc": "極大風魔法"
  },
  {
    "id": 223,
    "name": "フラマノヴァ",
    "type": "魔法",
    "target": "全体",
    "mp": 57,
    "rate": 1.65,
    "count": 1,
    "base": 45,
    "elm": "火",
    "desc": "極大炎魔法"
  },
  {
    "id": 224,
    "name": "イグナレクス",
    "type": "魔法",
    "target": "単体",
    "mp": 42,
    "rate": 2.3,
    "count": 1,
    "base": 70,
    "elm": "火",
    "desc": "極大火炎呪文"
  },
  {
    "id": 225,
    "name": "ノクスレクス",
    "type": "魔法",
    "target": "単体",
    "mp": 42,
    "rate": 2.3,
    "count": 1,
    "base": 70,
    "elm": "闇",
    "desc": "極大闇魔法"
  },
  {
    "id": 226,
    "name": "ヴォルテリオン",
    "type": "魔法",
    "target": "全体",
    "mp": 66,
    "rate": 1.8,
    "count": 1,
    "base": 60,
    "elm": "雷",
    "desc": "極大雷呪文"
  },
  {
    "id": 227,
    "name": "ルクスノヴァ",
    "type": "魔法",
    "target": "全体",
    "mp": 66,
    "rate": 1.8,
    "count": 1,
    "base": 60,
    "elm": "光",
    "desc": "極大爆発"
  },
  {
    "id": 228,
    "name": "セラフィア",
    "type": "魔法",
    "target": "全体",
    "mp": 72,
    "rate": 1.9,
    "count": 1,
    "base": 20,
    "elm": "光",
    "desc": "敵全体を打ち滅ぼす聖なる光"
  },
  {
    "id": 229,
    "name": "ニヴァレクス",
    "type": "魔法",
    "target": "単体",
    "mp": 42,
    "rate": 2.3,
    "count": 1,
    "base": 70,
    "elm": "水",
    "desc": "凍てつく極大魔法"
  },
  {
    "id": 230,
    "name": "ヴォルタ・カエルム",
    "type": "魔法",
    "target": "ランダム",
    "mp": 88,
    "rate": 0.5,
    "count": 4,
    "base": 20,
    "elm": "雷",
    "desc": "天より雷霆を降らせる4連続攻撃・感電付与",
    "SuccessRate": 100,
    "turn": 3,
    "Shock": true
  },
  {
    "id": 231,
    "name": "アステリオン",
    "type": "魔法",
    "target": "ランダム",
    "mp": 74,
    "rate": 0.5,
    "count": 7,
    "base": 20,
    "elm": "火",
    "desc": "巨大な星塊を連続して落とす"
  },
  {
    "id": 232,
    "name": "ルクシオン・ノナ",
    "type": "魔法",
    "target": "ランダム",
    "mp": 70,
    "rate": 0.35,
    "count": 9,
    "base": 5,
    "elm": "光",
    "desc": "失われた9連続の光爆魔法"
  },
  {
    "id": 233,
    "name": "イグナリス・トリア",
    "type": "魔法",
    "target": "ランダム",
    "mp": 99,
    "rate": 1.2,
    "count": 3,
    "base": 30,
    "elm": "火",
    "desc": "失われた3連続の極大火炎魔法"
  },
  {
    "id": 234,
    "name": "ノクタリス・トリア",
    "type": "魔法",
    "target": "ランダム",
    "mp": 99,
    "rate": 1.2,
    "count": 3,
    "base": 30,
    "elm": "闇",
    "desc": "失われた3連続の極大闇魔法"
  },
  {
    "id": 235,
    "name": "ニヴァノヴァ・デュオ",
    "type": "魔法",
    "target": "全体",
    "mp": 99,
    "rate": 1,
    "count": 2,
    "base": 40,
    "elm": "水",
    "desc": "失われた2連続の極大氷結魔法"
  },
  {
    "id": 236,
    "name": "ヴェントノヴァ・クアドラ",
    "type": "魔法",
    "target": "全体",
    "mp": 99,
    "rate": 0.5,
    "count": 4,
    "base": 20,
    "elm": "風",
    "desc": "失われた4連続の極大風魔法"
  },
  {
    "id": 237,
    "name": "ヴォルテリオン・アーク",
    "type": "魔法",
    "target": "全体",
    "mp": 99,
    "rate": 2,
    "count": 1,
    "base": 100,
    "elm": "雷",
    "desc": "失われた極大雷霆魔法"
  },
  {
    "id": 238,
    "name": "ケイオス・ジェネシス",
    "type": "魔法",
    "target": "全体",
    "mp": 99,
    "rate": 2.2,
    "count": 1,
    "base": 150,
    "elm": "混沌",
    "desc": "天地創造の混沌を解き放つ"
  },
  {
    "id": 239,
    "name": "アニマ・ケイオス",
    "type": "魔法",
    "target": "ランダム",
    "mp": 66,
    "rate": 0.5,
    "count": 5,
    "base": 18,
    "elm": "混沌",
    "desc": "混沌を秘めた球を複数生み出して投げつける"
  },
  {
    "id": 240,
    "name": "エーテラ",
    "type": "魔法",
    "target": "単体",
    "mp": 50,
    "rate": 0.8,
    "count": 1,
    "base": 100,
    "desc": "無属性魔法・HP吸収",
    "drain": true
  },
  {
    "id": 241,
    "name": "エーテリス",
    "type": "魔法",
    "target": "ランダム",
    "mp": 99,
    "rate": 0.45,
    "count": 4,
    "base": 40,
    "desc": "無属性ランダム4回攻撃魔法・HP吸収",
    "drain": true
  },
  {
    "id": 242,
    "name": "アビサリア",
    "type": "魔法",
    "target": "全体",
    "mp": 166,
    "rate": 2.8,
    "count": 1,
    "base": 150,
    "elm": "混沌",
    "desc": "厄災の壁"
  },
  {
    "id": 243,
    "name": "イグナ・アルケア",
    "type": "魔法",
    "target": "単体",
    "mp": 166,
    "rate": 3.5,
    "count": 1,
    "base": 200,
    "elm": "火",
    "desc": "大魔王のみが操る原初の極大火炎"
  },
  {
    "id": 244,
    "name": "アルケ・ジェネシス",
    "type": "魔法",
    "target": "全体",
    "mp": 166,
    "rate": 2,
    "count": 1,
    "base": 100,
    "elm": "混沌",
    "desc": "世界の理を書き換える創世魔法",
    "SuccessRate": 70,
    "HitRate": 100,
    "turn": 4,
    "debuff": {
      "atk": 0.7,
      "def": 0.7,
      "mag": 0.7,
      "spd": 0.7,
      "mdef": 0.7
    }
  },
  {
    "id": 245,
    "name": "ケイオス・オメガ",
    "type": "魔法",
    "target": "全体",
    "mp": 0,
    "rate": 4,
    "count": 1,
    "base": 10,
    "elm": "混沌",
    "desc": "全MPを燃やし、混沌の大爆発を引き起こす",
    "priority": -1
  },
  {
    "id": 246,
    "name": "ルクス・トリア",
    "type": "魔法",
    "target": "ランダム",
    "mp": 0,
    "rate": 2,
    "count": 3,
    "base": 10,
    "elm": "光",
    "desc": "全MPを光に変え、ランダムに3回大ダメージを与える",
    "priority": -1
  },
  {
    "id": 247,
    "name": "ノクス・フィーネ",
    "type": "魔法",
    "target": "単体",
    "mp": 0,
    "rate": 7,
    "count": 1,
    "base": 10,
    "elm": "闇",
    "desc": "全MPを闇に変え、敵単体に超大ダメージを与える",
    "priority": -1
  },
  {
    "id": 248,
    "name": "プリズマ・アルカ",
    "type": "魔法",
    "target": "全体",
    "mp": 199,
    "rate": 0,
    "count": 1,
    "base": 999,
    "desc": "敵全体に極大の固定ダメージを与える",
    "priority": -1,
    "fix": true
  },
  {
    "id": 300,
    "name": "火炎の吐息",
    "type": "ブレス",
    "target": "全体",
    "mp": 7,
    "rate": 0.6,
    "count": 1,
    "base": 6,
    "elm": "火",
    "desc": "炎の息"
  },
  {
    "id": 301,
    "name": "氷霧の吐息",
    "type": "ブレス",
    "target": "全体",
    "mp": 12,
    "rate": 0.8,
    "count": 1,
    "base": 17,
    "elm": "水",
    "desc": "冷たい息"
  },
  {
    "id": 302,
    "name": "焔獄の息",
    "type": "ブレス",
    "target": "全体",
    "mp": 12,
    "rate": 0.8,
    "count": 1,
    "base": 21,
    "elm": "火",
    "desc": "激しい炎"
  },
  {
    "id": 303,
    "name": "闇蝕の霧",
    "type": "ブレス",
    "target": "全体",
    "mp": 16,
    "rate": 0.95,
    "count": 1,
    "base": 17,
    "elm": "闇",
    "desc": "闇蝕の霧をまき散らし全体闇ダメージ"
  },
  {
    "id": 304,
    "name": "雷獣の息",
    "type": "ブレス",
    "target": "全体",
    "mp": 16,
    "rate": 0.95,
    "count": 1,
    "base": 17,
    "elm": "雷",
    "desc": "稲妻を呼び出し全体雷ダメージ"
  },
  {
    "id": 305,
    "name": "白銀凍気",
    "type": "ブレス",
    "target": "全体",
    "mp": 30,
    "rate": 1.3,
    "count": 1,
    "base": 44,
    "elm": "水",
    "desc": "極寒の息"
  },
  {
    "id": 306,
    "name": "灼界の業火",
    "type": "ブレス",
    "target": "全体",
    "mp": 30,
    "rate": 1.3,
    "count": 1,
    "base": 44,
    "elm": "火",
    "desc": "灼熱の業火"
  },
  {
    "id": 307,
    "name": "ニヴルヘイズ",
    "type": "ブレス",
    "target": "全体",
    "mp": 50,
    "rate": 1.6,
    "count": 1,
    "base": 66,
    "elm": "水",
    "desc": "全てを凍らす息"
  },
  {
    "id": 308,
    "name": "アビサリオン",
    "type": "ブレス",
    "target": "全体",
    "mp": 50,
    "rate": 1.6,
    "count": 1,
    "base": 66,
    "elm": "混沌",
    "desc": "地獄の炎で全体混沌ダメージ"
  },
  {
    "id": 309,
    "name": "ニヴァグラシア",
    "type": "ブレス",
    "target": "全体",
    "mp": 70,
    "rate": 1.8,
    "count": 1,
    "base": 88,
    "elm": "水",
    "turn": 3,
    "debuff": {
      "mag": 0.7
    },
    "desc": "全体水属性極大ダメージ＋魔力低下"
  },
  {
    "id": 310,
    "name": "イグナグラシア",
    "type": "ブレス",
    "target": "全体",
    "mp": 70,
    "rate": 1.8,
    "count": 1,
    "base": 88,
    "elm": "火",
    "desc": "全体火属性極大ダメージ＋攻撃低下",
    "turn": 3,
    "debuff": {
      "atk": 0.7
    }
  },
  {
    "id": 311,
    "name": "ゼフィルカ",
    "type": "ブレス",
    "target": "全体",
    "mp": 88,
    "rate": 1.1,
    "count": 2,
    "base": 66,
    "elm": "風",
    "desc": "風属性全体2回攻撃＋速度大幅減",
    "turn": 5,
    "debuff": {
      "spd": 0.3
    }
  },
  {
    "id": 312,
    "name": "ルクス・サクラ",
    "type": "ブレス",
    "target": "全体",
    "mp": 99,
    "rate": 2.3,
    "count": 1,
    "base": 99,
    "elm": "光",
    "desc": "全体光属性極大ダメージ＋スキル封印",
    "SuccessRate": 50,
    "turn": 3,
    "SpellSeal": true,
    "SkillSeal": true,
    "HealSeal": true
  },
  {
    "id": 313,
    "name": "ノクス・マレ",
    "type": "ブレス",
    "target": "全体",
    "mp": 99,
    "rate": 2.3,
    "count": 1,
    "base": 99,
    "elm": "闇",
    "desc": "全体闇属性極大ダメージ＋全属性耐性ダウン",
    "SuccessRate": 50,
    "turn": 3,
    "debuff": {
      "elmResDown": 50
    }
  },
  {
    "id": 314,
    "name": "ノクス・アステラ",
    "type": "ブレス",
    "target": "ランダム",
    "mp": 99,
    "rate": 0.66,
    "count": 6,
    "base": 66,
    "elm": "闇",
    "desc": "数多の流星がランダムに降り注ぎ闇の大ダメージ"
  },
  {
    "id": 315,
    "name": "マレディクト",
    "type": "ブレス",
    "target": "全体",
    "mp": 99,
    "rate": 0.5,
    "count": 1,
    "base": 66,
    "elm": "混沌",
    "desc": "闇の根源から災禍を呼び、複数の状態異常をまき散らす",
    "HitRate": 100,
    "SuccessRate": 30,
    "turn": 2,
    "ToxicPoison": true,
    "Fear": false,
    "SpellSeal": true,
    "SkillSeal": true,
    "HealSeal": true
  },
  {
    "id": 400,
    "name": "ルナ",
    "type": "回復",
    "target": "単体",
    "mp": 2,
    "rate": 0.6,
    "count": 1,
    "base": 20,
    "desc": "小回復"
  },
  {
    "id": 401,
    "name": "ルナリア",
    "type": "回復",
    "target": "単体",
    "mp": 5,
    "rate": 1,
    "count": 1,
    "base": 50,
    "desc": "中回復"
  },
  {
    "id": 402,
    "name": "静心",
    "type": "回復",
    "target": "自分",
    "mp": 11,
    "ratio": 0.5,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "HPを50%回復"
  },
  {
    "id": 403,
    "name": "明鏡",
    "type": "MP回復",
    "target": "自分",
    "mp": 0,
    "ratio": 0.5,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "MPを50%回復"
  },
  {
    "id": 404,
    "name": "ルナティア",
    "type": "回復",
    "target": "全体",
    "mp": 17,
    "rate": 0.6,
    "count": 1,
    "base": 25,
    "desc": "全体回復"
  },
  {
    "id": 405,
    "name": "ルストラ",
    "type": "特殊",
    "target": "全体",
    "mp": 15,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "味方全体の状態異常を浄化する",
    "CureAilments": true
  },
  {
    "id": 406,
    "name": "清明の構え",
    "type": "特殊",
    "target": "自分",
    "mp": 8,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "自身の弱体効果と状態異常を払い清める",
    "CureAilments": true,
    "debuff_reset": true
  },
  {
    "id": 407,
    "name": "リザ",
    "type": "蘇生",
    "target": "単体",
    "mp": 10,
    "rate": 0.5,
    "count": 1,
    "base": 20,
    "desc": "50%蘇生",
    "SuccessRate": 50
  },
  {
    "id": 408,
    "name": "ルストラティオ",
    "type": "特殊",
    "target": "全体",
    "mp": 35,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "味方全体の状態異常と弱体効果を浄化する",
    "CureAilments": true,
    "debuff_reset": true
  },
  {
    "id": 409,
    "name": "恵雨の祈り",
    "type": "特殊",
    "target": "全体",
    "mp": 26,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "毎ターンHP回復",
    "turn": 5,
    "HPRegen": 0.1
  },
  {
    "id": 410,
    "name": "魔泉の風",
    "type": "特殊",
    "target": "全体",
    "mp": 15,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "毎ターンMP回復",
    "turn": 5,
    "MPRegen": 0.05
  },
  {
    "id": 411,
    "name": "ルナ・セレス",
    "type": "回復",
    "target": "単体",
    "mp": 10,
    "rate": 0.6,
    "count": 1,
    "base": 20,
    "desc": "ごく一部の術者のみが扱える最速の回復魔法",
    "priority": 20
  },
  {
    "id": 412,
    "name": "ルナリス",
    "type": "回復",
    "target": "単体",
    "mp": 20,
    "rate": 1.5,
    "count": 1,
    "base": 250,
    "desc": "超回復",
    "fix": false
  },
  {
    "id": 413,
    "name": "ルナリオン",
    "type": "回復",
    "target": "全体",
    "mp": 35,
    "rate": 1,
    "count": 1,
    "base": 120,
    "desc": "全体超回復",
    "fix": false
  },
  {
    "id": 414,
    "name": "リザリス",
    "type": "蘇生",
    "target": "単体",
    "mp": 20,
    "rate": 1,
    "count": 1,
    "base": 50,
    "desc": "100%蘇生",
    "SuccessRate": 100
  },
  {
    "id": 415,
    "name": "不死鳥の誓い",
    "type": "回復",
    "target": "自分",
    "mp": 66,
    "rate": 1,
    "count": 1,
    "base": 500,
    "desc": "あらゆる苦難を受け止め、不死鳥のごとく生還する",
    "priority": -20,
    "CureAilments": true,
    "debuff_reset": true
  },
  {
    "id": 416,
    "name": "ルナ・ユグドラ",
    "type": "回復",
    "target": "全体",
    "mp": 66,
    "rate": 1.5,
    "count": 1,
    "base": 300,
    "desc": "味方全体を大きく癒やし、状態異常と弱体効果を浄化する",
    "CureAilments": true,
    "debuff_reset": true
  },
  {
    "id": 417,
    "name": "ルナレクス",
    "type": "回復",
    "target": "単体",
    "mp": 40,
    "rate": 0,
    "count": 1,
    "base": 99999,
    "desc": "完全回復",
    "fix": true
  },
  {
    "id": 418,
    "name": "ルナノヴァ",
    "type": "回復",
    "target": "全体",
    "mp": 99,
    "rate": 0,
    "count": 1,
    "base": 99999,
    "desc": "全体完全回復",
    "fix": true
  },
  {
    "id": 419,
    "name": "リザノヴァ",
    "type": "蘇生",
    "target": "全体",
    "mp": 99,
    "rate": 1,
    "count": 1,
    "base": 50,
    "desc": "味方全員を完全蘇生",
    "SuccessRate": 100
  },
  {
    "id": 500,
    "name": "ヴァルガ",
    "type": "強化",
    "target": "単体",
    "mp": 5,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "攻撃力アップ",
    "turn": 5,
    "buff": {
      "atk": 1.5
    }
  },
  {
    "id": 501,
    "name": "アルマティア",
    "type": "強化",
    "target": "全体",
    "mp": 7,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "守備力アップ",
    "turn": 5,
    "buff": {
      "def": 1.5
    }
  },
  {
    "id": 502,
    "name": "セレリオ",
    "type": "強化",
    "target": "全体",
    "mp": 7,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "全体の素早さアップ",
    "turn": 5,
    "buff": {
      "spd": 1.3
    }
  },
  {
    "id": 503,
    "name": "エレメンタ",
    "type": "強化",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "全体の全属性耐性アップ",
    "turn": 5,
    "buff": {
      "elmResUp": 30
    }
  },
  {
    "id": 504,
    "name": "アストラの加護",
    "type": "強化",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "味方全体を星の加護で包み、状態異常耐性を高める",
    "turn": 3,
    "buff": {
      "resists_Poison": 80,
      "resists_Shock": 80,
      "resists_Fear": 80,
      "resists_Seal": 80,
      "resists_Debuff": 80,
      "resists_InstantDeath": 80
    }
  },
  {
    "id": 505,
    "name": "無垢の護符",
    "type": "強化",
    "target": "単体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "状態異常を浄化し、あらゆる異常への耐性を最大まで高める",
    "turn": 10,
    "buff": {
      "resists_Poison": 200,
      "resists_Shock": 200,
      "resists_Fear": 200,
      "resists_Seal": 200,
      "resists_Debuff": 200,
      "resists_InstantDeath": 200
    }
  },
  {
    "id": 506,
    "name": "アルカナ覚醒",
    "type": "強化",
    "target": "自分",
    "mp": 20,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "魔力超上昇",
    "turn": 4,
    "buff": {
      "mag": 2
    }
  },
  {
    "id": 507,
    "name": "修羅の構え",
    "type": "強化",
    "target": "自分",
    "mp": 20,
    "rate": 0,
    "count": 0,
    "base": 0,
    "desc": "防御を捨て、攻撃力を極限まで高める",
    "buff": {
      "atk": 2.5
    },
    "turn": 4,
    "debuff": {
      "def": 0.7
    }
  },
  {
    "id": 508,
    "name": "戦神の律動",
    "type": "強化",
    "target": "全体",
    "mp": 45,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "戦神の律動で味方全体の全能力を高める",
    "turn": 5,
    "buff": {
      "atk": 1.2,
      "def": 1.2,
      "spd": 1.2,
      "mag": 1.2,
      "mdef": 1.2
    }
  },
  {
    "id": 509,
    "name": "アイギス",
    "type": "強化",
    "target": "全体",
    "mp": 60,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "神盾の加護で味方全体の全属性耐性を大きく高める",
    "turn": 2,
    "buff": {
      "elmResUp": 80
    }
  },
  {
    "id": 510,
    "name": "冥王の衣",
    "type": "強化",
    "target": "自分",
    "mp": 66,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "冥王の外套をまとい、全能力・属性耐性・状態異常耐性を高める",
    "turn": 5,
    "buff": {
      "atk": 1.5,
      "def": 1.5,
      "spd": 1.5,
      "mag": 1.5,
      "mdef": 1.5,
      "elmResUp": 50,
      "resists_Poison": 100,
      "resists_Shock": 100,
      "resists_Fear": 100,
      "resists_Seal": 100,
      "resists_Debuff": 100,
      "resists_InstantDeath": 100
    },
    "CureAilments": true,
    "debuff_reset": true
  },
  {
    "id": 600,
    "name": "ディアルマ",
    "type": "弱体",
    "target": "単体",
    "mp": 5,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "敵の守備ダウン",
    "SuccessRate": 70,
    "turn": 5,
    "debuff": {
      "def": 0.7
    }
  },
  {
    "id": 601,
    "name": "ディセレリオ",
    "type": "弱体",
    "target": "全体",
    "mp": 7,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "敵の素早さダウン",
    "SuccessRate": 70,
    "turn": 5,
    "debuff": {
      "spd": 0.7
    }
  },
  {
    "id": 602,
    "name": "ディアルマス",
    "type": "弱体",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "敵の守備ダウン",
    "SuccessRate": 70,
    "turn": 5,
    "debuff": {
      "def": 0.7
    }
  },
  {
    "id": 603,
    "name": "ディヴァルガ",
    "type": "弱体",
    "target": "単体",
    "mp": 5,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "敵の攻撃ダウン",
    "SuccessRate": 70,
    "turn": 5,
    "debuff": {
      "atk": 0.7
    }
  },
  {
    "id": 604,
    "name": "ディミヌエンド",
    "type": "弱体",
    "target": "全体",
    "mp": 45,
    "rate": 0,
    "count": 1,
    "base": 20,
    "desc": "敵全体のあらゆる能力を低下させる",
    "SuccessRate": 80,
    "turn": 4,
    "debuff": {
      "atk": 0.7,
      "def": 0.7,
      "mag": 0.7,
      "spd": 0.7,
      "mdef": 0.7
    }
  },
  {
    "id": 700,
    "name": "毒霧",
    "type": "特殊",
    "target": "全体",
    "mp": 3,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "毒霧を吐き出す",
    "SuccessRate": 80,
    "turn": 10,
    "Poison": true
  },
  {
    "id": 701,
    "name": "獣咆",
    "type": "特殊",
    "target": "全体",
    "mp": 4,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "獣の咆哮で敵全体をひるませる",
    "SuccessRate": 80,
    "turn": 1,
    "Fear": true
  },
  {
    "id": 702,
    "name": "猛毒霧",
    "type": "特殊",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "猛毒の霧を吐き出す",
    "SuccessRate": 80,
    "turn": 10,
    "ToxicPoison": true
  },
  {
    "id": 703,
    "name": "サイレントゥム",
    "type": "特殊",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "魔法と回復術を封じる静寂の呪い",
    "SuccessRate": 80,
    "turn": 5,
    "SpellSeal": true,
    "HealSeal": true
  },
  {
    "id": 704,
    "name": "カテナ",
    "type": "特殊",
    "target": "全体",
    "mp": 10,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "技の発動を縛る封印術",
    "SuccessRate": 80,
    "HitRate": 100,
    "turn": 5,
    "SkillSeal": true
  },
  {
    "id": 705,
    "name": "零相の波動",
    "type": "特殊",
    "target": "全体",
    "mp": 15,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "敵全体の強化効果を虚無へ還す",
    "buff_reset": true
  },
  {
    "id": 706,
    "name": "モルス",
    "type": "特殊",
    "target": "単体",
    "mp": 16,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "敵単体を死へ導く呪言",
    "SuccessRate": 30,
    "PercentDamage": 1
  },
  {
    "id": 707,
    "name": "モルスの舞",
    "type": "特殊",
    "target": "全体",
    "mp": 28,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "敵全体を低確率で死へ誘う冥府の舞",
    "SuccessRate": 20,
    "PercentDamage": 1
  },
  {
    "id": 708,
    "name": "モルスアリア",
    "type": "特殊",
    "target": "全体",
    "mp": 28,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "敵全体を死へ導く呪言",
    "SuccessRate": 30,
    "PercentDamage": 1
  },
  {
    "id": 709,
    "name": "モルスレクス",
    "type": "特殊",
    "target": "全体",
    "mp": 66,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "敵全体を高確率で死へ導く上位呪言",
    "SuccessRate": 50,
    "PercentDamage": 1
  },
  {
    "id": 710,
    "name": "冥府乱舞",
    "type": "特殊",
    "target": "ランダム",
    "mp": 66,
    "rate": 0,
    "count": 3,
    "base": 0,
    "desc": "死の気配をまとい、敵を無差別に冥府へ誘う",
    "SuccessRate": 70,
    "PercentDamage": 1
  },
  {
    "id": 711,
    "name": "獣王咆",
    "type": "特殊",
    "target": "全体",
    "mp": 34,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "獣王の咆哮で敵全体をひるませる",
    "HitRate": 100,
    "SuccessRate": 80,
    "PercentDamage": 0.2,
    "turn": 1,
    "Fear": true
  },
  {
    "id": 712,
    "name": "絶望の咆哮",
    "type": "特殊",
    "target": "全体",
    "mp": 47,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "絶望を刻む咆哮で敵全体の心を凍らせる",
    "SuccessRate": 70,
    "HitRate": 100,
    "PercentDamage": 0.5,
    "turn": 1,
    "Fear": true
  },
  {
    "id": 713,
    "name": "冥蛛の棘",
    "type": "特殊",
    "target": "全体",
    "mp": 45,
    "rate": 0,
    "count": 1,
    "base": 0,
    "HitRate": 100,
    "SuccessRate": 90,
    "PercentDamage": 0.6,
    "desc": "冥府の大蜘蛛が放つ棘で敵全体を蝕む"
  },
  {
    "id": 714,
    "name": "竜王咆哮",
    "type": "特殊",
    "target": "全体",
    "mp": 50,
    "rate": 1,
    "count": 1,
    "base": 0,
    "priority": -20,
    "SuccessRate": 190,
    "PercentDamage": 0.1,
    "turn": 1,
    "buff_reset": true,
    "Fear": true,
    "desc": "竜王の咆哮で敵全体をひるませ、強化効果を消し去る"
  },
  {
    "id": 715,
    "name": "無慈悲なる手",
    "type": "特殊",
    "target": "単体",
    "mp": 99,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "慈悲を捨て、敵単体の生命を刈り取る",
    "priority": -5,
    "SuccessRate": 100,
    "PercentDamage": 0.99
  },
  {
    "id": 700101,
    "name": "混沌の外套",
    "type": "強化",
    "target": "自分",
    "mp": 120,
    "rate": 0,
    "count": 1,
    "base": 0,
    "desc": "混沌の外套をまとい、全能力と属性耐性を高める",
    "turn": 5,
    "buff": {
      "atk": 1.35,
      "def": 1.35,
      "spd": 1.2,
      "mag": 1.35,
      "mdef": 1.35,
      "elmResUp": 40
    }
  }
];
