/* skills.js */
window.SKILLS_DATA = [
    {
        "id": 1,
        "name": "こうげき",
        "type": "通常攻撃",
        "target": "単体",
        "mp": 0,
        "rate": 1,
        "count": 1,
        "base": 0,
        "elm": null,
        "desc": "通常攻撃"
    },
    {
        "id": 2,
        "name": "ぼうぎょ",
        "type": "特殊",
        "target": "自分",
        "mp": 0,
        "rate": 0,
        "count": 0,
        "base": 20,
        "elm": null,
        "desc": "ダメージ軽減"
    },
    {
        "id": 3,
        "name": "こうげき",
        "type": "物理",
        "target": "単体",
        "mp": 0,
        "rate": 0.8,
        "count": 2,
        "base": 0,
        "desc": "2回攻撃",
        "elm": null,
        "drain": true
    },
    {
        "id": 9,
        "name": "逃げる",
        "type": "特殊",
        "target": "自分",
        "mp": 0,
        "rate": 0,
        "count": 0,
        "base": 20,
        "desc": "戦闘から離脱"
    },
    {
        "id": 10,
        "name": "メラ",
        "type": "魔法",
        "target": "単体",
        "mp": 4,
        "rate": 1,
        "count": 1,
        "base": 60,
        "elm": "火",
        "desc": "小火球"
    },
    {
        "id": 11,
        "name": "ヒャド",
        "type": "魔法",
        "target": "単体",
        "mp": 5,
        "rate": 1,
        "count": 1,
        "base": 62,
        "elm": "水",
        "desc": "氷の刃"
    },
    {
        "id": 12,
        "name": "バギ",
        "type": "魔法",
        "target": "全体",
        "mp": 8,
        "rate": 0.7,
        "count": 1,
        "base": 35,
        "elm": "風",
        "desc": "真空の刃"
    },
    {
        "id": 13,
        "name": "ライデイン",
        "type": "魔法",
        "target": "単体",
        "mp": 10,
        "rate": 1.2,
        "count": 1,
        "base": 70,
        "elm": "雷",
        "desc": "落雷"
    },
    {
        "id": 14,
        "name": "ドルマ",
        "type": "魔法",
        "target": "単体",
        "mp": 6,
        "rate": 1.1,
        "count": 1,
        "base": 65,
        "elm": "闇",
        "desc": "闇の弾"
    },
    {
        "id": 20,
        "name": "ホイミ",
        "type": "回復",
        "target": "単体",
        "mp": 5,
        "rate": 1.2,
        "count": 1,
        "base": 80,
        "elm": null,
        "desc": "小回復"
    },
    {
        "id": 21,
        "name": "ベホイミ",
        "type": "回復",
        "target": "単体",
        "mp": 40,
        "rate": 1.8,
        "count": 1,
        "base": 230,
        "elm": null,
        "desc": "中回復"
    },
    {
        "id": 22,
        "name": "ハッスルダンス",
        "type": "回復",
        "target": "全体",
        "mp": 120,
        "rate": 1.2,
        "count": 1,
        "base": 110,
        "elm": null,
        "desc": "全体回復"
    },
    {
        "id": 23,
        "name": "ベホイム",
        "type": "回復",
        "target": "単体",
        "mp": 250,
        "rate": 0,
        "count": 1,
        "base": 29999,
        "fix": true,
        "desc": "超回復"
    },
    {
        "id": 24,
        "name": "ベホマラー",
        "type": "回復",
        "target": "全体",
        "mp": 1200,
        "rate": 0,
        "count": 1,
        "base": 29999,
        "fix": true,
        "desc": "全体超回復"
    },
    {
        "id": 30,
        "name": "ザオラル",
        "type": "蘇生",
        "target": "単体",
        "mp": 60,
        "rate": 0.5,
        "count": 1,
        "base": 20,
        "elm": null,
        "desc": "50%蘇生"
    },
    {
        "id": 31,
        "name": "ザオリク",
        "type": "蘇生",
        "target": "単体",
        "mp": 300,
        "rate": 1,
        "count": 1,
        "base": 50,
        "elm": null,
        "desc": "100%蘇生"
    },
    {
        "id": 40,
        "name": "火炎斬り",
        "type": "物理",
        "target": "単体",
        "mp": 15,
        "rate": 1,
        "count": 1,
        "base": 55,
        "elm": "火",
        "desc": "炎の剣技"
    },
    {
        "id": 41,
        "name": "はやぶさ斬り",
        "type": "物理",
        "target": "単体",
        "mp": 25,
        "rate": 0.6,
        "count": 2,
        "base": 20,
        "elm": null,
        "desc": "2回攻撃"
    },
    {
        "id": 42,
        "name": "氷結斬り",
        "type": "物理",
        "target": "単体",
        "mp": 15,
        "rate": 1,
        "count": 1,
        "base": 55,
        "elm": "水",
        "desc": "氷の剣技"
    },
    {
        "id": 43,
        "name": "雷鳴突き",
        "type": "物理",
        "target": "単体",
        "mp": 15,
        "rate": 1,
        "count": 1,
        "base": 55,
        "elm": "雷",
        "desc": "雷の槍技"
    },
    {
        "id": 44,
        "name": "兜割り",
        "type": "物理",
        "target": "単体",
        "mp": 15,
        "rate": 1,
        "count": 1,
        "base": 55,
        "debuff": {
            "def": 0.8
        },
        "desc": "敵の守備を下げる"
    },
    {
        "id": 45,
        "name": "メタル斬り",
        "type": "物理",
        "target": "単体",
        "mp": 20,
        "rate": 0,
        "count": 1,
        "base": 22,
        "fix": true,
        "desc": "メタルに固定ダメージ"
    },
    {
        "id": 46,
        "name": "ウイングアッパー",
        "type": "物理",
        "target": "単体",
        "mp": 20,
        "rate": 1.1,
        "count": 1,
        "base": 60,
        "elm": "風",
        "desc": "風の拳"
    },
    {
        "id": 47,
        "name": "ブラッドソード",
        "type": "物理",
        "target": "単体",
        "mp": 30,
        "rate": 1.2,
        "count": 1,
        "base": 70,
        "elm": "混沌",
        "drain": true,
        "desc": "HP吸収"
    },
    {
        "id": 48,
        "name": "ミラクルソード",
        "type": "物理",
        "target": "単体",
        "mp": 35,
        "rate": 0.7,
        "count": 1,
        "base": 50,
        "drain": true,
        "desc": "奇跡の剣技・HP回復"
    },
    {
        "id": 49,
        "name": "疾風突き",
        "type": "物理",
        "target": "単体",
        "mp": 20,
        "rate": 0.5,
        "count": 1,
        "base": 0,
        "priority": 2,
        "desc": "疾風の如き速さの一撃"
    },
    {
        "id": 50,
        "name": "バイキルト",
        "type": "強化",
        "target": "単体",
        "mp": 40,
        "rate": 0,
        "count": 1,
        "base": 20,
        "buff": {
            "atk": 1.5
        },
        "desc": "攻撃力アップ"
    },
    {
        "id": 51,
        "name": "スカラ",
        "type": "強化",
        "target": "単体",
        "mp": 20,
        "rate": 0,
        "count": 1,
        "base": 20,
        "buff": {
            "def": 1.5
        },
        "desc": "守備力アップ"
    },
    {
        "id": 52,
        "name": "ピオリム",
        "type": "強化",
        "target": "全体",
        "mp": 30,
        "rate": 0,
        "count": 1,
        "base": 20,
        "buff": {
            "spd": 1.3
        },
        "desc": "素早さアップ"
    },
    {
        "id": 53,
        "name": "マジックバリア",
        "type": "強化",
        "target": "全体",
        "mp": 40,
        "rate": 0,
        "count": 1,
        "base": 20,
        "buff": {
            "mag": 1.5
        },
        "desc": "魔法防御アップ"
    },
    {
        "id": 55,
        "name": "フォースブレイク",
        "type": "物理",
        "target": "単体",
        "mp": 150,
        "rate": 1.2,
        "count": 1,
        "base": 0,
        "debuff": {
            "elmResDown": 100
        },
        "desc": "敵の全属性耐性を激減させる",
        "SuccessRate": 200
    },
    {
        "id": 56,
        "name": "ひかりのはどう",
        "type": "特殊",
        "target": "全体",
        "mp": 550,
        "rate": 0,
        "count": 1,
        "base": 0,
        "debuff_reset": true,
        "desc": "味方全体の状態異常と弱体を解除",
        "CureAilments": true
    },
    {
        "id": 57,
        "name": "いてつくはどう",
        "type": "特殊",
        "target": "全体",
        "mp": 250,
        "rate": 0,
        "count": 1,
        "base": 0,
        "buff_reset": true,
        "desc": "敵全体の強化を解除"
    },
    {
        "id": 58,
        "name": "たたかいのドラム",
        "type": "強化",
        "target": "全体",
        "mp": 550,
        "rate": 0,
        "count": 1,
        "base": 0,
        "buff": {
            "atk": 1.2,
            "def": 1.2,
            "spd": 1.2,
            "mag": 1.2
        },
        "turn": 5,
        "desc": "味方全体の全ステータスUP"
    },
    {
        "id": 59,
        "name": "パラディンガード",
        "type": "強化",
        "target": "全体",
        "mp": 2000,
        "rate": 0,
        "count": 1,
        "base": 0,
        "buff": {
            "elmResUp": 80
        },
        "turn": 2,
        "desc": "味方全体の全属性耐性超上昇"
    },
    {
        "id": 60,
        "name": "ルカニ",
        "type": "弱体",
        "target": "単体",
        "mp": 20,
        "rate": 0,
        "count": 1,
        "base": 20,
        "SuccessRate": 70,
        "debuff": {
            "def": 0.5
        },
        "desc": "敵の守備ダウン"
    },
    {
        "id": 61,
        "name": "ボミオス",
        "type": "弱体",
        "target": "全体",
        "mp": 30,
        "rate": 0,
        "count": 1,
        "base": 20,
        "SuccessRate": 70,
        "debuff": {
            "spd": 0.7
        },
        "desc": "敵の素早さダウン"
    },
    {
        "id": 62,
        "name": "キアリク",
        "type": "特殊",
        "target": "全体",
        "mp": 100,
        "rate": 0,
        "count": 1,
        "base": 0,
        "CureAilments": true,
        "desc": "味方全体の状態異常を治療する"
    },
    {
        "id": 63,
        "name": "世界樹の陽光",
        "type": "回復",
        "target": "全体",
        "mp": 3000,
        "rate": 1,
        "count": 1,
        "base": 99999,
        "CureAilments": true,
        "desc": "味方全体のHPを超回復し、状態異常を治療する",
        "debuff_reset": true
    },
    {
        "id": 80,
        "name": "めいそう",
        "type": "回復",
        "target": "自分",
        "mp": 0,
        "rate": 0,
        "count": 1,
        "base": 0,
        "ratio": 0.5,
        "desc": "HPを50%回復"
    },
    {
        "id": 81,
        "name": "無念無想",
        "type": "MP回復",
        "target": "自分",
        "mp": 0,
        "rate": 0,
        "count": 1,
        "base": 0,
        "ratio": 0.5,
        "desc": "MPを50%回復"
    },
    {
        "id": 101,
        "name": "強撃",
        "type": "物理",
        "target": "単体",
        "mp": 40,
        "rate": 1.4,
        "count": 1,
        "base": 60,
        "desc": "力強い一撃"
    },
    {
        "id": 102,
        "name": "渾身斬り",
        "type": "物理",
        "target": "単体",
        "mp": 80,
        "rate": 1.8,
        "count": 1,
        "base": 180,
        "desc": "渾身の一撃"
    },
    {
        "id": 103,
        "name": "ギガスラッシュ",
        "type": "物理",
        "target": "全体",
        "mp": 150,
        "rate": 1.4,
        "count": 1,
        "base": 200,
        "elm": "光",
        "desc": "光の剣技"
    },
    {
        "id": 104,
        "name": "暗黒剣",
        "type": "物理",
        "target": "単体",
        "mp": 120,
        "rate": 1.5,
        "count": 1,
        "base": 190,
        "elm": "闇",
        "desc": "闇の剣技"
    },
    {
        "id": 105,
        "name": "しんくうは",
        "type": "物理",
        "target": "全体",
        "mp": 140,
        "rate": 1.4,
        "count": 2,
        "base": 80,
        "elm": "風",
        "desc": "真空の刃"
    },
    {
        "id": 106,
        "name": "天下無双",
        "type": "物理",
        "target": "単体",
        "mp": 250,
        "rate": 0.6,
        "count": 6,
        "base": 20,
        "desc": "怒涛の6連撃"
    },
    {
        "id": 107,
        "name": "テールスイング",
        "type": "物理",
        "target": "全体",
        "mp": 200,
        "rate": 1,
        "count": 2,
        "base": 1999,
        "desc": "強烈な尻尾攻撃2連"
    },
    {
        "id": 108,
        "name": "超はやぶさ斬り",
        "type": "物理",
        "target": "単体",
        "mp": 180,
        "rate": 0.7,
        "count": 4,
        "base": 50,
        "desc": "超高速の4連撃"
    },
    {
        "id": 109,
        "name": "不死鳥天舞",
        "type": "物理",
        "target": "単体",
        "mp": 220,
        "rate": 0.7,
        "count": 4,
        "base": 100,
        "drain": true,
        "desc": "再生を伴う4連撃"
    },
    {
        "id": 110,
        "name": "九龍連斬",
        "type": "物理",
        "target": "単体",
        "mp": 300,
        "rate": 0.6,
        "count": 9,
        "base": 50,
        "desc": "9頭の龍の如き連撃"
    },
    {
        "id": 111,
        "name": "魔人の絶技",
        "type": "物理",
        "target": "単体",
        "mp": 350,
        "rate": 1.1,
        "count": 6,
        "base": 100,
        "desc": "魔人のごとき6連続攻撃"
    },
    {
        "id": 111,
        "name": "八刀一閃",
        "type": "物理",
        "target": "単体",
        "mp": 350,
        "rate": 1.1,
        "count": 6,
        "base": 100,
        "priority": 4,
        "desc": "誰よりも速く八つの刃で切り刻む"
    },
    {
        "id": 112,
        "name": "魔人斬り",
        "type": "物理",
        "target": "単体",
        "mp": 10,
        "rate": 2.5,
        "count": 1,
        "base": 0,
        "SuccessRate": 25,
        "IgnoreDefense": true,
        "desc": "当たる確率は低いが、防御無視の会心攻撃"
    },
    {
        "id": 113,
        "name": "大魔人斬り",
        "type": "物理",
        "target": "単体",
        "mp": 300,
        "rate": 3,
        "count": 1,
        "base": 0,
        "SuccessRate": 50,
        "IgnoreDefense": true,
        "desc": "防御無視の強烈な会心攻撃"
    },
    {
        "id": 201,
        "name": "五月雨突き",
        "type": "物理",
        "target": "ランダム",
        "mp": 80,
        "rate": 0.5,
        "count": 4,
        "base": 20,
        "desc": "4回攻撃"
    },
    {
        "id": 202,
        "name": "爆裂拳",
        "type": "物理",
        "target": "ランダム",
        "mp": 100,
        "rate": 0.6,
        "count": 4,
        "base": 20,
        "desc": "4回攻撃"
    },
    {
        "id": 203,
        "name": "さみだれ剣",
        "type": "物理",
        "target": "ランダム",
        "mp": 120,
        "rate": 0.7,
        "count": 4,
        "base": 50,
        "desc": "4回斬撃"
    },
    {
        "id": 301,
        "name": "メラミ",
        "type": "魔法",
        "target": "単体",
        "mp": 40,
        "rate": 1.4,
        "count": 1,
        "base": 90,
        "elm": "火",
        "desc": "中火球"
    },
    {
        "id": 302,
        "name": "ベギラマ",
        "type": "魔法",
        "target": "全体",
        "mp": 70,
        "rate": 1.2,
        "count": 1,
        "base": 80,
        "elm": "火",
        "desc": "灼熱の帯"
    },
    {
        "id": 303,
        "name": "ヒャダルコ",
        "type": "魔法",
        "target": "全体",
        "mp": 70,
        "rate": 1.2,
        "count": 1,
        "base": 80,
        "elm": "水",
        "desc": "氷の波動"
    },
    {
        "id": 304,
        "name": "バギマ",
        "type": "魔法",
        "target": "全体",
        "mp": 70,
        "rate": 1.2,
        "count": 1,
        "base": 80,
        "elm": "風",
        "desc": "真空の嵐"
    },
    {
        "id": 305,
        "name": "メラゾーマ",
        "type": "魔法",
        "target": "単体",
        "mp": 150,
        "rate": 2,
        "count": 1,
        "base": 250,
        "elm": "火",
        "desc": "大火球"
    },
    {
        "id": 306,
        "name": "イオナズン",
        "type": "魔法",
        "target": "全体",
        "mp": 250,
        "rate": 1.5,
        "count": 1,
        "base": 230,
        "elm": "光",
        "desc": "大爆発"
    },
    {
        "id": 307,
        "name": "ドルモーア",
        "type": "魔法",
        "target": "単体",
        "mp": 150,
        "rate": 2,
        "count": 1,
        "base": 250,
        "elm": "闇",
        "desc": "闇の爆発"
    },
    {
        "id": 308,
        "name": "イオラ",
        "type": "魔法",
        "target": "全体",
        "mp": 100,
        "rate": 1,
        "count": 1,
        "base": 90,
        "elm": "光",
        "desc": "中爆発"
    },
    {
        "id": 309,
        "name": "バギクロス",
        "type": "魔法",
        "target": "全体",
        "mp": 250,
        "rate": 1.5,
        "count": 1,
        "base": 230,
        "elm": "風",
        "desc": "真空の大嵐"
    },
    {
        "id": 310,
        "name": "ベギラゴン",
        "type": "魔法",
        "target": "全体",
        "mp": 250,
        "rate": 1.5,
        "count": 1,
        "base": 230,
        "elm": "火",
        "desc": "灼熱の波動"
    },
    {
        "id": 401,
        "name": "ギガブレイク",
        "type": "物理",
        "target": "全体",
        "mp": 450,
        "rate": 2,
        "count": 1,
        "base": 250,
        "elm": "雷",
        "desc": "最強の剣技"
    },
    {
        "id": 402,
        "name": "ゴッドハンド",
        "type": "物理",
        "target": "単体",
        "mp": 500,
        "rate": 2.1,
        "count": 1,
        "base": 450,
        "elm": "光",
        "desc": "神の拳"
    },
    {
        "id": 403,
        "name": "ベホマ",
        "type": "回復",
        "target": "単体",
        "mp": 2000,
        "rate": 0,
        "count": 1,
        "base": 99999,
        "fix": true,
        "desc": "完全回復"
    },
    {
        "id": 404,
        "name": "プチメテオ",
        "type": "魔法",
        "target": "ランダム",
        "mp": 600,
        "rate": 0.6,
        "count": 7,
        "base": 170,
        "elm": "火",
        "desc": "小隕石落とし"
    },
    {
        "id": 405,
        "name": "ジゴスパーク",
        "type": "魔法",
        "target": "全体",
        "mp": 550,
        "rate": 2,
        "count": 1,
        "base": 270,
        "elm": "混沌",
        "desc": "地獄の雷"
    },
    {
        "id": 406,
        "name": "マヒャデドス",
        "type": "魔法",
        "target": "全体",
        "mp": 550,
        "rate": 2,
        "count": 1,
        "base": 270,
        "elm": "水",
        "desc": "極大氷魔法"
    },
    {
        "id": 407,
        "name": "メラガイアー",
        "type": "魔法",
        "target": "単体",
        "mp": 400,
        "rate": 2.4,
        "count": 1,
        "base": 500,
        "elm": "火",
        "desc": "極大火炎"
    },
    {
        "id": 408,
        "name": "ギガデイン",
        "type": "魔法",
        "target": "全体",
        "mp": 500,
        "rate": 2.1,
        "count": 1,
        "base": 480,
        "elm": "雷",
        "desc": "極大雷呪文"
    },
    {
        "id": 409,
        "name": "ギガクロスブレイク",
        "type": "物理",
        "target": "単体",
        "mp": 650,
        "rate": 2.1,
        "count": 2,
        "base": 400,
        "elm": "雷",
        "desc": "雷の2連撃"
    },
    {
        "id": 410,
        "name": "シャイニング",
        "type": "魔法",
        "target": "全体",
        "mp": 600,
        "rate": 2.3,
        "count": 1,
        "base": 500,
        "elm": "光",
        "desc": "聖なる光"
    },
    {
        "id": 411,
        "name": "ラグナブレード",
        "type": "物理",
        "target": "単体",
        "mp": 550,
        "rate": 4.5,
        "count": 1,
        "base": 600,
        "elm": "混沌",
        "debuff": {
            "def": 0.5
        },
        "desc": "混沌の一撃"
    },
    {
        "id": 412,
        "name": "イオグランデ",
        "type": "魔法",
        "target": "全体",
        "mp": 550,
        "rate": 2.1,
        "count": 1,
        "base": 480,
        "elm": "光",
        "desc": "極大爆発"
    },
    {
        "id": 413,
        "name": "裁きの雷霆",
        "type": "魔法",
        "target": "ランダム",
        "mp": 500,
        "rate": 0.9,
        "count": 4,
        "base": 100,
        "elm": "雷",
        "Shock": true,
        "SuccessRate": 100,
        "desc": "雷魔法超ダメージ5連・感電付与",
        "turn": 5
    },
    {
        "id": 414,
        "name": "グランドクロス",
        "type": "物理",
        "target": "全体",
        "mp": 500,
        "rate": 1,
        "count": 2,
        "base": 999,
        "elm": "風",
        "desc": "十字に切り裂く2連撃"
    },
    {
        "id": 415,
        "name": "絶対零度",
        "type": "魔法",
        "target": "単体",
        "mp": 600,
        "rate": 2.5,
        "count": 1,
        "base": 450,
        "elm": "水",
        "desc": "凍てつく極大魔法"
    },
    {
        "id": 416,
        "name": "メテオ",
        "type": "魔法",
        "target": "単体",
        "mp": 900,
        "rate": 1.1,
        "count": 7,
        "base": 450,
        "elm": "火",
        "desc": "隕石落とし"
    },
    {
        "id": 420,
        "name": "神避",
        "type": "物理",
        "target": "全体",
        "mp": 500,
        "rate": 1.2,
        "count": 1,
        "base": 0,
        "priority": 5,
        "desc": "神速で全てを薙ぎ払う"
    },
    {
        "id": 421,
        "name": "アルテマソード",
        "type": "物理",
        "target": "単体",
        "mp": 600,
        "rate": 6,
        "count": 1,
        "base": 500,
        "desc": "究極の剣技"
    },
    {
        "id": 450,
        "name": "ベホマズン",
        "type": "回復",
        "target": "全体",
        "mp": 4000,
        "rate": 0,
        "count": 1,
        "base": 99999,
        "fix": true,
        "desc": "全体完全回復"
    },
    {
        "id": 451,
        "name": "いやしのあめ",
        "type": "特殊",
        "target": "全体",
        "mp": 300,
        "rate": 0,
        "count": 1,
        "base": 0,
        "HPRegen": 0.1,
        "turn": 5,
        "desc": "毎ターンHP回復"
    },
    {
        "id": 452,
        "name": "まりょくのかぜ",
        "type": "特殊",
        "target": "全体",
        "mp": 20,
        "rate": 0,
        "count": 1,
        "base": 0,
        "MPRegen": 0.05,
        "turn": 5,
        "desc": "毎ターンMP回復"
    },
    {
        "id": 453,
        "name": "秒間ホイミ",
        "type": "回復",
        "target": "単体",
        "mp": 200,
        "rate": 1.5,
        "count": 1,
        "base": 999,
        "priority": 20,
        "desc": "使い手の少ない最速の回復呪文"
    },
    {
        "id": 454,
        "name": "不死鳥の灰",
        "type": "回復",
        "target": "自分",
        "mp": 2000,
        "rate": 1,
        "count": 1,
        "base": 99999,
        "CureAilments": true,
        "priority": -20,
        "desc": "全てを受け止めて生還する不死鳥"
    },
    {
        "id": 500,
        "name": "マダンテ",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 6,
        "count": 1,
        "base": 300,
        "priority": -1,
        "elm": "混沌",
        "desc": "全MPを消費し大爆発"
    },
    {
        "id": 601,
        "name": "火炎の息",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 90,
        "elm": "火",
        "desc": "炎の息"
    },
    {
        "id": 602,
        "name": "こごえる吹雪",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 100,
        "elm": "水",
        "desc": "冷たい息"
    },
    {
        "id": 603,
        "name": "はげしい炎",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 130,
        "elm": "火",
        "desc": "激しい炎"
    },
    {
        "id": 604,
        "name": "かがやく息",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 150,
        "elm": "水",
        "desc": "極寒の息"
    },
    {
        "id": 605,
        "name": "しゃくねつ",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 200,
        "elm": "火",
        "desc": "灼熱の業火"
    },
    {
        "id": 606,
        "name": "絶対零度",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 200,
        "elm": "水",
        "desc": "全てを凍らす息"
    },
    {
        "id": 607,
        "name": "暗黒のきり",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 80,
        "elm": "闇",
        "desc": "暗黒のきり"
    },
    {
        "id": 608,
        "name": "いなずま",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 110,
        "elm": "雷",
        "desc": "稲妻"
    },
    {
        "id": 609,
        "name": "煉獄火炎",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 1.4,
        "count": 1,
        "base": 250,
        "elm": "混沌",
        "desc": "地獄の炎"
    },
    {
        "id": 610,
        "name": "シャイニングブレス",
        "type": "魔法",
        "target": "全体",
        "mp": 50,
        "rate": 1.4,
        "count": 1,
        "base": 150,
        "elm": "光",
        "SpellSeal": true,
        "SkillSeal": true,
        "HealSeal": true,
        "SuccessRate": 50,
        "turn": 3,
        "desc": "光のブレス・スキル封印"
    },
    {
        "id": 611,
        "name": "ダークネスブレス",
        "type": "魔法",
        "target": "全体",
        "mp": 50,
        "rate": 1.4,
        "count": 1,
        "base": 150,
        "elm": "闇",
        "debuff": {
            "elmResDown": 50
        },
        "SuccessRate": 50,
        "turn": 3,
        "desc": "闇のブレス・属性耐性ダウン"
    },
    {
        "id": 612,
        "name": "霜白の氷塊",
        "type": "魔法",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 1000,
        "desc": "",
        "elm": "水"
    },
    {
        "id": 613,
        "name": "紅蓮の炎",
        "type": "物理",
        "target": "全体",
        "mp": 0,
        "rate": 0.8,
        "count": 1,
        "base": 1000,
        "desc": "",
        "elm": "火"
    },
    {
        "id": 614,
        "name": "ウイングダイブ",
        "type": "物理",
        "target": "全体",
        "mp": 350,
        "rate": 1.1,
        "count": 2,
        "base": 500,
        "desc": "",
        "elm": "風"
    },
    {
        "id": 615,
        "name": "竜の咆哮",
        "type": "特殊",
        "target": "全体",
        "mp": 0,
        "rate": 1,
        "count": 1,
        "base": 0,
        "desc": "",
        "buff_reset": true,
        "Fear": true,
        "SuccessRate": 100,
        "PercentDamage": 0,
        "turn": 1,
        "priority": -20,
        "elm": null
    },
    {
        "id": 701,
        "name": "どくのいき",
        "type": "特殊",
        "target": "全体",
        "mp": 0,
        "rate": 0,
        "count": 1,
        "base": 500,
        "Poison": true,
        "SuccessRate": 80,
        "desc": "どくのいき"
    },
    {
        "id": 901,
        "name": "ジェネシス",
        "type": "魔法",
        "target": "全体",
        "mp": 500,
        "rate": 3,
        "count": 1,
        "base": 800,
        "elm": "混沌",
        "desc": "【EX】天地創造の光"
    },
    {
        "id": 902,
        "name": "ラグナロク",
        "type": "物理",
        "target": "ランダム",
        "mp": 700,
        "rate": 1,
        "count": 5,
        "base": 350,
        "elm": "闇",
        "desc": "【EX】終焉の5連撃"
    },
    {
        "id": 903,
        "name": "ザオリーマ",
        "type": "蘇生",
        "target": "全体",
        "mp": 1000,
        "rate": 0.8,
        "count": 1,
        "base": 150,
        "desc": "【EX】味方全員を完全蘇生"
    },
    {
        "id": 905,
        "name": "やみのはどう",
        "type": "弱体",
        "target": "全体",
        "mp": 500,
        "rate": 0,
        "count": 1,
        "base": 20,
        "SuccessRate": 0.8,
        "debuff": {
            "atk": 0.7,
            "def": 0.7,
            "mag": 0.7,
            "spd": 0.7
        },
        "desc": "全能力ダウン"
    },
    {
        "id": 906,
        "name": "創世の魔力",
        "type": "魔法",
        "target": "全体",
        "mp": 1000,
        "rate": 3.5,
        "count": 1,
        "base": 800,
        "elm": "混沌",
        "debuff": {
            "atk": 0.7,
            "def": 0.7,
            "mag": 0.7,
            "spd": 0.7
        },
        "desc": "【EX】世界を創り変える力"
    },
    {
        "id": 907,
        "name": "おぞましいおたけび",
        "type": "特殊",
        "target": "全体",
        "mp": 1000,
        "rate": 0,
        "count": 1,
        "base": 0,
        "PercentDamage": 0.5,
        "Fear": true,
        "SuccessRate": 0.5,
        "turn": 1,
        "desc": "心まで凍り付く恐ろしいおたけび"
    },
    {
        "id": 908,
        "name": "魔触",
        "type": "魔法",
        "target": "全体",
        "mp": 1000,
        "rate": 0.7,
        "count": 2,
        "base": 50,
        "Fear": true,
        "ToxicPoison": true,
        "SpellSeal": true,
        "SkillSeal": true,
        "HealSeal": true,
        "SuccessRate": 30,
        "turn": 1,
        "elm": "混沌",
        "desc": "闇の根源より漏れ出る災禍"
    },
    {
        "id": 920,
        "name": "王者の一閃",
        "type": "物理",
        "target": "単体",
        "mp": 300,
        "rate": 4,
        "count": 1,
        "base": 0,
        "debuff": {
            "def": 0.5
        },
        "priority": -1,
        "desc": "王者の威光を纏った一撃"
    },
    {
        "id": 921,
        "name": "サイコキャノン",
        "type": "魔法",
        "target": "単体",
        "mp": 300,
        "rate": 1.5,
        "count": 1,
        "base": 500,
        "drain": true,
        "desc": "精神エネルギー砲・HP吸収"
    },
    {
        "id": 922,
        "name": "サイコストーム",
        "type": "魔法",
        "target": "ランダム",
        "mp": 700,
        "rate": 1,
        "count": 4,
        "base": 300,
        "drain": true,
        "desc": "精神の嵐・HP吸収"
    },
    {
        "id": 923,
        "name": "カラミティエンド",
        "type": "物理",
        "target": "単体",
        "mp": 1200,
        "rate": 3,
        "count": 1,
        "base": 500,
        "IgnoreDefense": true,
        "SuccessRate": 100,
        "desc": "全てを断ち切る大魔王の右腕"
    },
    {
        "id": 924,
        "name": "カラミティウォール",
        "type": "魔法",
        "target": "全体",
        "mp": 1000,
        "rate": 2,
        "count": 1,
        "base": 1000,
        "elm": "混沌",
        "desc": "厄災の壁"
    },
    {
        "id": 925,
        "name": "カイザーフェニックス",
        "type": "魔法",
        "target": "単体",
        "mp": 1000,
        "rate": 3,
        "count": 1,
        "base": 5000,
        "elm": "火",
        "desc": "大魔王のメラゾーマ"
    },
    {
        "id": 926,
        "name": "心ない天使",
        "type": "特殊",
        "target": "単体",
        "mp": 5000,
        "rate": 0,
        "count": 1,
        "base": 0,
        "PercentDamage": 0.99,
        "SuccessRate": 100,
        "priority": -5,
        "desc": "無慈悲な一撃"
    },
    {
        "id": 999,
        "name": "アルテマ",
        "type": "魔法",
        "target": "単体",
        "mp": 0,
        "rate": 0,
        "count": 1,
        "base": 99999,
        "fix": true,
        "priority": -1,
        "desc": "単体極大ダメージ"
    }
];
